### ISSUE TITLE
Issue with Spee::CreditCard Module unable to change from confirm to complete order state  

### ISSUE THREAD

**Issue by kshtzkr** [spree/spree#10089]
Issue with Spee::CreditCard Module unable to change from confirm to complete order state  
## Expected Behavior

it should just deduct the payment and move to change the order state from **confirm** to **complete**

## Actual Behavior

it's get crashed in the credit card module 
Exactly in this function first and the second line I am not sure why when I have already completed the payment state and then moved to confirmed state this is a critical issue 
```
`def set_last_digits
      number.to_s.gsub!(/\s/, '')
      verification_value.to_s.gsub!(/\s/, '')
      self.last_digits ||= number.to_s.length <= 4 ? number : number.to_s.slice(-4..-1)
    end`

```
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

```
`Gem Lock version
`GEM
  remote: https://rubygems.org/
  specs:
    actioncable (6.0.2.1)
      actionpack (= 6.0.2.1)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.0.2.1)
      actionpack (= 6.0.2.1)
      activejob (= 6.0.2.1)
      activerecord (= 6.0.2.1)
      activestorage (= 6.0.2.1)
      activesupport (= 6.0.2.1)
      mail (>= 2.7.1)
    actionmailer (6.0.2.1)
      actionpack (= 6.0.2.1)
      actionview (= 6.0.2.1)
      activejob (= 6.0.2.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.0.2.1)
      actionview (= 6.0.2.1)
      activesupport (= 6.0.2.1)
      rack (~> 2.0, >= 2.0.8)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.0.2.1)
      actionpack (= 6.0.2.1)
      activerecord (= 6.0.2.1)
      activestorage (= 6.0.2.1)
      activesupport (= 6.0.2.1)
      nokogiri (>= 1.8.5)
    actionview (6.0.2.1)
      activesupport (= 6.0.2.1)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (6.0.2.1)
      activesupport (= 6.0.2.1)
      globalid (>= 0.3.6)
    activemerchant (1.104.0)
      activesupport (>= 4.2)
      builder (>= 2.1.2, < 4.0.0)
      i18n (>= 0.6.9)
      nokogiri (~> 1.4)
    activemodel (6.0.2.1)
      activesupport (= 6.0.2.1)
    activerecord (6.0.2.1)
      activemodel (= 6.0.2.1)
      activesupport (= 6.0.2.1)
    activestorage (6.0.2.1)
      actionpack (= 6.0.2.1)
      activejob (= 6.0.2.1)
      activerecord (= 6.0.2.1)
      marcel (~> 0.3.1)
    activesupport (6.0.2.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
      zeitwerk (~> 2.2)
    acts_as_list (0.9.19)
      activerecord (>= 3.0)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    airbrussh (1.4.0)
      sshkit (>= 1.6.1, != 1.7.0)
    ast (2.4.0)
    autoprefixer-rails (9.7.4)
      execjs
    awesome_nested_set (3.2.0)
      activerecord (>= 4.0.0, < 7.0)
    awesome_print (1.8.0)
    axiom-types (0.1.1)
      descendants_tracker (~> 0.0.4)
      ice_nine (~> 0.11.0)
      thread_safe (~> 0.3, >= 0.3.1)
    bcrypt (3.1.13)
    bootsnap (1.4.5)
      msgpack (~> 1.0)
    bootstrap (4.3.1)
      autoprefixer-rails (>= 9.1.0)
      popper_js (>= 1.14.3, < 2)
      sassc-rails (>= 2.0.0)
    builder (3.2.4)
    bullet (6.1.0)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.11)
    byebug (11.1.1)
    camertron-eprun (1.1.1)
    cancancan (3.0.2)
    canonical-rails (0.2.6)
      rails (>= 4.1, < 6.1)
    capistrano (3.12.0)
      airbrussh (>= 1.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-bundler (1.6.0)
      capistrano (~> 3.1)
    capistrano-rails (1.4.0)
      capistrano (~> 3.1)
      capistrano-bundler (~> 1.1)
    capistrano-rvm (0.1.2)
      capistrano (~> 3.0)
      sshkit (~> 1.2)
    capistrano3-puma (4.0.0)
      capistrano (~> 3.7)
      capistrano-bundler
      puma (~> 4.0)
    carmen (1.1.3)
      activesupport (>= 3.0.0)
    carrierwave (2.0.2)
      activemodel (>= 5.0.0)
      activesupport (>= 5.0.0)
      addressable (~> 2.6)
      image_processing (~> 1.1)
      mimemagic (>= 0.3.0)
      mini_mime (>= 0.1.3)
    cldr-plurals-runtime-rb (1.0.1)
    code_analyzer (0.5.1)
      sexp_processor
    codeclimate-engine-rb (0.4.1)
      virtus (~> 1.0)
    coderay (1.1.2)
    coercible (1.0.0)
      descendants_tracker (~> 0.0.1)
    concurrent-ruby (1.1.5)
    crass (1.0.6)
    css_parser (1.7.1)
      addressable
    deface (1.5.3)
      nokogiri (>= 1.6)
      polyglot
      rails (>= 4.1)
      rainbow (>= 2.1.0)
    descendants_tracker (0.0.4)
      thread_safe (~> 0.3, >= 0.3.1)
    devise (4.7.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    devise-encryptable (0.2.0)
      devise (>= 2.1.0)
    devise-jwt (0.6.0)
      devise (~> 4.0)
      warden-jwt_auth (~> 0.4)
    diff-lcs (1.3)
    docile (1.3.2)
    doorkeeper (5.3.1)
      railties (>= 5)
    dotenv (2.7.5)
    dotenv-rails (2.7.5)
      dotenv (= 2.7.5)
      railties (>= 3.2, < 6.1)
    dry-auto_inject (0.7.0)
      dry-container (>= 0.3.4)
    dry-configurable (0.9.0)
      concurrent-ruby (~> 1.0)
      dry-core (~> 0.4, >= 0.4.7)
    dry-container (0.7.2)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1, >= 0.1.3)
    dry-core (0.4.9)
      concurrent-ruby (~> 1.0)
    equalizer (0.0.11)
    erubi (1.9.0)
    erubis (2.7.0)
    execjs (2.7.0)
    fast_jsonapi (1.5)
      activesupport (>= 4.2)
    ffaker (2.13.0)
    ffi (1.12.1)
    flay (2.12.1)
      erubis (~> 2.7.0)
      path_expander (~> 1.0)
      ruby_parser (~> 3.0)
      sexp_processor (~> 4.0)
    flog (4.6.4)
      path_expander (~> 1.0)
      ruby_parser (~> 3.1, > 3.1.0)
      sexp_processor (~> 4.8)
    friendly_id (5.3.0)
      activerecord (>= 4.0.0)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    glyphicons (1.0.2)
    graphiql-rails (1.7.0)
      railties
      sprockets-rails
    graphql (1.10.0)
    highline (2.0.3)
    htmlentities (4.3.4)
    i18n (1.8.2)
      concurrent-ruby (~> 1.0)
    ice_nine (0.11.2)
    image_processing (1.10.3)
      mini_magick (>= 4.9.5, < 5)
      ruby-vips (>= 2.0.17, < 3)
    inline_svg (1.7.0)
      activesupport (>= 3.0)
      nokogiri (>= 1.6)
    jaro_winkler (1.5.4)
    jquery-rails (4.3.5)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (6.0.1)
      railties (>= 3.2.16)
    json (2.3.0)
    jwt (2.2.1)
    kaminari (1.1.1)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.1.1)
      kaminari-activerecord (= 1.1.1)
      kaminari-core (= 1.1.1)
    kaminari-actionview (1.1.1)
      actionview
      kaminari-core (= 1.1.1)
    kaminari-activerecord (1.1.1)
      activerecord
      kaminari-core (= 1.1.1)
    kaminari-core (1.1.1)
    kwalify (0.7.2)
    launchy (2.4.3)
      addressable (~> 2.3)
    letter_opener (1.7.0)
      launchy (~> 2.2)
    letter_opener_web (1.4.0)
      actionmailer (>= 3.2)
      letter_opener (~> 1.0)
      railties (>= 3.2)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.4.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (0.3.3)
      mimemagic (~> 0.3.2)
    method_source (0.9.2)
    mimemagic (0.3.4)
    mini_magick (4.10.1)
    mini_mime (1.0.2)
    mini_portile2 (2.4.0)
    minitest (5.14.0)
    monetize (1.9.4)
      money (~> 6.12)
    money (6.13.7)
      i18n (>= 0.6.4, <= 2)
    msgpack (1.3.1)
    mysql2 (0.5.3)
    net-scp (2.0.0)
      net-ssh (>= 2.6.5, < 6.0.0)
    net-ssh (5.2.0)
    nio4r (2.5.2)
    nokogiri (1.10.7)
      mini_portile2 (~> 2.4.0)
    orm_adapter (0.5.0)
    parallel (1.19.1)
    paranoia (2.4.2)
      activerecord (>= 4.0, < 6.1)
    parser (2.7.0.2)
      ast (~> 2.4.0)
    path_expander (1.1.0)
    polyamorous (2.3.2)
      activerecord (>= 5.2.1)
    polyglot (0.3.5)
    popper_js (1.16.0)
    premailer (1.11.1)
      addressable
      css_parser (>= 1.6.0)
      htmlentities (>= 4.0.0)
    premailer-rails (1.10.3)
      actionmailer (>= 3)
      premailer (~> 1.7, >= 1.7.9)
    pry (0.12.2)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    pry-rails (0.3.9)
      pry (>= 0.10.4)
    psych (3.1.0)
    public_suffix (4.0.3)
    puma (4.3.1)
      nio4r (~> 2.0)
    rabl (0.14.2)
      activesupport (>= 2.3.14)
    rack (2.1.2)
    rack-cors (1.1.1)
      rack (>= 2.0.0)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (6.0.2.1)
      actioncable (= 6.0.2.1)
      actionmailbox (= 6.0.2.1)
      actionmailer (= 6.0.2.1)
      actionpack (= 6.0.2.1)
      actiontext (= 6.0.2.1)
      actionview (= 6.0.2.1)
      activejob (= 6.0.2.1)
      activemodel (= 6.0.2.1)
      activerecord (= 6.0.2.1)
      activestorage (= 6.0.2.1)
      activesupport (= 6.0.2.1)
      bundler (>= 1.3.0)
      railties (= 6.0.2.1)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.3.0)
      loofah (~> 2.3)
    rails_best_practices (1.19.5)
      activesupport
      code_analyzer (>= 0.5.1)
      erubis
      i18n
      json
      require_all (~> 3.0)
      ruby-progressbar
    railties (6.0.2.1)
      actionpack (= 6.0.2.1)
      activesupport (= 6.0.2.1)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.20.3, < 2.0)
    rainbow (3.0.0)
    rake (13.0.1)
    ransack (2.3.2)
      activerecord (>= 5.2.1)
      activesupport (>= 5.2.1)
      i18n
      polyamorous (= 2.3.2)
    rb-fsevent (0.10.3)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    reek (5.6.0)
      codeclimate-engine-rb (~> 0.4.0)
      kwalify (~> 0.7.0)
      parser (>= 2.5.0.0, < 2.8, != 2.5.1.1)
      psych (~> 3.1.0)
      rainbow (>= 2.0, < 4.0)
    require_all (3.0.0)
    responders (3.0.0)
      actionpack (>= 5.0)
      railties (>= 5.0)
    rmagick (4.0.0)
    rspec-core (3.9.1)
      rspec-support (~> 3.9.1)
    rspec-expectations (3.9.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.9.0)
    rspec-mocks (3.9.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.9.0)
    rspec-rails (3.9.0)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.9.0)
      rspec-expectations (~> 3.9.0)
      rspec-mocks (~> 3.9.0)
      rspec-support (~> 3.9.0)
    rspec-support (3.9.2)
    rubocop (0.79.0)
      jaro_winkler (~> 1.5.1)
      parallel (~> 1.10)
      parser (>= 2.7.0.1)
      rainbow (>= 2.2.2, < 4.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 1.7)
    rubocop-rails (2.4.2)
      rack (>= 1.1)
      rubocop (>= 0.72.0)
    ruby-progressbar (1.10.1)
    ruby-vips (2.0.17)
      ffi (~> 1.9)
    ruby_dep (1.5.0)
    ruby_parser (3.14.2)
      sexp_processor (~> 4.9)
    rubycritic (4.4.0)
      flay (~> 2.8)
      flog (~> 4.4)
      launchy (= 2.4.3)
      parser (>= 2.6.0)
      rainbow (~> 3.0)
      reek (~> 5.0, < 6.0)
      ruby_parser (~> 3.8)
      simplecov (>= 0.17.0)
      tty-which (~> 0.4.0)
      virtus (~> 1.0)
    sassc (2.2.1)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    select2-rails (3.5.10)
      thor (~> 0.14)
    sexp_processor (4.14.1)
    simplecov (0.18.2)
      docile (~> 1.1)
      simplecov-html (~> 0.11)
    simplecov-html (0.12.0)
    spree (4.1.0.rc3)
      spree_api (= 4.1.0.rc3)
      spree_backend (= 4.1.0.rc3)
      spree_cmd (= 4.1.0.rc3)
      spree_core (= 4.1.0.rc3)
      spree_frontend (= 4.1.0.rc3)
      spree_sample (= 4.1.0.rc3)
    spree_api (4.1.0.rc3)
      doorkeeper (~> 5.2, >= 5.2.1)
      fast_jsonapi (~> 1.5)
      rabl (~> 0.14.2)
      spree_core (= 4.1.0.rc3)
    spree_auth_devise (4.1.0)
      deface (~> 1.0)
      devise (~> 4.7)
      devise-encryptable (= 0.2.0)
      spree_core (>= 4.1.0.alpha, < 5.0)
      spree_extension
    spree_backend (4.1.0.rc3)
      bootstrap (~> 4.3.1)
      glyphicons (~> 1.0.2)
      jquery-rails (~> 4.3)
      jquery-ui-rails (~> 6.0.1)
      select2-rails (~> 3.5.0)
      spree_api (= 4.1.0.rc3)
      spree_core (= 4.1.0.rc3)
    spree_cmd (4.1.0.rc3)
      thor (~> 0.14)
    spree_core (4.1.0.rc3)
      activemerchant (~> 1.67)
      acts_as_list (~> 0.8)
      awesome_nested_set (>= 3.1.4, < 3.3.0)
      cancancan (~> 3.0)
      carmen (>= 1.0, < 1.2)
      ffaker (~> 2.9)
      friendly_id (>= 5.2.1, < 5.4.0)
      highline (~> 2.0.0)
      image_processing (~> 1.2)
      kaminari (>= 1.0.1, < 1.2.0)
      mini_magick (>= 4.9.4, < 4.11.0)
      monetize (~> 1.9)
      money (~> 6.13)
      paranoia (~> 2.4.2)
      premailer-rails
      rails (~> 6.0.0)
      ransack (~> 2.3.0)
      responders
      sprockets (~> 3.7)
      sprockets-rails
      state_machines-activemodel (~> 0.7)
      state_machines-activerecord (~> 0.6)
      stringex
      twitter_cldr (>= 4.3, < 6.0)
    spree_extension (0.0.9)
      activerecord (>= 4.2)
      spree_core
    spree_frontend (4.1.0.rc3)
      bootstrap (~> 4.3.1)
      canonical-rails (~> 0.2.5)
      glyphicons (~> 1.0.2)
      inline_svg (~> 1.5)
      jquery-rails (~> 4.3)
      spree_api (= 4.1.0.rc3)
      spree_core (= 4.1.0.rc3)
      turbolinks (~> 5.2.0)
    spree_gateway (3.7.0)
      spree_core (>= 3.1.0, < 5.0)
      spree_extension
    spree_sample (4.1.0.rc3)
      spree_core (= 4.1.0.rc3)
    spring (2.1.0)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sshkit (1.20.0)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    state_machines (0.5.0)
    state_machines-activemodel (0.7.1)
      activemodel (>= 4.1)
      state_machines (>= 0.5.0)
    state_machines-activerecord (0.6.0)
      activerecord (>= 4.1)
      state_machines-activemodel (>= 0.5.0)
    stringex (2.8.5)
    strip_attributes (1.9.0)
      activemodel (>= 3.0, < 7.0)
    stripe (5.17.0)
    stripe-rails (1.10.0)
      rails (>= 3)
      responders
      stripe (>= 1.36.2)
    thor (0.20.3)
    thread_safe (0.3.6)
    tilt (2.0.10)
    tty-which (0.4.2)
    turbolinks (5.2.1)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    twitter_cldr (5.3.0)
      camertron-eprun
      cldr-plurals-runtime-rb (~> 1.0)
      tzinfo
    tzinfo (1.2.6)
      thread_safe (~> 0.1)
    unicode-display_width (1.6.1)
    uniform_notifier (1.13.0)
    virtus (1.0.5)
      axiom-types (~> 0.1)
      coercible (~> 1.0)
      descendants_tracker (~> 0.0, >= 0.0.3)
      equalizer (~> 0.0, >= 0.0.9)
    warden (1.2.8)
      rack (>= 2.0.6)
    warden-jwt_auth (0.4.0)
      dry-auto_inject (~> 0.6)
      dry-configurable (~> 0.8)
      jwt (~> 2.1)
      warden (~> 1.2)
    websocket-driver (0.7.1)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.4)
    zeitwerk (2.2.2)

PLATFORMS
  ruby

DEPENDENCIES
  addressable (~> 2.7)
  awesome_print (~> 1.8)
  bootsnap (>= 1.4.2)
  bullet (~> 6.1)
  byebug
  capistrano (~> 3.10)
  capistrano-rails (~> 1.4)
  capistrano-rvm
  capistrano3-puma
  carrierwave (~> 2.0, >= 2.0.2)
  devise (~> 4.7, >= 4.7.1)
  devise-jwt (~> 0.6.0)
  dotenv-rails (~> 2.7)
  graphiql-rails (~> 1.7)
  graphql (~> 1.10)
  image_processing (~> 1.2)
  jwt (~> 2.2, >= 2.2.1)
  letter_opener_web (~> 1.0)
  listen (>= 3.0.5, < 3.2)
  mysql2 (~> 0.5.3)
  paranoia (~> 2.4)
  pry-rails (~> 0.3.9)
  puma (~> 4.1)
  rack-cors (~> 1.1, >= 1.1.1)
  rails (~> 6.0.2, >= 6.0.2.1)
  rails_best_practices
  rmagick (~> 4.0)
  rspec-rails (~> 3.9)
  rubocop-rails (~> 2.4, >= 2.4.2)
  rubycritic (~> 4.4)
  spree (~> 4.1.0.rc3)
  spree_auth_devise (~> 4.1)
  spree_gateway (~> 3.7)
  spring
  spring-watcher-listen (~> 2.0.0)
  strip_attributes (~> 1.9)
  stripe-rails (~> 1.10)
  tzinfo-data

RUBY VERSION
   ruby 2.7.0p0

BUNDLED WITH
   2.1.2
``
```

```
`Completed 500 Internal Server Error in 4301ms (ActiveRecord: 2567.9ms | Allocations: 189601)


  
FrozenError (can't modify frozen String: ""):
  
spree_core (4.1.0.rc3) app/models/spree/credit_card.rb:105:in `gsub!'
spree_core (4.1.0.rc3) app/models/spree/credit_card.rb:105:in `set_last_digits'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:429:in `block in make_lambda'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:607:in `block (2 levels) in default_terminator'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:606:in `catch'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:606:in `block in default_terminator'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:202:in `block in halting'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:514:in `block in invoke_before'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:514:in `each'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:514:in `invoke_before'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:134:in `run_callbacks'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
activerecord (6.0.2.1) lib/active_record/callbacks.rb:328:in `create_or_update'
activerecord (6.0.2.1) lib/active_record/timestamp.rb:129:in `create_or_update'
activerecord (6.0.2.1) lib/active_record/persistence.rb:470:in `save'
activerecord (6.0.2.1) lib/active_record/validations.rb:47:in `save'
activerecord (6.0.2.1) lib/active_record/transactions.rb:315:in `block in save'
activerecord (6.0.2.1) lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
activerecord (6.0.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:279:in `transaction'
activerecord (6.0.2.1) lib/active_record/transactions.rb:212:in `transaction'
activerecord (6.0.2.1) lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
activerecord (6.0.2.1) lib/active_record/transactions.rb:315:in `save'
activerecord (6.0.2.1) lib/active_record/suppressor.rb:44:in `save'
activerecord (6.0.2.1) lib/active_record/persistence.rb:621:in `block in update'
activerecord (6.0.2.1) lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
activerecord (6.0.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `block in transaction'
activerecord (6.0.2.1) lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
activerecord (6.0.2.1) lib/active_record/connection_adapters/abstract/transaction.rb:278:in `synchronize'
activerecord (6.0.2.1) lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
activerecord (6.0.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `transaction'
activerecord (6.0.2.1) lib/active_record/transactions.rb:212:in `transaction'
activerecord (6.0.2.1) lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
activerecord (6.0.2.1) lib/active_record/persistence.rb:619:in `update'
spree_core (4.1.0.rc3) app/models/spree/order/checkout.rb:269:in `persist_user_credit_card'
state_machines (0.5.0) lib/state_machines/eval_helpers.rb:58:in `evaluate_method'
state_machines (0.5.0) lib/state_machines/callback.rb:192:in `block in run_methods'
state_machines (0.5.0) lib/state_machines/callback.rb:191:in `each'
state_machines (0.5.0) lib/state_machines/callback.rb:191:in `run_methods'
state_machines (0.5.0) lib/state_machines/callback.rb:159:in `call'
state_machines (0.5.0) lib/state_machines/transition.rb:394:in `block (2 levels) in after'
state_machines (0.5.0) lib/state_machines/transition.rb:394:in `each'
state_machines (0.5.0) lib/state_machines/transition.rb:394:in `block in after'
state_machines (0.5.0) lib/state_machines/transition.rb:392:in `catch'
state_machines (0.5.0) lib/state_machines/transition.rb:392:in `after'
state_machines (0.5.0) lib/state_machines/transition.rb:195:in `run_callbacks'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:127:in `run_callbacks'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:63:in `block (2 levels) in perform'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:63:in `catch'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:63:in `block in perform'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:186:in `within_transaction'
state_machines (0.5.0) lib/state_machines/transition_collection.rb:62:in `perform'
state_machines (0.5.0) lib/state_machines/transition.rb:163:in `perform'
state_machines (0.5.0) lib/state_machines/event.rb:155:in `fire'
state_machines (0.5.0) lib/state_machines/event.rb:219:in `block in add_actions'
state_machines (0.5.0) lib/state_machines/machine.rb:729:in `block (2 levels) in define_helper'
spree_frontend (4.1.0.rc3) app/controllers/spree/checkout_controller.rb:36:in `update'
actionpack (6.0.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.2.1) lib/abstract_controller/base.rb:196:in `process_action'
actionpack (6.0.2.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.2.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.2.1) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.2.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.2.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.2.1) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.2.1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.2.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.2.1) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.2.1) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.2.1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (6.0.2.1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (6.0.2.1) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
actionpack (6.0.2.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.2.1) lib/action_dispatch/routing/route_set.rb:837:in `call'
railties (6.0.2.1) lib/rails/engine.rb:526:in `call'
railties (6.0.2.1) lib/rails/railtie.rb:190:in `public_send'
railties (6.0.2.1) lib/rails/railtie.rb:190:in `method_missing'
actionpack (6.0.2.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (6.0.2.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.2.1) lib/action_dispatch/routing/route_set.rb:837:in `call'
warden-jwt_auth (0.4.0) lib/warden/jwt_auth/middleware/token_dispatcher.rb:20:in `call'
warden-jwt_auth (0.4.0) lib/warden/jwt_auth/middleware/revocation_manager.rb:21:in `call'
rack (2.1.2) lib/rack/builder.rb:177:in `call'
warden-jwt_auth (0.4.0) lib/warden/jwt_auth/middleware.rb:23:in `call'
bullet (6.1.0) lib/bullet/rack.rb:12:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.1.2) lib/rack/tempfile_reaper.rb:17:in `call'
rack (2.1.2) lib/rack/etag.rb:27:in `call'
rack (2.1.2) lib/rack/conditional_get.rb:40:in `call'
rack (2.1.2) lib/rack/head.rb:14:in `call'
actionpack (6.0.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.1.2) lib/rack/session/abstract/id.rb:269:in `context'
rack (2.1.2) lib/rack/session/abstract/id.rb:263:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.2.1) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.1.2) lib/rack/method_override.rb:24:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (6.0.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
railties (6.0.2.1) lib/rails/engine.rb:526:in `call'
puma (4.3.1) lib/puma/configuration.rb:228:in `call'
puma (4.3.1) lib/puma/server.rb:681:in `handle_request'
puma (4.3.1) lib/puma/server.rb:472:in `process_client'
puma (4.3.1) lib/puma/server.rb:328:in `block in run'
puma (4.3.1) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
`
```

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/10090
