### ISSUE TITLE
upgrade to 4.2-rc4 spree globalize break with error: Missing helper file helpers/spree_i18n/locale_helper.rb (AbstractController::Helpers::MissingHelperError)

### ISSUE THREAD

**Issue by channainfo** [spree/spree#10722]
I followed this guide https://guides.spreecommerce.org/developer/upgrades/four-dot-one-to-four-dot-two.html to upgrade from 4.2-rc2 to 4.2-rc4, however, when I deployed to Heroku I've got the following error:

```
Error: The application encountered the following error: Missing helper file helpers/spree_i18n/locale_helper.rb (AbstractController::Helpers::MissingHelperError)
```

## Application load error

 Below is my Gemfile

```
gem 'spree', '~> 4.2.0.rc4'
gem 'spree_auth_devise', '~> 4.3'
gem 'spree_gateway', '> 3.9'

gem 'spree_i18n', github: 'spree-contrib/spree_i18n', branch: :master
gem 'spree_i18n', '~> 5.0', github: 'spree-contrib/spree_i18n', branch: 'master'

gem 'spree_globalize', github: 'spree-contrib/spree_globalize'
```

I've checked the line that caused the error:
```
#  spree_globalize-f0ebc983c68c/app/controllers/spree/admin/translations_controller.rb:5
helper 'spree_i18n/locale'
```
I checked this file app/helpers/spree_i18n/locale_helper.rb no longer exists in the latest spree_i18n gem.

Is spree_globalize compatible with current master spree_i18n? 

## Environment

* Rails env: production
* Version used: spree-4.2-rc4
* Gemfile and Gemfile.lock as text in a Gist: https://gist.github.com/channainfo/6fa57b777933288bda042b54a0abd9ac
* Any relevant stack traces ("Full trace" preferred):
```
| App 257 output: Error: The application encountered the following error: Missing helper file helpers/spree_i18n/locale_helper.rb (AbstractController::Helpers::MissingHelperError)
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.4/lib/abstract_controller/helpers.rb:152:in `rescue in block in modules_for_helpers'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.4/lib/abstract_controller/helpers.rb:149:in `block in modules_for_helpers'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.4/lib/abstract_controller/helpers.rb:145:in `map!'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.4/lib/abstract_controller/helpers.rb:145:in `modules_for_helpers'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.4/lib/action_controller/metal/helpers.rb:94:in `modules_for_helpers'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.4/lib/abstract_controller/helpers.rb:109:in `helper'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/bundler/gems/spree_globalize-f0ebc983c68c/app/controllers/spree/admin/translations_controller.rb:5:in `<class:TranslationsController>'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/bundler/gems/spree_globalize-f0ebc983c68c/app/controllers/spree/admin/translations_controller.rb:2:in `<module:Spree>'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/bundler/gems/spree_globalize-f0ebc983c68c/app/controllers/spree/admin/translations_controller.rb:1:in `<main>'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `const_get'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `block (2 levels) in eager_load'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:733:in `block in ls'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `foreach'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `ls'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:404:in `block in eager_load'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `synchronize'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `eager_load'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `each'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `eager_load_all'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/application/finisher.rb:122:in `block in <module:Finisher>'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `instance_exec'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `run'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
web_1        | App 257 output:     /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
web_1        | App 257 output:     /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
web_1        | App 257 output:     /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
web_1        | App 257 output:     /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
web_1        | App 257 output:     /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each'
web_1        | App 257 output:     /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `call'
web_1        | App 257 output:     /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
web_1        | App 257 output:     /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
web_1        | App 257 output:     /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:60:in `run_initializers'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/application.rb:363:in `initialize!'
web_1        | App 257 output:     /home/app/webapp/config/environment.rb:5:in `<top (required)>'
web_1        | App 257 output:     config.ru:3:in `require_relative'
web_1        | App 257 output:     config.ru:3:in `block in <main>'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
web_1        | App 257 output:     /home/app/webapp/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
web_1        | App 257 output:     config.ru:1:in `new'
web_1        | App 257 output:     config.ru:1:in `<main>'
web_1        | App 257 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
web_1        | App 257 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
web_1        | App 257 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
web_1        | App 257 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:382:in `run_block_and_record_step_progress'
web_1        | App 257 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
web_1        | App 257 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
web_1        | App 257 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
web_1        | [ E 2021-01-26 09:03:22.0365 42/Tn age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/app/webapp: The application encountered the following error: Missing helper file helpers/spree_i18n/locale_helper.rb (AbstractController::Helpers::MissingHelperError)
web_1        |   Error ID: 651b2e2d

```

**Comment by damianlegawiec** [comment]
Please upgrade Spree Globalize, this is fixed now :)
