### ISSUE TITLE
Sample Data Broken In Master

### ISSUE THREAD

**Issue by MatthewKennedy** [spree/spree#11356]
When running `bundle exec rake spree_sample:load`

```shell
Loaded Addresses samples
Loaded Zones samples
Loaded Payment Methods samples
Loaded Shipping Methods samples
Loaded Tax Categories samples
Loaded Tax Rates samples
Loaded Stores samples
Loaded Taxonomies samples
Loaded Option Types samples
Loaded Option Values samples
Loaded Taxons samples
Loaded Products samples
Loaded Promotions samples
Loaded Product Properties samples
Loaded Properties samples
Loaded Prototypes samples
Loaded Variants samples
rake aborted!
ActiveRecord::RecordNotFound: Couldn't find Spree::StockItem with [WHERE "spree_stock_items"."deleted_at" IS NULL AND "spree_stock_items"."variant_id" = $1 AND "spree_stock_items"."stock_location_id" = $2]
/Users/matt/Spark/spree/sample/db/samples/stock.rb:17:in `<main>'
/Users/matt/Spark/spree/sample/lib/spree/sample.rb:13:in `load_sample'
/Users/matt/Spark/spree/sample/lib/spree_sample.rb:26:in `load_samples'
/Users/matt/Spark/spree/sample/lib/tasks/sample.rake:20:in `block (2 levels) in <main>'
/Users/matt/.asdf/installs/ruby/3.0.1/bin/bundle:23:in `load'
/Users/matt/.asdf/installs/ruby/3.0.1/bin/bundle:23:in `<main>'
Tasks: TOP => spree_sample:load
(See full trace by running task with --trace)
```

**Comment by damianlegawiec** [comment]
These samples are generating random failures, generally, we would like to move away from it to a simple import a CSV data files, which will be implemented in spree core in future versions
