### ISSUE TITLE
Loading sample data errors out - docker-compose run web rake spree_sample:load

### ISSUE THREAD

**Issue by CaptainJeff** [spree/spree#11619]
I'm getting an error when I'm trying to run `docker-compose run web rake spree_sample:load`
## Context
I have docker set up and run the following commands

`./bin.setup`
`docker-compose run web rake spree_sample:load`

## Expected Behavior
I would expect the script to finish populating sample data 

## Actual Behavior
Errors out with the same error every time

```
Loaded Payments samples
Loaded Reimbursements samples
Loaded Return Authorization Reasons samples
Loaded Cms Standard Pages samples
Loaded Cms Feature Pages samples
Loaded Cms Homepages samples
rake aborted!
ActiveRecord::RecordNotFound: Couldn't find Spree::Taxon
/bundle/ruby/2.7.0/gems/activerecord-6.1.4.4/lib/active_record/core.rb:384:in `find_by!'
/bundle/ruby/2.7.0/gems/spree_sample-4.3.0/db/samples/cms_sections.rb:30:in `block in <main>'
/bundle/ruby/2.7.0/gems/spree_sample-4.3.0/db/samples/cms_sections.rb:10:in `each'
/bundle/ruby/2.7.0/gems/spree_sample-4.3.0/db/samples/cms_sections.rb:10:in `<main>'
/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/bundle/ruby/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/bundle/ruby/2.7.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require'
/bundle/ruby/2.7.0/gems/spree_sample-4.3.0/lib/spree/sample.rb:13:in `load_sample'
/bundle/ruby/2.7.0/gems/spree_sample-4.3.0/lib/spree_sample.rb:39:in `load_samples'
/bundle/ruby/2.7.0/gems/spree_sample-4.3.0/lib/tasks/sample.rake:20:in `block (2 levels) in <main>'
/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => spree_sample:load
(See full trace by running task with --trace)
````

## Steps to Reproduce
1. clone repo 
2. `./bin.setup`
3. `docker-compose run web rake spree_sample:load`

## Your Environment
I'm on a MacBook Pro (16-inch, 2019) running from `master` branch

**Comment by damianlegawiec** [comment]
this is now fixed
