### ISSUE TITLE
uninitialized constant Spree::StoreHelper (NameError)

### ISSUE THREAD

**Issue by rdinca** [spree/spree#11636]
I am trying to install spree in an existing devise application and I ran into the problem above ... I followed the steps mentioned here :  
https://dev-docs.spreecommerce.org/customization/authentication
and the module StoreHelper simply doesn't exist in the core gem ... I am using spree 4.4.0.

This is the full error message I am getting:
/home/radu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.4/lib/active_support/inflector/methods.rb:288:in `const_get': uninitialized constant Spree::StoreHelper (NameError)

**Comment by yanshiyason** [comment]
I am following the install instructions to add to an existing rails app, and when I try to run
```
bin/rails g spree:install --user_class=Spree::User
```

I am getting hit with `uninitialized constant Spree::AppConfiguration`

```
/Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/spree_core-4.4.0/lib/spree/core/engine.rb:23:in `block in <class:Engine>': uninitialized constant Spree::AppConfiguration (NameError)
...
	from /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.1/lib/rails/application.rb:372:in `initialize!'
	from /Users/me/my_app/config/environment.rb:7:in `<main>'
	...
	from bin/rails:6:in `<main>'
```

I am completely stumped because I can't even find any reference to `Spree::AppConfiguration` inside the library source code 🤔 .....

**Comment by joyboy67** [comment]
> I am following the install instructions to add to an existing rails app, and when I try to run
> 
> ```
> bin/rails g spree:install --user_class=Spree::User
> ```
> 
> I am getting hit with `uninitialized constant Spree::AppConfiguration`
> 
> ```
> /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/spree_core-4.4.0/lib/spree/core/engine.rb:23:in `block in <class:Engine>': uninitialized constant Spree::AppConfiguration (NameError)
> ...
> 	from /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.1/lib/rails/initializable.rb:60:in `run_initializers'
> 	from /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.1/lib/rails/application.rb:372:in `initialize!'
> 	from /Users/me/my_app/config/environment.rb:7:in `<main>'
> 	...
> 	from bin/rails:6:in `<main>'
> ```
> 
> I am completely stumped because I can't even find any reference to `Spree::AppConfiguration` inside the library source code 🤔 .....

Me too #11648

**Comment by x7** [comment]
@rdinca `Spree::StoreHelper` is part of the frontend which was extracted in 4.4.0 into a separate repo [spree_legacy_frontend](https://github.com/spree/spree_legacy_frontend)

@yanshiyason `Spree::AppConfiguration` is in models/spree https://github.com/spree/spree/blob/v4.4.0/core/app/models/spree/app_configuration.rb. 

For spree 4.4.0 use rails 6. You could try the main branch with rails 7.

**Comment by mices** [comment]
I'm getting this error with rails 7 spree 4.3.2 The only spree gem I added to my Gemfile is  spree 4.3.2 Running the installer didn't add any gems to my gemfile When I try to load the schema in production I get the error NameError: uninitialized constant Spree::AppConfiguration

**Comment by mices** [comment]
Which spree version uses rails < 6 cause I don't wanna get started with another rails 6 site that's gonna be hard to upgrade to rails 7
