### ISSUE TITLE
Failed to run `rails g spree:install`

### ISSUE THREAD

**Issue by joyboy67** [spree/spree#11648]
Hello, I followed this instructions : https://dev-docs.spreecommerce.org/advanced/existing_app_tutorial but I got this error when I do `rails g spree:install --user_class=Spree:User`

```
/usr/local/lib/ruby/gems/3.1.0/gems/spree_core-4.4.0/lib/spree/core/engine.rb:22:in `block in <class:Engine>': uninitialized constant Spree::AppConfiguration (NameError)

        app.config.spree = Environment.new(SpreeCalculators.new, Spree::AppConfiguration.new, Spree::AppDependencies.new)
                                                                      ^^^^^^^^^^^^^^^^^^
	from /usr/local/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/initializable.rb:32:in `run'
	from /usr/local/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /usr/local/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/initializable.rb:50:in `each'
	from /usr/local/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:415:in `call'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
	from /usr/local/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/application.rb:372:in `initialize!'
	from /home/cloud/mr/config/environment.rb:5:in `<main>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /usr/local/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /usr/local/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/application.rb:348:in `require_environment!'
	from /usr/local/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/command/actions.rb:28:in `require_environment!'
	from /usr/local/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	from /usr/local/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	from /usr/local/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/command/base.rb:87:in `perform'
	from /usr/local/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/command.rb:48:in `invoke'
	from /usr/local/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/commands.rb:18:in `<main>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:4:in `<main>'
```

## Your Environment

* Version used: Spree 4.4.0
* OS : OpenBSD 7.0 amd64
* Ruby version = 3.1 ; Rails version = 7 ; Database = mariadb/mysql
* Gemfile.lock:

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.0.2.2)
      actionpack (= 7.0.2.2)
      activesupport (= 7.0.2.2)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (7.0.2.2)
      actionpack (= 7.0.2.2)
      activejob (= 7.0.2.2)
      activerecord (= 7.0.2.2)
      activestorage (= 7.0.2.2)
      activesupport (= 7.0.2.2)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.0.2.2)
      actionpack (= 7.0.2.2)
      actionview (= 7.0.2.2)
      activejob (= 7.0.2.2)
      activesupport (= 7.0.2.2)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.0)
    actionpack (7.0.2.2)
      actionview (= 7.0.2.2)
      activesupport (= 7.0.2.2)
      rack (~> 2.0, >= 2.2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (7.0.2.2)
      actionpack (= 7.0.2.2)
      activerecord (= 7.0.2.2)
      activestorage (= 7.0.2.2)
      activesupport (= 7.0.2.2)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.0.2.2)
      activesupport (= 7.0.2.2)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    active_storage_validations (0.9.5)
      rails (>= 5.2.0)
    activejob (7.0.2.2)
      activesupport (= 7.0.2.2)
      globalid (>= 0.3.6)
    activemerchant (1.125.0)
      activesupport (>= 4.2)
      builder (>= 2.1.2, < 4.0.0)
      i18n (>= 0.6.9)
      nokogiri (~> 1.4)
    activemodel (7.0.2.2)
      activesupport (= 7.0.2.2)
    activerecord (7.0.2.2)
      activemodel (= 7.0.2.2)
      activesupport (= 7.0.2.2)
    activerecord-typedstore (1.4.0)
      activerecord (>= 5.2)
    activestorage (7.0.2.2)
      actionpack (= 7.0.2.2)
      activejob (= 7.0.2.2)
      activerecord (= 7.0.2.2)
      activesupport (= 7.0.2.2)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (7.0.2.2)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    acts_as_list (1.0.4)
      activerecord (>= 4.2)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    auto_strip_attributes (2.6.0)
      activerecord (>= 4.0)
    autoprefixer-rails (10.4.2.0)
      execjs (~> 2)
    awesome_nested_set (3.5.0)
      activerecord (>= 4.0.0, < 7.1)
    babel-source (5.8.35)
    babel-transpiler (0.7.0)
      babel-source (>= 4.0, < 6)
      execjs (~> 2.0)
    bcrypt (3.1.16)
    bindex (0.8.1)
    bootsnap (1.10.3)
      msgpack (~> 1.2)
    bootstrap (4.6.1)
      autoprefixer-rails (>= 9.1.0)
      popper_js (>= 1.14.3, < 2)
      sassc-rails (>= 2.0.0)
    builder (3.2.4)
    cancancan (3.3.0)
    capybara (3.36.0)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    carmen (1.1.3)
      activesupport (>= 3.0.0)
    childprocess (4.1.0)
    concurrent-ruby (1.1.9)
    crass (1.0.6)
    debug (1.4.0)
      irb (>= 1.3.6)
      reline (>= 0.2.7)
    devise (4.8.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    devise-encryptable (0.2.0)
      devise (>= 2.1.0)
    digest (3.1.0)
    doorkeeper (5.5.4)
      railties (>= 5)
    erubi (1.10.0)
    execjs (2.8.1)
    ffi (1.15.5)
    flatpickr (4.6.6.0)
    friendly_id (5.4.2)
      activerecord (>= 4.0.0)
    globalid (1.0.0)
      activesupport (>= 5.0)
    glyphicons (1.0.2)
    haml (5.2.2)
      temple (>= 0.8.0)
      tilt
    highline (2.0.3)
    hotwire-rails (0.1.3)
      rails (>= 6.0.0)
      stimulus-rails
      turbo-rails
    i18n (1.10.0)
      concurrent-ruby (~> 1.0)
    i18n_data (0.16.0)
      simple_po_parser (~> 1.1)
    image_processing (1.12.1)
      mini_magick (>= 4.9.5, < 5)
      ruby-vips (>= 2.0.17, < 3)
    importmap-rails (1.0.3)
      actionpack (>= 6.0.0)
      railties (>= 6.0.0)
    inline_svg (1.8.0)
      activesupport (>= 3.0)
      nokogiri (>= 1.6)
    io-console (0.5.11)
    io-wait (0.2.1)
    irb (1.4.1)
      reline (>= 0.3.0)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    jquery-rails (4.4.0)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (6.0.1)
      railties (>= 3.2.16)
    jsbundling-rails (1.0.2)
      railties (>= 6.0.0)
    jsonapi-serializer (2.2.0)
      activesupport (>= 4.2)
    kaminari (1.2.2)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.2.2)
      kaminari-activerecord (= 1.2.2)
      kaminari-core (= 1.2.2)
    kaminari-actionview (1.2.2)
      actionview
      kaminari-core (= 1.2.2)
    kaminari-activerecord (1.2.2)
      activerecord
      kaminari-core (= 1.2.2)
    kaminari-core (1.2.2)
    kaminari-i18n (0.5.0)
      kaminari
      rails
    loofah (2.14.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.2)
    matrix (0.4.2)
    method_source (1.0.0)
    mini_magick (4.11.0)
    mini_mime (1.1.2)
    mini_portile2 (2.5.3)
    minitest (5.15.0)
    monetize (1.12.0)
      money (~> 6.12)
    money (6.16.0)
      i18n (>= 0.6.4, <= 2)
    msgpack (1.4.5)
    mysql2 (0.5.3)
    net-imap (0.2.3)
      digest
      net-protocol
      strscan
    net-pop (0.1.1)
      digest
      net-protocol
      timeout
    net-protocol (0.1.2)
      io-wait
      timeout
    net-smtp (0.3.1)
      digest
      net-protocol
      timeout
    nio4r (2.5.8)
    nokogiri (1.11.5)
      mini_portile2 (~> 2.5.0)
      racc (~> 1.4)
    orm_adapter (0.5.0)
    paranoia (2.5.2)
      activerecord (>= 5.1, < 7.1)
    popper_js (1.16.0)
    public_suffix (4.0.6)
    puma (5.6.2)
      nio4r (~> 2.0)
    rabl (0.15.0)
      activesupport (>= 2.3.14)
    racc (1.6.0)
    rack (2.2.3)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (7.0.2.2)
      actioncable (= 7.0.2.2)
      actionmailbox (= 7.0.2.2)
      actionmailer (= 7.0.2.2)
      actionpack (= 7.0.2.2)
      actiontext (= 7.0.2.2)
      actionview (= 7.0.2.2)
      activejob (= 7.0.2.2)
      activemodel (= 7.0.2.2)
      activerecord (= 7.0.2.2)
      activestorage (= 7.0.2.2)
      activesupport (= 7.0.2.2)
      bundler (>= 1.15.0)
      railties (= 7.0.2.2)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.4.2)
      loofah (~> 2.3)
    rails-i18n (7.0.2)
      i18n (>= 0.7, < 2)
      railties (>= 6.0.0, < 8)
    railties (7.0.2.2)
      actionpack (= 7.0.2.2)
      activesupport (= 7.0.2.2)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
      zeitwerk (~> 2.5)
    rake (13.0.6)
    ransack (2.5.0)
      activerecord (>= 5.2.4)
      activesupport (>= 5.2.4)
      i18n
    redcarpet (3.5.1)
    regexp_parser (2.2.1)
    reline (0.3.1)
      io-console (~> 0.5)
    responders (3.0.1)
      actionpack (>= 5.0)
      railties (>= 5.0)
    rexml (3.2.5)
    ruby-vips (2.1.4)
      ffi (~> 1.12)
    rubyzip (2.3.2)
    sass-rails (6.0.0)
      sassc-rails (~> 2.1, >= 2.1.1)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    select2-rails (4.0.13)
    selenium-webdriver (4.1.0)
      childprocess (>= 0.5, < 5.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2)
    simple_po_parser (1.1.5)
    spree (4.4.0)
      spree_api (= 4.4.0)
      spree_cli (= 4.4.0)
      spree_core (= 4.4.0)
    spree_api (4.4.0)
      bcrypt (~> 3.1)
      doorkeeper (~> 5.3)
      jsonapi-serializer (~> 2.1)
      rabl (~> 0.14, >= 0.14.2)
      responders
      spree_core (= 4.4.0)
    spree_auth_devise (4.4.2)
      devise (~> 4.7)
      devise-encryptable (= 0.2.0)
      spree_core (>= 4.3.0.rc1)
      spree_extension
    spree_backend (4.4.0)
      babel-transpiler (~> 0.7)
      bootstrap (~> 4.0)
      flatpickr (~> 4.6)
      glyphicons (~> 1.0)
      hotwire-rails
      inline_svg (~> 1.5)
      jquery-rails (~> 4.3)
      jquery-ui-rails (~> 6.0)
      jsbundling-rails
      responders
      sass-rails (>= 5)
      select2-rails (~> 4.0)
      spree (>= 4.4.0.rc1)
      sprockets (~> 4.0)
      tinymce-rails
    spree_cli (4.4.0)
      thor (~> 1.0)
    spree_core (4.4.0)
      actionpack (>= 5.2)
      actionview (>= 5.2)
      active_storage_validations (~> 0.9, <= 0.9.5)
      activejob (>= 5.2)
      activemerchant (~> 1.67)
      activemodel (>= 5.2)
      activerecord (>= 5.2)
      activerecord-typedstore
      activestorage (>= 5.2)
      activesupport (>= 5.2)
      acts_as_list (>= 0.8)
      auto_strip_attributes (~> 2.6)
      awesome_nested_set (~> 3.3, >= 3.3.1)
      cancancan (~> 3.2)
      carmen (>= 1.0)
      friendly_id (~> 5.2, >= 5.2.1)
      highline (~> 2.0)
      image_processing (~> 1.2)
      kaminari (~> 1.2)
      mini_magick (~> 4.9, >= 4.9.4)
      monetize (~> 1.9)
      money (~> 6.13)
      paranoia (~> 2.4)
      railties (>= 5.2)
      ransack (~> 2.3)
      rexml
      state_machines-activemodel (~> 0.7)
      state_machines-activerecord (~> 0.6)
      stringex
      validates_zipcode
    spree_emails (4.4.0)
      actionmailer
      spree_core (>= 4.4.0)
      sprockets (>= 4.0)
    spree_extension (0.0.9)
      activerecord (>= 4.2)
      spree_core
    spree_gateway (3.9.4)
      spree_core (>= 3.7.0)
      spree_extension
    spree_i18n (5.0.1)
      i18n_data
      kaminari-i18n
      rails-i18n
      spree_core (>= 4.2.0.rc3, < 5.0)
      spree_extension
    sprockets (4.0.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    state_machines (0.5.0)
    state_machines-activemodel (0.8.0)
      activemodel (>= 5.1)
      state_machines (>= 0.5.0)
    state_machines-activerecord (0.8.0)
      activerecord (>= 5.1)
      state_machines-activemodel (>= 0.8.0)
    stimulus-rails (1.0.4)
      railties (>= 6.0.0)
    stringex (2.8.5)
    strscan (3.0.1)
    temple (0.8.2)
    thor (1.2.1)
    tilt (2.0.10)
    timeout (0.2.0)
    tinymce-rails (5.10.3)
      railties (>= 3.1.1)
    turbo-rails (1.0.1)
      actionpack (>= 6.0.0)
      railties (>= 6.0.0)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    validates_zipcode (0.5.0)
      activemodel (>= 4.2.0)
    warden (1.2.9)
      rack (>= 2.0.9)
    web-console (4.2.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (5.0.0)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.5.4)

PLATFORMS
  x86_64-openbsd-7.0

DEPENDENCIES
  bcrypt (~> 3.1.7)
  bootsnap
  capybara
  debug
  haml
  importmap-rails
  jbuilder
  mysql2 (~> 0.5)
  nokogiri (= 1.11.5)
  puma (~> 5.0)
  rails (~> 7.0.2, >= 7.0.2.2)
  redcarpet
  sassc-rails
  selenium-webdriver
  spree (~> 4.4)
  spree_auth_devise (~> 4.4)
  spree_backend (~> 4.4)
  spree_emails (~> 4.4)
  spree_gateway (~> 3.9)
  spree_i18n (~> 5.0)
  sprockets-rails
  stimulus-rails
  turbo-rails
  tzinfo-data
  web-console
  webdrivers

RUBY VERSION
   ruby 3.1.1p18

BUNDLED WITH
   2.3.7
```

**Comment by parvesh22** [comment]
I am facing same issue

**Comment by x7** [comment]
Spree 4.4.0 doesn't work with rails 7 new autoloading configuration. It is fixed in the main branch.

**Comment by ashishkpaul** [comment]
After running **rails g spree:install**
I am getting the error
[WARN] FriendlyId::Slug is calling acts_as_paranoid more than once!
**rake aborted!**
ArgumentError: ActiveRecord::ConnectionAdapters::SQLite3Adapter does not support skipping duplicates
Please help me

**Comment by ashishkpaul** [comment]
Partial Problem is resolved by installing
gem install sqlite3

Now getting error
ashish@ecommerce:~/code/backend/spreecom$ bin/rake spree_sample:load
[WARN] FriendlyId::Slug is calling acts_as_paranoid more than once!
[WARN] FriendlyId::Slug is calling acts_as_paranoid more than once!
[WARN] FriendlyId::Slug is calling acts_as_paranoid more than once!
Running via Spring preloader in process 5247
rake aborted!
Don't know how to build task 'spree_sample:load' (See the list of available tasks with `rake --tasks`)
/home/ashish/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/home/ashish/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/home/ashish/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/command_wrapper.rb:40:in `call'
/home/ashish/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/application.rb:220:in `block in serve'
/home/ashish/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/application.rb:180:in `fork'
/home/ashish/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/application.rb:180:in `serve'
/home/ashish/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
/home/ashish/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
/home/ashish/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
/home/ashish/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
-e:1:in `<main>'
(See full trace by running task with --trace)

**Comment by ashishkpaul** [comment]
on a fresh server home page returning to default ruby rails version.
I followed the installation instruction at https://dev-docs.spreecommerce.org/advanced/existing_app_tutorial

ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]

 rails -v
Found no changes, using resolution from the lockfile
Rails 6.0.4.7

**Comment by youngjaw12** [comment]
i have same problem using rails 7 and ruby version 3.1.0.

**Comment by damianlegawiec** [comment]
> i have same problem using rails 7 and ruby version 3.1.0.

Spree currently works with Rails 5.2-6.1, Rails 7 support will be available later in Q2

**Comment by dylanfisher** [comment]
This is also happening in Rails 6 / Spree 4.4 when using custom authentication. 

This part of the guide says to include the `spree/store` helper in `ApplicationController` https://dev-docs.spreecommerce.org/customization/authentication#authentication-helpers, but that helper was moved to a legacy frontend app, as mentioned in this issue https://github.com/spree/spree_legacy_frontend/blob/main/app/helpers/spree/store_helper.rb. 

Manually copying `Spree::StoreHelper` from the legacy app should get you around this issue.

**Comment by diegomichel** [comment]
> 

Hey @damianlegawiec, is Rails 7 support already available 🙏 ?

**Comment by rafalcymerys** [comment]
@diegomichel @joyboy67 this should work fine with Spree 4.5 that's now available
