### ISSUE TITLE
 uninitialized constant Spree::BackendConfiguration (NameError)

### ISSUE THREAD

**Issue by younthu** [spree/spree#11718]
In rails 7, run  rails g spree:install --user_class=Spree::User, get error below
~~~

/Users/andrewy/.rvm/gems/ruby-3.1.1/gems/spree_backend-4.4.1/lib/spree/backend/engine.rb:7:in `block in <class:Engine>': uninitialized constant Spree::BackendConfiguration (NameError)

        Spree::Backend::Config = Spree::BackendConfiguration.new
                                      ^^^^^^^^^^^^^^^^^^^^^^
        from /Users/andrewy/.rvm/gems/ruby-3.1.1/gems/railties-7.0.3/lib/rails/initializable.rb:32:in `instance_exec'
        from /Users/andrewy/.rvm/gems/ruby-3.1.1/gems/railties-7.0.3/lib/rails/initializable.rb:32:in `run'
        from /Users/andrewy/.rvm/gems/ruby-3.1.1/gems/railties-7.0.3/lib/rails/initializable.rb:61:in `block in run_initializers'

~~~

## Context

Ruby 3.1.1
Rails 7.0
Spree master branch

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by katasonov-dev** [comment]
have the same problem with existing rails 7 app. Tested with fresh one and there is no such problem. Will take a look and compare where can be the difference
