### ISSUE TITLE
`spree:install` fails when `spree_auth_devise`  is not installed

### ISSUE THREAD

**Issue by abdellani** [spree/spree#11720]
## Context
I'm trying to integrate spree into a new rails (6.1) application.
## Expected Behavior
The following command should run without problems.
```bash
bin/rails g spree:install --user_class=Spree::User
```
## Actual Behavior

The command is throwing with the following error 
```bash
 rails g spree:install --user_class=Spree::User
[Spree WARNING] Missing migrations.
[Spree WARNING] add_deleted_at_to_spree_stores from spree is missing.
[Spree WARNING] add_metadata_to_spree_line_items from spree is missing.
[Spree WARNING] add_metadata_to_spree_multiple_tables from spree is missing.
[Spree WARNING] add_metadata_to_spree_orders from spree is missing.
[Spree WARNING] add_metadata_to_spree_payments from spree is missing.
[Spree WARNING] add_metadata_to_spree_products from spree is missing.
[Spree WARNING] add_metadata_to_spree_shipments from spree is missing.
[Spree WARNING] add_metadata_to_spree_stock_transfers from spree is missing.
[Spree WARNING] add_metadata_to_spree_taxons_and_taxonomies from spree is missing.
[Spree WARNING] add_metadata_to_spree_variants from spree is missing.
[Spree WARNING] add_settings_to_spree_stores from spree is missing.
[Spree WARNING] add_unique_stock_item_stock_location_variant_deleted_at_index from spree is missing.
[Spree WARNING] create_spree_digital_links from spree is missing.
[Spree WARNING] create_spree_digitals from spree is missing.
[Spree WARNING] create_spree_wished_products from spree is missing.
[Spree WARNING] create_spree_wishlists from spree is missing.
[Spree WARNING] create_stock_item_stock_location_id_variant_id_coalesce_deleted_at_unique_index from spree is missing.
[Spree WARNING] rename_column_access_hash_to_token from spree is missing.
[Spree WARNING] rename_secret_to_token_on_spree_digital_links from spree is missing.
[Spree WARNING] rename_spree_wished_products_to_spree_wished_items from spree is missing.
[Spree WARNING] spree_four_three from spree is missing.
[Spree WARNING] Run `bundle exec rake railties:install:migrations` to get them.

[Spree_api WARNING] Missing migrations.
[Spree_api WARNING] add_api_key_to_spree_users from spree_api is missing.
[Spree_api WARNING] add_index_to_user_spree_api_key from spree_api is missing.
[Spree_api WARNING] change_integer_id_columns_type from spree_api is missing.
[Spree_api WARNING] create_doorkeeper_tables from spree_api is missing.
[Spree_api WARNING] create_spree_webhooks_events from spree_api is missing.
[Spree_api WARNING] create_spree_webhooks_tables from spree_api is missing.
[Spree_api WARNING] enable_polymorphic_resource_owner from spree_api is missing.
[Spree_api WARNING] rename_api_key_to_spree_api_key from spree_api is missing.
[Spree_api WARNING] resize_api_key_field from spree_api is missing.
[Spree_api WARNING] Run `bundle exec rake railties:install:migrations` to get them.

[WARN] FriendlyId::Slug is calling acts_as_paranoid more than once!
/home/user/.rvm/gems/ruby-3.0.2/gems/spree_core-4.4.0/app/models/spree/address.rb:34:in `<class:Address>': undefined method `name' for nil:NilClass (NoMethodError)
        from /home/user/.rvm/gems/ruby-3.0.2/gems/spree_core-4.4.0/app/models/spree/address.rb:2:in `<module:Spree>'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/spree_core-4.4.0/app/models/spree/address.rb:1:in `<main>'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:27:in `require'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/spree_api-4.4.0/lib/spree/api/engine.rb:20:in `activate'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `instance_exec'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `block in make_lambda'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `catch'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `block in default_terminator'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:199:in `block in halting'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `block in invoke_before'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `each'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `invoke_before'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:105:in `run_callbacks'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.6/lib/active_support/reloader.rb:88:in `prepare!'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/railties-6.1.6/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `run'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/railties-6.1.6/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/share/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
        from /usr/share/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/share/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/share/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/share/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each'
        from /usr/share/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `call'
        from /usr/share/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/share/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
        from /usr/share/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/railties-6.1.6/lib/rails/initializable.rb:60:in `run_initializers'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/railties-6.1.6/lib/rails/application.rb:391:in `initialize!'
        from /home/user/opensource/spree-test-6.1/config/environment.rb:5:in `<main>'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `block in require'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/spring-4.0.0/lib/spring/application.rb:108:in `preload'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/spring-4.0.0/lib/spring/application.rb:162:in `serve'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/spring-4.0.0/lib/spring/application.rb:144:in `block in run'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/spring-4.0.0/lib/spring/application.rb:138:in `loop'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/spring-4.0.0/lib/spring/application.rb:138:in `run'
        from /home/user/.rvm/gems/ruby-3.0.2/gems/spring-4.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
        from <internal:/usr/share/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/share/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from -e:1:in `<main>'
```
## Possible Fix

 According to the [documentation](https://dev-docs.spreecommerce.org/advanced/existing_app_tutorial), the gem `spree_auth_devise` is optional. The generator didn't run successfully until I added that gem.

## Steps to Reproduce

1. generate new rails application 6.1
2.  Add the two gems only: `spree` & `spree_backend`
3. run `bin/rails g spree:install --user_class=Spree::User`

## Your Environment

* Version used: 4.4
* Gemfile and Gemfile.lock as text in a Gist: (you'll need to remove `spree_auth_devise`)
https://gist.github.com/abdellani/4752dc09a41818a74f6618a582ca2d1f
https://gist.github.com/abdellani/1599d16e9e0a2498dc6eca9692600cfd

**Comment by damianlegawiec** [comment]
If you're not using spree auth devise you need to follow this guide - https://dev-docs.spreecommerce.org/customization/authentication

**Comment by dan-jensen** [comment]
Nice, solved this problem by installing [devise](https://rubygems.org/gems/devise) first, then installing [spree](https://rubygems.org/gems/spree) along with [spree_auth_devise](https://rubygems.org/gems/spree_auth_devise). I hadn't realized that Spree depends on Devise by default.
