### ISSUE TITLE
API Internal Server Error GET /api/v2/storefront/taxons

### ISSUE THREAD

**Issue by mlf20** [spree/spree#11747]
The Spree v4.4.0 API endpoint  '/api/v2/storefront/taxons' returns a 500 error when a user requests the endpoint with a malformed request in the query.

## Context
An authenticated user, when trying to query the endpoint  '/api/v2/storefront/taxons' results in an internal server error due to an unpermitted parameter in an SQL query when using a malformed request.

```filter%5Bparent_permalink%5D=clothes&filter%5Broots%5D=False```
 
## Expected Behavior
Returns 400 response as the request body is malformed.

## Actual Behavior
Returns 500 response code from an internal server error.

## Steps to Reproduce
1. Install demo version of spree as a docker container [Link](https://github.com/spree/spree_starter).
2. Submit a GET request to the endpoint with the malformed request:
```
curl -H 'Content-Type: application/json' -X PATCH http://localhost:4000/api/v2/storefront/taxons?filter%5Bparent_permalink%5D=clothes&filter%5Broots%5D=False
```

## Your Environment

* Version used: Spree 4.4.0, rails 6.1.6
* Gemfile and Gemfile.lock as text in a Gist:
	*  https://gist.github.com/mlf20/309b0d077089d8ec04812937941ba903
* Any relevant stack traces ("Full trace" preferred):

 ```
Started GET "/api/v2/storefront/taxons?filter%5Bids%5D=1&filter%5Bname%5D=rails&filter%5Bparent_id%5D=1&filter%5Bparent_permalink%5D=clothes&filter%5Btaxonomy_id%5D=1&filter%5Broots%5D=False&page=1&per_page=25&include=parent,taxonomy,children,image,products" for 172.20.0.1 at 2022-08-11 11:25:30 +0000
Cannot render console from 172.20.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by Spree::Api::V2::Storefront::TaxonsController#index as JSON
  Parameters: {"filter"=>{"ids"=>"1", "name"=>"rails", "parent_id"=>"1", "parent_permalink"=>"clothes", "taxonomy_id"=>"1", "roots"=>"False"}, "page"=>"1", "per_page"=>"25", "include"=>"parent,taxonomy,children,image,products", "taxon"=>{}}
  Spree::Store Load (6.8ms)  SELECT "spree_stores".* FROM "spree_stores" WHERE "spree_stores"."deleted_at" IS NULL AND (url like '%localhost%') ORDER BY "spree_stores"."created_at" ASC LIMIT $1  [["LIMIT", 1]]
  Spree::Store Load (0.9ms)  SELECT "spree_stores".* FROM "spree_stores" WHERE "spree_stores"."deleted_at" IS NULL AND "spree_stores"."default" = $1 ORDER BY "spree_stores"."created_at" ASC LIMIT $2  [["default", true], ["LIMIT", 1]]
  Spree::OauthAccessToken Load (1.4ms)  SELECT "spree_oauth_access_tokens".* FROM "spree_oauth_access_tokens" WHERE "spree_oauth_access_tokens"."token" = $1 LIMIT $2  [["token", "12ad423fa3dc450e2ed47b6bd63d9504e8768533c247bd8b9de26143429806c5"], ["LIMIT", 1]]
  Spree::User Load (3.7ms)  SELECT "spree_users".* FROM "spree_users" WHERE "spree_users"."deleted_at" IS NULL AND "spree_users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Spree::Role Exists? (2.1ms)  SELECT 1 AS one FROM "spree_roles" INNER JOIN "spree_role_users" ON "spree_roles"."id" = "spree_role_users"."role_id" WHERE "spree_role_users"."user_id" = $1 AND "spree_roles"."name" = $2 LIMIT $3  [["user_id", 1], ["name", "admin"], ["LIMIT", 1]]
  Spree::Preference Load (0.8ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = $1 LIMIT $2  [["key", "spree/api_configuration/api_v2_per_page_limit"], ["LIMIT", 1]]
   (2.9ms)  SELECT "spree_taxons"."id", "spree_taxons"."updated_at" FROM "spree_taxons" INNER JOIN "spree_taxonomies" ON "spree_taxonomies"."id" = "spree_taxons"."taxonomy_id" INNER JOIN "spree_taxons" "parent" ON "parent"."id" = "spree_taxons"."parent_id" WHERE "spree_taxonomies"."store_id" = $1 AND "spree_taxons"."id" = $2 AND "spree_taxons"."parent_id" = $3 AND "parent"."permalink" = $4 AND "spree_taxons"."taxonomy_id" = $5 AND "spree_taxons"."parent_id" IS NULL AND "spree_taxons"."name" ILIKE '%rails%' LIMIT $6 OFFSET $7  [["store_id", 1], ["id", 1], ["parent_id", 1], ["permalink", "clothes"], ["taxonomy_id", 1], ["LIMIT", 25], ["OFFSET", 0]]
  Spree::Zone Load (1.0ms)  SELECT "spree_zones".* FROM "spree_zones" WHERE "spree_zones"."default_tax" = $1 LIMIT $2  [["default_tax", true], ["LIMIT", 1]]
  Spree::Preference Load (1.5ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = $1 LIMIT $2  [["key", "spree/api_configuration/api_v2_collection_cache_namespace"], ["LIMIT", 1]]
  Spree::Preference Load (2.4ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = $1 LIMIT $2  [["key", "spree/api_configuration/api_v2_collection_cache_ttl"], ["LIMIT", 1]]
   (3.6ms)  SELECT COUNT(*) FROM "spree_taxons" INNER JOIN "spree_taxonomies" ON "spree_taxonomies"."id" = "spree_taxons"."taxonomy_id" INNER JOIN "spree_taxons" "parent" ON "parent"."id" = "spree_taxons"."parent_id" WHERE "spree_taxonomies"."store_id" = $1 AND "spree_taxons"."id" = $2 AND "spree_taxons"."parent_id" = $3 AND "parent"."permalink" = $4 AND "spree_taxons"."taxonomy_id" = $5 AND "spree_taxons"."parent_id" IS NULL AND "spree_taxons"."name" ILIKE '%rails%'  [["store_id", 1], ["id", 1], ["parent_id", 1], ["permalink", "clothes"], ["taxonomy_id", 1]]
Unpermitted parameter: :taxon
Unpermitted parameter: :taxon
Unpermitted parameter: :taxon
Unpermitted parameter: :taxon
   (2.4ms)  SELECT COUNT(*) FROM (SELECT 1 AS one FROM "spree_taxons" INNER JOIN "spree_taxonomies" ON "spree_taxonomies"."id" = "spree_taxons"."taxonomy_id" INNER JOIN "spree_taxons" "parent" ON "parent"."id" = "spree_taxons"."parent_id" WHERE "spree_taxonomies"."store_id" = $1 AND "spree_taxons"."id" = $2 AND "spree_taxons"."parent_id" = $3 AND "parent"."permalink" = $4 AND "spree_taxons"."taxonomy_id" = $5 AND "spree_taxons"."parent_id" IS NULL AND "spree_taxons"."name" ILIKE '%rails%' ORDER BY lft LIMIT $6 OFFSET $7) subquery_for_count  [["store_id", 1], ["id", 1], ["parent_id", 1], ["permalink", "clothes"], ["taxonomy_id", 1], ["LIMIT", 25], ["OFFSET", 0]]
Completed 500 Internal Server Error in 303ms (ActiveRecord: 68.1ms | Allocations: 37713)


PG::AmbiguousColumn: ERROR:  column reference "lft" is ambiguous
LINE 1: ...ND "spree_taxons"."name" ILIKE '%rails%' ORDER BY lft LIMIT ...
                                                             ^
 excluded from capture: DSN not set
  
ActiveRecord::StatementInvalid (PG::AmbiguousColumn: ERROR:  column reference "lft" is ambiguous
LINE 1: ...ND "spree_taxons"."name" ILIKE '%rails%' ORDER BY lft LIMIT ...
                                                             ^
):
  
rack-mini-profiler (3.0.0) lib/patches/db/pg.rb:72:in `exec_params'
rack-mini-profiler (3.0.0) lib/patches/db/pg.rb:72:in `exec_params'
activerecord (6.1.6) lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `block (2 levels) in exec_no_cache'
activesupport (6.1.6) lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
activesupport (6.1.6) lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
activesupport (6.1.6) lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
activerecord (6.1.6) lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `block in exec_no_cache'
activerecord (6.1.6) lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
activerecord (6.1.6) lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
activesupport (6.1.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activerecord (6.1.6) lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
activerecord (6.1.6) lib/active_record/connection_adapters/postgresql_adapter.rb:670:in `exec_no_cache'
activerecord (6.1.6) lib/active_record/connection_adapters/postgresql_adapter.rb:649:in `execute_and_clear'
activerecord (6.1.6) lib/active_record/connection_adapters/postgresql/database_statements.rb:55:in `exec_query'
activerecord (6.1.6) lib/active_record/connection_adapters/abstract/database_statements.rb:532:in `select'
activerecord (6.1.6) lib/active_record/connection_adapters/abstract/database_statements.rb:69:in `select_all'
activerecord (6.1.6) lib/active_record/connection_adapters/abstract/query_cache.rb:101:in `block in select_all'
activerecord (6.1.6) lib/active_record/connection_adapters/abstract/query_cache.rb:118:in `block in cache_sql'
activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
activerecord (6.1.6) lib/active_record/connection_adapters/abstract/query_cache.rb:109:in `cache_sql'
activerecord (6.1.6) lib/active_record/connection_adapters/abstract/query_cache.rb:101:in `select_all'
activerecord (6.1.6) lib/active_record/relation/calculations.rb:308:in `block in execute_simple_calculation'
activerecord (6.1.6) lib/active_record/relation.rb:861:in `skip_query_cache_if_necessary'
activerecord (6.1.6) lib/active_record/relation/calculations.rb:308:in `execute_simple_calculation'
activerecord (6.1.6) lib/active_record/relation/calculations.rb:269:in `perform_calculation'
activerecord (6.1.6) lib/active_record/relation/calculations.rb:144:in `calculate'
activerecord (6.1.6) lib/active_record/relation/calculations.rb:51:in `count'
activerecord (6.1.6) lib/active_record/relation.rb:260:in `size'
spree_api (4.4.0) app/helpers/spree/api/v2/collection_options_helpers.rb:17:in `collection_meta'
spree_api (4.4.0) app/helpers/spree/api/v2/collection_options_helpers.rb:38:in `collection_options'
spree_api (4.4.0) app/controllers/spree/api/v2/base_controller.rb:31:in `serialize_collection'
spree_api (4.4.0) app/controllers/spree/api/v2/resource_controller.rb:11:in `block (2 levels) in index'
activesupport (6.1.6) lib/active_support/cache.rb:752:in `block in save_block_result_to_cache'
activesupport (6.1.6) lib/active_support/cache.rb:726:in `block in instrument'
activesupport (6.1.6) lib/active_support/notifications.rb:205:in `instrument'
activesupport (6.1.6) lib/active_support/cache.rb:726:in `instrument'
activesupport (6.1.6) lib/active_support/cache.rb:751:in `save_block_result_to_cache'
activesupport (6.1.6) lib/active_support/cache.rb:343:in `fetch'
spree_api (4.4.0) app/controllers/spree/api/v2/resource_controller.rb:10:in `block in index'
spree_api (4.4.0) app/controllers/spree/api/v2/base_controller.rb:53:in `render_serialized_payload'
spree_api (4.4.0) app/controllers/spree/api/v2/resource_controller.rb:9:in `index'
actionpack (6.1.6) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.1.6) lib/abstract_controller/base.rb:228:in `process_action'
actionpack (6.1.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.1.6) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.1.6) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
sentry-raven (3.1.2) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
activesupport (6.1.6) lib/active_support/callbacks.rb:126:in `instance_exec'
activesupport (6.1.6) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
activesupport (6.1.6) lib/active_support/callbacks.rb:137:in `run_callbacks'
actionpack (6.1.6) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.1.6) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.1.6) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (6.1.6) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.1.6) lib/active_support/notifications.rb:203:in `instrument'
actionpack (6.1.6) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
actionpack (6.1.6) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
activerecord (6.1.6) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.1.6) lib/abstract_controller/base.rb:165:in `process'
actionview (6.1.6) lib/action_view/rendering.rb:39:in `process'
actionpack (6.1.6) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.1.6) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.1.6) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.1.6) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (6.1.6) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.1.6) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.1.6) lib/action_dispatch/routing/route_set.rb:842:in `call'
railties (6.1.6) lib/rails/engine.rb:539:in `call'
railties (6.1.6) lib/rails/railtie.rb:207:in `public_send'
railties (6.1.6) lib/rails/railtie.rb:207:in `method_missing'
actionpack (6.1.6) lib/action_dispatch/routing/mapper.rb:20:in `block in <class:Constraints>'
actionpack (6.1.6) lib/action_dispatch/routing/mapper.rb:49:in `serve'
actionpack (6.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (6.1.6) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.1.6) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.1.6) lib/action_dispatch/routing/route_set.rb:842:in `call'
scout_apm (5.1.1) lib/scout_apm/instant/middleware.rb:55:in `call'
scout_apm (5.1.1) lib/scout_apm/middleware.rb:20:in `call'
bullet (7.0.2) lib/bullet/rack.rb:15:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.3.1) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3.1) lib/rack/etag.rb:27:in `call'
rack (2.2.3.1) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3.1) lib/rack/head.rb:12:in `call'
actionpack (6.1.6) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
actionpack (6.1.6) lib/action_dispatch/http/content_security_policy.rb:19:in `call'
rack (2.2.3.1) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3.1) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.1.6) lib/action_dispatch/middleware/cookies.rb:689:in `call'
activerecord (6.1.6) lib/active_record/migration.rb:601:in `call'
actionpack (6.1.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.6) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:19:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.1.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.6) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.6) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.6) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.6) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.1.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.6) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3.1) lib/rack/method_override.rb:24:in `call'
rack (2.2.3.1) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.6) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3.1) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.6) lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
sentry-raven (3.1.2) lib/raven/integrations/rack.rb:51:in `call'
rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
rack-mini-profiler (3.0.0) lib/mini_profiler/profiler.rb:393:in `call'
railties (6.1.6) lib/rails/engine.rb:539:in `call'
puma (5.6.4) lib/puma/configuration.rb:252:in `call'
puma (5.6.4) lib/puma/request.rb:77:in `block in handle_request'
puma (5.6.4) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.6.4) lib/puma/request.rb:76:in `handle_request'
puma (5.6.4) lib/puma/server.rb:441:in `process_client'
puma (5.6.4) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by narendran-kannan** [comment]
Can we add a validator (delegator) to validate params and send an appropriate response?
