### ISSUE TITLE
Error loading Doorkeeper v5.6.0

### ISSUE THREAD

**Issue by zavan** [spree/spree#11770]
I tried updating Doorkeeper to v5.6.0 (released a week ago), but it seems that [a change to their autoloading code](https://github.com/doorkeeper-gem/doorkeeper/pull/1551) breaks [this initializer](https://github.com/spree/spree/blob/v4.2.6/api/config/initializers/doorkeeper.rb):

```
/usr/local/lib/ruby/gems/3.1.0/gems/spree_api-4.2.6/config/initializers/doorkeeper.rb:31:in `<main>': uninitialized constant Doorkeeper::AccessGrant
Did you mean?  Doorkeeper::AccessGrantMixin (NameError)
	from /usr/local/lib/ruby/gems/3.1.0/gems/railties-6.1.7/lib/rails/engine.rb:681:in `block in load_config_initializer'
```

Downgrading to v5.5.4 works.

## Your Environment

* Version used: Spree v4.2.6 and Doorkeeper v5.6.0. I have not tried Spree v4.3 and up.

**Comment by rafalcymerys** [comment]
Hi @zavan - thank you for creating this one! How is the PR that you assigned to it, related to this issue? Was the error caused by lack of permitted classes in the initializer?

**Comment by zavan** [comment]
@rafalcymerys Hey! Nope, it's my [second comment](https://github.com/spree/spree/pull/11771#issuecomment-1247968698) on that references this PR actually, the CI there is failing due to this issue here.

**Comment by HustMaroon** [comment]
since this [5.5.0 release](https://github.com/doorkeeper-gem/doorkeeper/releases/tag/v5.5.0.rc1), Doorkeeper has required client authentication which current version of Spree_api doesn't satisfy anymore, so I think you would want to change this version's gemspec to `(~> 5.2, >= 5.2.1, <5.5.0)`

**Comment by nbulaj** [comment]
Hey @zavan . Could you please try with 

```ruby
# Gemfile

gem "doorkeeper", github: "doorkeeper-gem/doorkeeper", branch: "fixes/lazy-load-associations"
```

And report if issue still present?
