### ISSUE TITLE
uninitialized constant Spree::Preference (NameError)

### ISSUE THREAD

**Issue by dylanfisher** [spree/spree#11810]
## Context
Using Rails 7 and Spree 4.5.0 and trying to configure preferences causes app to crash on startup.

This same issue applies to other areas an ActiveModel record is referenced before the app is initialized, for example in `spree_auth_devise`. A potential fix for that is here https://github.com/dylanfisher/spree_auth_devise/commit/4d6a70389a3b8f7021341df36cfa3f85db3adc37. 

## Expected Behavior
Spree preference should be loaded on boot.

## Actual Behavior
Error on boot:
`/Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/spree_core-4.5.0/lib/spree/core/preferences/store.rb:96:in 'should_persist?': uninitialized constant Spree::Preference (NameError)`

## Possible Fix
Wrap the calls to Spree config that call the `Spree::Preference` model in a `to_prepare` block. 

```
ActiveSupport::Reloader.to_prepare do
  Spree.config do |config|
    config.tax_using_ship_address = true
  end
end
```

## Steps to Reproduce
1. Install new Rails 7 app `rails new spree_test --database=postgresql --skip-yarn --skip-active-storage --skip-action-cable --skip-coffee --skip-test --skip-javascript`
2. Add Spree 4.5.0 to Gemfile `gem "spree", "~> 4.5"`
3. Create a Spree initializer in `config/initializers/spree.rb` and add a config preference, like this:
    ```
    Spree.config do |config|
      config.tax_using_ship_address = true
    end
    ```
5. Start rails server `bin/rails server`

## Your Environment
* Version used: `Spree 4.5.0`
* Rails version: `Rails ~> 7.0.3`
* Any relevant stack traces ("Full trace" preferred):

```
/Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/spree_core-4.5.0/lib/spree/core/preferences/store.rb:96:in `should_persist?': uninitialized constant Spree::Preference (NameError)

      @persistence && Spree::Preference.table_exists?
                           ^^^^^^^^^^^^
Did you mean?  Spree::Preferences
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/spree_core-4.5.0/lib/spree/core/preferences/store.rb:81:in `persist'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/spree_core-4.5.0/lib/spree/core/preferences/store.rb:28:in `set'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/spree_core-4.5.0/lib/spree/core/preferences/scoped_store.rb:17:in `[]='
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/spree_core-4.5.0/lib/spree/core/preferences/preferable_class_methods.rb:20:in `block in preference'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/spree_core-4.5.0/lib/spree/core/preferences/preferable.rb:51:in `set_preference'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/spree_core-4.5.0/lib/spree/core/preferences/configuration.rb:62:in `method_missing'
	from /Users/dylanfisher/projects/spree_test/config/initializers/spree.rb:2:in `block in <main>'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/spree_core-4.5.0/lib/spree/core.rb:89:in `config'
	from /Users/dylanfisher/projects/spree_test/config/initializers/spree.rb:1:in `<main>'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/engine.rb:667:in `load'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/engine.rb:667:in `block in load_config_initializer'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications.rb:208:in `instrument'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/engine.rb:666:in `load_config_initializer'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/engine.rb:619:in `each'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/engine.rb:619:in `block in <class:Engine>'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `run'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/3.1.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/3.1.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/initializable.rb:50:in `each'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/3.1.0/tsort.rb:415:in `call'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/3.1.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/application.rb:372:in `initialize!'
	from /Users/dylanfisher/projects/spree_test/config/environment.rb:5:in `<main>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/server.rb:249:in `app'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/server.rb:422:in `wrapped_app'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:36:in `start'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:143:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<main>'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/dylanfisher/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by nciemniak** [comment]
Hey @dylanfisher, another spree user has also flagged this issue and we've updated the [4.4 to 4.5 upgrade docs](https://dev-docs.spreecommerce.org/upgrades/upgrades/4.4-to-4.5) to include a fix for this, I'm wondering if there's any place that would be helpful to include this note in addition to the upgrade doc and the [spree starter readme](https://github.com/spree/spree_starter#uninitialized-constant-spreepreference-nameerror)? Maybe in this repo's readme as well?

**Comment by nciemniak** [comment]
Great idea, appreciate the feedback 🙏

**Comment by nciemniak** [comment]
Also, interesting that you get this error also from `spree_auth_devise`, do you know if this is possible to reproduce as well? I'm not getting the error, but would be happy to apply a fix if I can repro.

**Comment by dylanfisher** [comment]
`spree_auth_devise` actually loads fine as is, but I opened a PR to revert a change that prevents overriding the `Spree.user_class` here https://github.com/spree/spree_auth_devise/pull/573. That line in the PR needs to be wrapped in the `after_initialize` block because of the call to `Spree.user_class.blank?`, which references the model class.
