### ISSUE TITLE
Unable to add it to a fresh new rails app

### ISSUE THREAD

**Issue by pablogfb** [spree/spree#11975]
I'm following the official docs to add spree to a fresh new rails (7.1.2) app with ruby 3.1.3:

[https://dev-docs.spreecommerce.org/advanced/existing_app_tutorial](https://dev-docs.spreecommerce.org/advanced/existing_app_tutorial
)

When I try to execute the first install generator I'm geting an error after trying to add the default admin user:

`bin/rails g spree:install --user_class=Spree::User`

```
loading ruby [...]/.rvm/gems/ruby-3.1.3@spree/gems/spree_auth_devise-4.6.0/db/default/users.rb
Create the admin user (press enter for defaults).
Email [spree@example.com]: 
Password [spree123]: 
rake aborted!
LoadError: cannot load such file -- spree/user.rb
[...]/.rvm/gems/ruby-3.1.3@spree/gems/spree_auth_devise-4.6.0/db/default/users.rb:53:in 'load'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/spree_auth_devise-4.6.0/db/default/users.rb:53:in 'create_admin_user'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/spree_auth_devise-4.6.0/db/default/users.rb:75:in '<main>'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/spree_core-4.7.0/lib/tasks/core.rake:11:in 'load'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/spree_core-4.7.0/lib/tasks/core.rake:11:in 'block (2 levels) in <main>'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/spree_core-4.7.0/lib/tasks/core.rake:30:in 'block (3 levels) in <main>'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/spree_core-4.7.0/lib/tasks/core.rake:24:in 'each'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/spree_core-4.7.0/lib/tasks/core.rake:24:in 'block (2 levels) in <main>'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/spree_auth_devise-4.6.0/db/seeds.rb:5:in '<main>'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/railties-7.1.2/lib/rails/engine.rb:556:in 'load'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/railties-7.1.2/lib/rails/engine.rb:556:in 'block in load_seed'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:121:in 'block in run_callbacks'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/activesupport-7.1.2/lib/active_support/execution_wrapper.rb:88:in 'wrap'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/railties-7.1.2/lib/rails/engine.rb:642:in 'block (2 levels) in <class:Engine>'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:130:in 'instance_exec'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:130:in 'block in run_callbacks'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:141:in 'run_callbacks'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/railties-7.1.2/lib/rails/engine.rb:556:in 'load_seed'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/railties-7.1.2/lib/rails/railtie.rb:226:in 'public_send'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/railties-7.1.2/lib/rails/railtie.rb:226:in 'method_missing'
[...]/projects/spree/db/seeds.rb:12:in '<main>'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/railties-7.1.2/lib/rails/engine.rb:556:in 'load'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/railties-7.1.2/lib/rails/engine.rb:556:in 'block in load_seed'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:121:in 'block in run_callbacks'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/activesupport-7.1.2/lib/active_support/execution_wrapper.rb:92:in 'wrap'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/railties-7.1.2/lib/rails/engine.rb:642:in 'block (2 levels) in <class:Engine>'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:130:in 'instance_exec'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:130:in 'block in run_callbacks'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:141:in 'run_callbacks'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/railties-7.1.2/lib/rails/engine.rb:556:in 'load_seed'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/activerecord-7.1.2/lib/active_record/tasks/database_tasks.rb:468:in 'load_seed'
[...]/.rvm/gems/ruby-3.1.3@spree/gems/activerecord-7.1.2/lib/active_record/railties/databases.rake:405:in 'block (2 levels) in <main>'
```

I supppose that I could try to create the user manually from the console but I don't get why is it faling at the very first step of the docs. Might they be outdated?

Thanks for your help.

**Comment by damianlegawiec** [comment]
Hi @pablogfb 

Please do `bundle update spree_auth_devise` - this will resolve the issue, thank you for reporting!
