### ISSUE TITLE
Validation failed: Credit card  Card has expired during rake spree_sample:load

### ISSUE THREAD

**Issue by masterkain** [spree/spree#5916]
```
ruby-2.1.5] 14:52 /tmp/spreeschema $ bundle exec rake spree_sample:load
...
Loaded Adjustments samples
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Credit card  Card has expired
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/validations.rb:57:in `save!'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/transactions.rb:273:in `block in save!'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/transactions.rb:273:in `save!'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:487:in `block in save!'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:502:in `block (2 levels) in around_save'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:150:in `block in run_actions'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:170:in `catch_exceptions'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:148:in `run_actions'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:133:in `run_callbacks'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:212:in `run_callbacks'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:63:in `block (2 levels) in perform'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:63:in `catch'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:63:in `block in perform'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:186:in `within_transaction'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:62:in `perform'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:502:in `block in around_save'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:530:in `block in transaction'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:529:in `transaction'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:501:in `around_save'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:487:in `save!'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/associations/has_many_association.rb:38:in `insert_record'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:462:in `block (2 levels) in _create_record'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:389:in `add_to_target'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:460:in `block in _create_record'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:168:in `block in transaction'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:167:in `transaction'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:459:in `_create_record'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:141:in `create!'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/associations/collection_proxy.rb:301:in `create!'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/spree_sample-2.4.2/db/samples/payments.rb:20:in `block in <top (required)>'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/relation/delegation.rb:132:in `each'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/relation/delegation.rb:132:in `each_with_index'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/relation/delegation.rb:132:in `public_send'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/relation/delegation.rb:132:in `method_missing'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/relation/delegation.rb:99:in `method_missing'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/spree_sample-2.4.2/db/samples/payments.rb:18:in `<top (required)>'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/spree_sample-2.4.2/lib/spree/sample.rb:13:in `load_sample'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/spree_sample-2.4.2/lib/spree_sample.rb:28:in `load_samples'
/Users/kain/.rvm/gems/ruby-2.1.5/gems/spree_sample-2.4.2/lib/tasks/sample.rake:20:in `block (2 levels) in <top (required)>'
/Users/kain/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/kain/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => spree_sample:load
(See full trace by running task with --trace)
```

**Comment by JDutil** [comment]
Update to 2-4-stable.
