### ISSUE TITLE
Issue with Sidekiq on Spree 3.0 

### ISSUE THREAD

**Issue by romul** [spree/spree#6083]
In development mode (`config.cache_classes = false`) `bundle exec sidekiq` causes the such error:
```
Cannot define multiple 'included' blocks for a Concern
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/concern.rb:126:in `included'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/spree-80c47e09d7bc/core/app/models/spree/preferences/preferable.rb:37:in `<module:Preferable>'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/spree-80c47e09d7bc/core/app/models/spree/preferences/preferable.rb:34:in `<top (required)>'
...
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
/Users/roman/www/application/config/environment.rb:5:in `<top (required)>'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.2/lib/sidekiq/cli.rb:236:in `boot_system'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.2/lib/sidekiq/cli.rb:50:in `run'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.2/bin/sidekiq:8:in `<top (required)>'
/Users/roman/.rbenv/versions/2.1.2/bin/sidekiq:23:in `load'
/Users/roman/.rbenv/versions/2.1.2/bin/sidekiq:23:in `<main>'
```
Looks like a double load of some files. I'm pretty sure, that this bug isn't restricted to sidekiq and can appear in other cases.

**Comment by romul** [comment]
Can be fixed with something like https://github.com/romul/spree/commit/f532dd841db65800db5f2f3ebfb6424b991ef60f
But figuring out reasons of double load would be much better.

**Comment by romul** [comment]
Additional note: Not reproduced with vanilla Spree. Only with extensions.

**Comment by romul** [comment]
Error is caused by spree_shared. I'll move ticket to it.
