### ISSUE TITLE
Unable to refund payment

### ISSUE THREAD

**Issue by BenMorganIO** [spree/spree#6113]
Steps to Reproduce:
1. Create a complete order (I used Stripe).
2. Go the admin orders and accept the payment
3. (Including this since I did perform this action) Create a $5 adjustment. Push the close all adjustments.
4. Go to the edit page and refund the order.

And here's the error:

```ruby
19:02:06 web.1    | Started GET "/admin/orders/R936383215/payments/PGVCIFAV/refunds/new" for ::1 at 2015-03-04 19:02:06 -0800
19:02:07 web.1    | Processing by Spree::Admin::RefundsController#new as HTML
19:02:07 web.1    |   Parameters: {"order_id"=>"R936383215", "payment_id"=>"PGVCIFAV"}
19:02:07 web.1    |   Spree::Preference Load (0.3ms)  SELECT  "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = $1 LIMIT 1 /*application:SpreeApplication,controller:refunds,action:new*/  [["key", "spree/backend_configuration/locale"]]
19:02:07 web.1    |   Spree::User Load (0.4ms)  SELECT  "spree_users".* FROM "spree_users" WHERE "spree_users"."deleted_at" IS NULL AND "spree_users"."id" = $1  ORDER BY "spree_users"."id" ASC LIMIT 1 /*application:SpreeApplication,controller:refunds,action:new*/  [["id", 1]]
19:02:07 web.1    |   Spree::Store Load (0.6ms)  SELECT  "spree_stores".* FROM "spree_stores" WHERE (url like '%localhost%')  ORDER BY "spree_stores"."id" ASC LIMIT 1 /*application:SpreeApplication,controller:refunds,action:new*/
19:02:07 web.1    |   Spree::Store Load (1.9ms)  SELECT  "spree_stores".* FROM "spree_stores" WHERE "spree_stores"."default" = 't'  ORDER BY "spree_stores"."id" ASC LIMIT 1 /*application:SpreeApplication,controller:refunds,action:new*/
19:02:07 web.1    |   Spree::Order Load (0.5ms)  SELECT  "spree_orders".* FROM "spree_orders" WHERE "spree_orders"."completed_at" IS NULL AND "spree_orders"."currency" = $1 AND "spree_orders"."guest_token" = $2 AND "spree_orders"."store_id" = $3 AND "spree_orders"."user_id" = $4 LIMIT 1 /*application:SpreeApplication,controller:refunds,action:new*/  [["currency", "USD"], ["guest_token", "G_cYU3pAipuw0BjwEijPog"], ["store_id", 1], ["user_id", 1]]
19:02:07 web.1    |   Spree::Order Load (0.4ms)  SELECT  "spree_orders".* FROM "spree_orders" WHERE "spree_orders"."user_id" = $1 AND "spree_orders"."completed_at" IS NULL  ORDER BY created_at DESC LIMIT 1 /*application:SpreeApplication,controller:refunds,action:new*/  [["user_id", 1]]
19:02:07 web.1    |    (0.4ms)  SELECT COUNT(*) FROM "spree_roles" INNER JOIN "spree_roles_users" ON "spree_roles"."id" = "spree_roles_users"."role_id" WHERE "spree_roles_users"."user_id" = $1 AND "spree_roles"."name" = $2 /*application:SpreeApplication,controller:refunds,action:new*/  [["user_id", 1], ["name", "admin"]]
19:02:07 web.1    |   Spree::Payment Load (0.4ms)  SELECT  "spree_payments".* FROM "spree_payments" WHERE "spree_payments"."id" = $1  ORDER BY spree_payments.created_at LIMIT 1 /*application:SpreeApplication,controller:refunds,action:new*/  [["id", 0]]
19:02:07 web.1    | Completed 500 Internal Server Error in 64ms
19:02:07 web.1    |
19:02:07 web.1    | NoMethodError - undefined method `refunds' for nil:NilClass:
19:02:07 web.1    |    () Users/benmorgan/.rvm/gems/ruby-2.2.0/bundler/gems/spree-dab5db15f3b8/backend/app/controllers/spree/admin/resource_controller.rb:183:in `build_resource'
19:02:07 web.1    |    () Users/benmorgan/.rvm/gems/ruby-2.2.0/bundler/gems/spree-dab5db15f3b8/backend/app/controllers/spree/admin/refunds_controller.rb:27:in `build_resource'
19:02:07 web.1    |    () Users/benmorgan/.rvm/gems/ruby-2.2.0/bundler/gems/spree-dab5db15f3b8/backend/app/controllers/spree/admin/resource_controller.rb:153:in `load_resource_instance'
19:02:07 web.1    |    () Users/benmorgan/.rvm/gems/ruby-2.2.0/bundler/gems/spree-dab5db15f3b8/backend/app/controllers/spree/admin/resource_controller.rb:133:in `load_resource'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:427:in `block in make_lambda'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:308:in `block (2 levels) in halting'
19:02:07 web.1    |   (eval):3:in `record_query_comment'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:427:in `block in make_lambda'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:307:in `block in halting'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
19:02:07 web.1    |   actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
19:02:07 web.1    |   activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
19:02:07 web.1    |   actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
19:02:07 web.1    |   actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
19:02:07 web.1    |   railties (4.2.0) lib/rails/engine.rb:518:in `call'
19:02:07 web.1    |   railties (4.2.0) lib/rails/railtie.rb:194:in `method_missing'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/routing/mapper.rb:51:in `serve'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   bullet (4.13.2) lib/bullet/rack.rb:10:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   meta_request (0.3.4) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/rack/developer_mode.rb:56:in `traced_call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
19:02:07 web.1    |   warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
19:02:07 web.1    |   warden (1.2.3) lib/warden/manager.rb:34:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   rack (1.6.0) lib/rack/etag.rb:24:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   rack (1.6.0) lib/rack/head.rb:13:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
19:02:07 web.1    |   rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   better_errors (2.0.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
19:02:07 web.1    |   better_errors (2.0.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
19:02:07 web.1    |   better_errors (2.0.0) lib/better_errors/middleware.rb:57:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   rack-contrib (1.1.0) lib/rack/contrib/response_headers.rb:17:in `call'
19:02:07 web.1    |   meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
19:02:07 web.1    |   railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
19:02:07 web.1    |   activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
19:02:07 web.1    |   railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   rack (1.6.0) lib/rack/runtime.rb:18:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   rack (1.6.0) lib/rack/lock.rb:17:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
19:02:07 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
19:02:07 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
19:02:07 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
19:02:07 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   railties (4.2.0) lib/rails/engine.rb:518:in `call'
19:02:07 web.1    |   railties (4.2.0) lib/rails/application.rb:164:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
19:02:07 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
19:02:07 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
19:02:07 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
19:02:07 web.1    |   rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
19:02:07 web.1    |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
19:02:07 web.1    |   rack (1.6.0) lib/rack/content_length.rb:15:in `call'
19:02:07 web.1    |   puma (2.11.0) lib/puma/server.rb:507:in `handle_request'
19:02:07 web.1    |   puma (2.11.0) lib/puma/server.rb:375:in `process_client'
19:02:07 web.1    |   puma (2.11.0) lib/puma/server.rb:262:in `block in run'
19:02:07 web.1    |   puma (2.11.0) lib/puma/thread_pool.rb:104:in `block in spawn_thread'
19:02:07 web.1    |   logging (1.8.2) lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

**Comment by BenMorganIO** [comment]
Also, why are we nesting at three levels? Isn't this a bad practice?

**Comment by BenMorganIO** [comment]
It should probably be something like:

````json
/admin/orders/:order_id/refunds/new

{
  "payment_id": "dskfasdeoijedc"
}
```

**Comment by JDutil** [comment]
Should be fixed by https://github.com/spree/spree/pull/6100

**Comment by BenMorganIO** [comment]
@JDutil thanks
