### ISSUE TITLE
spree/core/app/models/spree/option_type.rb and option types sorting

### ISSUE THREAD

**Issue by connecticus** [spree/spree#6114]
spree 2.4

Оption types not stored after sorting by reason of error:

Started POST "/admin/option_types/update_positions" for 127.0.0.1 at 2015-03-04 21:02:35 -0800
Processing by Spree::Admin::OptionTypesController#update_positions as JS
  Parameters: {"positions"=>{"1"=>"0", "3"=>"1", "4"=>"2", "5"=>"3", "6"=>"4", "7"=>"5", "8"=>"6", "9"=>"7", "11"=>"8"}}
  Spree::User Load (0.3ms)  SELECT  "spree_users".* FROM "spree_users"  WHERE "spree_users"."deleted_at" IS NULL AND "spree_users"."id" = 1  ORDER BY "spree_users"."id" ASC LIMIT 1
   (0.1ms)  SELECT COUNT(*) FROM "spree_roles" INNER JOIN "spree_roles_users" ON "spree_roles"."id" = "spree_roles_users"."role_id" WHERE "spree_roles_users"."user_id" = ? AND "spree_roles"."name" = 'admin'  [["user_id", 1]]
   (0.1ms)  begin transaction
  Spree::OptionType Load (0.2ms)  SELECT  "spree_option_types".* FROM "spree_option_types"  WHERE "spree_option_types"."id" = ?  ORDER BY spree_option_types.position LIMIT 1  [["id", 1]]
   (0.1ms)  rollback transaction
  Spree::OptionType::Translation Load (0.1ms)  SELECT "spree_option_type_translations".* FROM "spree_option_type_translations"  WHERE "spree_option_type_translations"."spree_option_type_id" = ?  [["spree_option_type_id", 1]]
Completed 500 Internal Server Error in 13ms

NoMethodError (undefined method `set_list_position' for #<Spree::OptionType:0x0000000a6adba0>):
  activemodel (4.1.9) lib/active_model/attribute_methods.rb:435:in `method_missing'
  activerecord (4.1.9) lib/active_record/attribute_methods.rb:213:in `method_missing'

**Comment by connecticus** [comment]
It's need to add 'acts_as_list' to fix this.
