### ISSUE TITLE
Unable to add a taxon to a product

### ISSUE THREAD

**Issue by bricesanchez** [spree/spree#6300]
I'm on 3-0-stable branch, my spree is mounted to `/catalog/`.
When i try to add a taxon to my product with the autocomplete field, i have this error : 

```shell
GET http://localhost:3000/catalogapi/taxons?per_page=50&page=1&without_children…5D=&token=d5a7f2e6ac9d2f319777f80b2479e804798c496d90e8a5e5&_=1429196910463 422 (Unprocessable Entity)
```

This is my stacktrace : 

```shell
Started GET "/catalogapi/taxons?per_page=50&page=1&without_children=true&q%5Bname_cont%5D=&token=d5a7f2e6ac9d2f319777f80b2479e804798c496d90e8a5e5&_=1429196910463" for 127.0.0.1 at 2015-04-16 11:08:37 -0400
Processing by Spree::Api::TaxonsController#index as JSON
  Parameters: {"per_page"=>"50", "page"=>"1", "without_children"=>"true", "q"=>{"name_cont"=>""}, "token"=>"d5a7f2e6ac9d2f319777f80b2479e804798c496d90e8a5e5", "_"=>"1429196910463"}
  Spree::User Load (1.1ms)  SELECT  "spree_users".* FROM "spree_users" WHERE "spree_users"."deleted_at" IS NULL AND "spree_users"."id" = $1  ORDER BY "spree_users"."id" ASC LIMIT 1  [["id", 1]]
  Spree::User Load (0.4ms)  SELECT  "spree_users".* FROM "spree_users" WHERE "spree_users"."deleted_at" IS NULL AND "spree_users"."spree_api_key" = $1 LIMIT 1  [["spree_api_key", "d5a7f2e6ac9d2f319777f80b2479e804798c496d90e8a5e5"]]
   (0.3ms)  SELECT "spree_roles"."name" FROM "spree_roles" INNER JOIN "spree_roles_users" ON "spree_roles"."id" = "spree_roles_users"."role_id" WHERE "spree_roles_users"."user_id" = $1  [["user_id", 1]]
   (0.4ms)  SELECT COUNT(*) FROM "spree_roles" INNER JOIN "spree_roles_users" ON "spree_roles"."id" = "spree_roles_users"."role_id" WHERE "spree_roles_users"."user_id" = $1 AND "spree_roles"."name" = $2  [["user_id", 1], ["name", "admin"]]
   (0.4ms)  SELECT COUNT(*) FROM "spree_taxons"
  Spree::Taxon Load (0.5ms)  SELECT  "spree_taxons".* FROM "spree_taxons"  ORDER BY "spree_taxons"."taxonomy_id" ASC, "spree_taxons"."lft" ASC LIMIT 50 OFFSET 0
  Spree::Taxon Load (0.5ms)  SELECT "spree_taxons".* FROM "spree_taxons" WHERE "spree_taxons"."parent_id" IN (1, 2)  ORDER BY "lft"
  Rendered .gems/bundler/gems/spree-147652470a55/api/app/views/spree/api/taxons/index.v1.rabl (213.2ms)
undefined method `total_count' for #<Spree::Taxon::ActiveRecord_Relation:0x007f85ecc0eb70>
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb:136:in `method_missing'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb:99:in `method_missing'
(eval):3:in `block in render'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rabl-0.9.4.pre1/lib/rabl/builder.rb:112:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rabl-0.9.4.pre1/lib/rabl/builder.rb:112:in `node'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rabl-0.9.4.pre1/lib/rabl/builder.rb:87:in `block in update_settings'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rabl-0.9.4.pre1/lib/rabl/builder.rb:86:in `each'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rabl-0.9.4.pre1/lib/rabl/builder.rb:86:in `update_settings'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rabl-0.9.4.pre1/lib/rabl/builder.rb:41:in `compile_hash'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rabl-0.9.4.pre1/lib/rabl/builder.rb:28:in `block in build'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rabl-0.9.4.pre1/lib/rabl/builder.rb:212:in `cache_results'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rabl-0.9.4.pre1/lib/rabl/builder.rb:27:in `build'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rabl-0.9.4.pre1/lib/rabl/engine.rb:48:in `to_hash'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rabl-0.9.4.pre1/lib/rabl/engine.rb:62:in `to_json'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rabl-0.9.4.pre1/lib/rabl/engine.rb:36:in `block in render'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rabl-0.9.4.pre1/lib/rabl/engine.rb:296:in `cache_results'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rabl-0.9.4.pre1/lib/rabl/engine.rb:36:in `render'
/Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/spree-147652470a55/api/app/views/spree/api/taxons/index.v1.rabl:2:in `_7c705bb4dbcdcb4d897ea371bcbcf314'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionview-4.2.0/lib/action_view/template.rb:145:in `block in render'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionview-4.2.0/lib/action_view/template.rb:333:in `instrument'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionview-4.2.0/lib/action_view/template.rb:143:in `render'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/deface-1.0.1/lib/deface/action_view_extensions.rb:41:in `render'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionview-4.2.0/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionview-4.2.0/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionview-4.2.0/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionview-4.2.0/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionview-4.2.0/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionview-4.2.0/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionview-4.2.0/lib/action_view/renderer/template_renderer.rb:14:in `render'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionview-4.2.0/lib/action_view/renderer/renderer.rb:42:in `render_template'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionview-4.2.0/lib/action_view/renderer/renderer.rb:23:in `render'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionview-4.2.0/lib/action_view/rendering.rb:100:in `_render_template'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionview-4.2.0/lib/action_view/rendering.rb:83:in `render_to_body'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/abstract_controller/rendering.rb:25:in `render'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:16:in `render'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/bci20/.rbenv/versions/2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:40:in `render'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/responders-2.1.0/lib/action_controller/responder.rb:236:in `default_render'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/responders-2.1.0/lib/action_controller/responder.rb:186:in `to_format'
/Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/spree-147652470a55/api/lib/spree/api/responders/rabl_template.rb:9:in `to_format'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/responders-2.1.0/lib/action_controller/responder.rb:163:in `respond'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/responders-2.1.0/lib/action_controller/responder.rb:156:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/responders-2.1.0/lib/action_controller/respond_with.rb:203:in `respond_with'
/Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/spree-147652470a55/core/lib/spree/core/controller_helpers/respond_with.rb:16:in `respond_with'
/Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/spree-147652470a55/api/app/controllers/spree/api/taxons_controller.rb:16:in `index'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:198:in `process_action'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:10:in `process_action'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_controller/metal/rescue.rb:29:in `process_action'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:137:in `process'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionview-4.2.0/lib/action_view/rendering.rb:30:in `process'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_controller/metal.rb:195:in `dispatch'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_controller/metal.rb:236:in `block in action'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:73:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:42:in `serve'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `each'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `serve'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:802:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `public_send'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `method_missing'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:51:in `serve'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `each'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `serve'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:802:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/dragonfly-1.0.7/lib/dragonfly/middleware.rb:14:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/dragonfly-1.0.7/lib/dragonfly/middleware.rb:14:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/dragonfly-1.0.7/lib/dragonfly/middleware.rb:14:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-1.6.0/lib/rack/etag.rb:24:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-1.6.0/lib/rack/conditionalget.rb:25:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/middleware/flash.rb:260:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.0/lib/active_record/query_cache.rb:36:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.0/lib/active_record/migration.rb:378:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/middleware/reloader.rb:73:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/web-console-2.1.2/lib/web_console/middleware.rb:37:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/railties-4.2.0/lib/rails/rack/logger.rb:38:in `call_app'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `block in call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `tagged'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/quiet_assets-1.1.0/lib/quiet_assets.rb:27:in `call_with_quiet_assets'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-1.6.0/lib/rack/runtime.rb:18:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-1.6.0/lib/rack/lock.rb:17:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/dragonfly-1.0.7/lib/dragonfly/cookie_monster.rb:9:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-livereload-0.3.15/lib/rack/livereload.rb:23:in `_call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-livereload-0.3.15/lib/rack/livereload.rb:14:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/actionpack-4.2.0/lib/action_dispatch/middleware/static.rb:113:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-1.6.0/lib/rack/sendfile.rb:113:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/rack-1.6.0/lib/rack/content_length.rb:15:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/puma-2.11.2/lib/puma/server.rb:507:in `handle_request'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/puma-2.11.2/lib/puma/server.rb:375:in `process_client'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/puma-2.11.2/lib/puma/server.rb:262:in `block in run'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `call'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
  Rendered text template (0.0ms)
Completed 422 Unprocessable Entity in 3412ms (Views: 3.4ms | ActiveRecord: 3.7ms)
```

**Comment by JDutil** [comment]
Appears to be related to https://github.com/spree/spree/issues/5198 but thought that was fixed on 2.4+ :(

**Comment by bricesanchez** [comment]
It works well for option_types but not for taxons

**Comment by bricesanchez** [comment]
It does the same problem on `spree_related_products` when i want to add a variant : 
`
http://localhost:3000/catalogapi/variants?q%5Bproduct_name_or_sku_cont%5D=test&token=d5a7f2e6ac9d2f319777f80b2479e804798c496d90e8a5e5&_=1429292352080 Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)`

**Comment by JDutil** [comment]
Any issues related to this are likely from incorrect usage of the route helpers in the javascript see this bad line:
https://github.com/spree/spree/blob/master/backend/app/assets/javascripts/spree/backend/taxon_autocomplete.js.erb#L18 

Good line: https://github.com/spree/spree/blob/master/backend/app/assets/javascripts/spree/backend/taxon_autocomplete.js.erb#L9

You can get familiar with what the spree url stuff is doing by checking out this js file https://github.com/spree/spree/blob/master/core/app/assets/javascripts/spree.js.coffee.erb

**Comment by bricesanchez** [comment]
My problem was related to the bridge between my Refinery CMS and my Spree : 
https://github.com/bricesanchez/spree-refinery-authentication/commit/58bbede7a0c7c45c6d98b5b768ac880cab13fdea

I'm now able to add and list taxons with this malformed path  : 
```shell
http://localhost:3000/catalogapi/taxons?ids=2&token=d5a7f2e6ac9d2f....98c496d90e8a5e5
```

**Comment by JDutil** [comment]
Odd well I think to get the url corrected my previous suggestion would still need to be done.
