### ISSUE TITLE
NoMethodError - undefined method `start_with?' for nil:NilClass:

### ISSUE THREAD

**Issue by cdesch** [spree/spree#6318]
I get the following error after updating to the latest version of spree `3.0.0.rc4`  and pulling from `gem 'spree', github: 'spree/spree', branch: '3-0-stable'`

     NoMethodError - undefined method `start_with?' for nil:NilClass:

This error came up directly after updating the gem. I was on `3.0.0`  which i believe was `3.0.0.rc3`

**Comment by cdesch** [comment]
Full stack trace


    NoMethodError - undefined method `start_with?' for nil:NilClass:
      sprockets (3.0.1) lib/sprockets/path_utils.rb:111:in `split_subpath'
      sprockets (3.0.1) lib/sprockets/path_utils.rb:126:in `block in paths_split'
      sprockets (3.0.1) lib/sprockets/path_utils.rb:125:in `paths_split'
      sprockets (3.0.1) lib/sprockets/resolve.rb:88:in `resolve_relative_path'
      sprockets (3.0.1) lib/sprockets/resolve.rb:33:in `resolve'
      sprockets (3.0.1) lib/sprockets/legacy.rb:66:in `resolve_with_compat'
      sprockets (3.0.1) lib/sprockets/base.rb:61:in `find_asset'
      sprockets (3.0.1) lib/sprockets/base.rb:89:in `[]'
      sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:230:in `lookup_asset_for_path'
      sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:190:in `check_errors_for'
      sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:89:in `asset_path'
      sprockets (3.0.1) lib/sprockets/sass_processor.rb:117:in `asset_path'
      sprockets (3.0.1) lib/sprockets/sass_processor.rb:130:in `asset_url'
      sass (3.4.13) lib/sass/script/tree/funcall.rb:140:in `_perform'
      sass (3.4.13) lib/sass/script/tree/node.rb:50:in `perform'
      sass (3.4.13) lib/sass/tree/visitors/perform.rb:394:in `visit_prop'
      sass (3.4.13) lib/sass/tree/visitors/base.rb:36:in `visit'
      sass (3.4.13) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
      sass (3.4.13) lib/sass/stack.rb:79:in `block in with_base'
      sass (3.4.13) lib/sass/stack.rb:115:in `with_frame'
      sass (3.4.13) lib/sass/stack.rb:79:in `with_base'
      sass (3.4.13) lib/sass/tree/visitors/perform.rb:158:in `visit'
      sass (3.4.13) lib/sass/tree/visitors/perform.rb:501:in `block (2 levels) in visit_directive'
      sass (3.4.13) lib/sass/tree/visitors/perform.rb:501:in `block in visit_directive'
      sass (3.4.13) lib/sass/tree/visitors/perform.rb:179:in `with_environment'
      sass (3.4.13) lib/sass/tree/visitors/perform.rb:500:in `visit_directive'
      sass (3.4.13) lib/sass/tree/visitors/base.rb:36:in `visit'
      sass (3.4.13) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
      sass (3.4.13) lib/sass/stack.rb:79:in `block in with_base'
      sass (3.4.13) lib/sass/stack.rb:115:in `with_frame'
      sass (3.4.13) lib/sass/stack.rb:79:in `with_base'
      sass (3.4.13) lib/sass/tree/visitors/perform.rb:158:in `visit'
      sass (3.4.13) lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
      sass (3.4.13) lib/sass/tree/visitors/base.rb:52:in `visit_children'
      sass (3.4.13) lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
      sass (3.4.13) lib/sass/tree/visitors/perform.rb:179:in `with_environment'
      sass (3.4.13) lib/sass/tree/visitors/perform.rb:166:in `visit_children'
      sass (3.4.13) lib/sass/tree/visitors/base.rb:36:in `block in visit'
      sass (3.4.13) lib/sass/tree/visitors/perform.rb:186:in `visit_root'
      sass (3.4.13) lib/sass/tree/visitors/base.rb:36:in `visit'
      sass (3.4.13) lib/sass/tree/visitors/perform.rb:157:in `visit'
      sass (3.4.13) lib/sass/tree/visitors/perform.rb:8:in `visit'
      sass (3.4.13) lib/sass/tree/root_node.rb:36:in `css_tree'
      sass (3.4.13) lib/sass/tree/root_node.rb:20:in `render'
      sass (3.4.13) lib/sass/engine.rb:268:in `render'
      sass-rails (5.0.3) lib/sass/rails/template.rb:47:in `evaluate'
      tilt (1.4.1) lib/tilt/template.rb:103:in `render'
      sprockets (3.0.1) lib/sprockets/legacy_tilt_processor.rb:25:in `call'
      sprockets (3.0.1) lib/sprockets/processor_utils.rb:73:in `call_processor'
      sprockets (3.0.1) lib/sprockets/processor_utils.rb:55:in `block in call_processors'
      sprockets (3.0.1) lib/sprockets/processor_utils.rb:54:in `call_processors'
      sprockets (3.0.1) lib/sprockets/loader.rb:103:in `load_asset_by_uri'
      sprockets (3.0.1) lib/sprockets/loader.rb:40:in `block in load'
      sprockets (3.0.1) lib/sprockets/loader.rb:170:in `fetch_asset_from_dependency_cache'
      sprockets (3.0.1) lib/sprockets/loader.rb:33:in `load'
      sprockets (3.0.1) lib/sprockets/cached_environment.rb:20:in `block in initialize'
      sprockets (3.0.1) lib/sprockets/cached_environment.rb:47:in `load'
      sprockets (3.0.1) lib/sprockets/bundle.rb:23:in `block in call'
      sprockets (3.0.1) lib/sprockets/utils.rb:183:in `dfs'
      sprockets (3.0.1) lib/sprockets/bundle.rb:24:in `call'
      sprockets (3.0.1) lib/sprockets/processor_utils.rb:73:in `call_processor'
      sprockets (3.0.1) lib/sprockets/processor_utils.rb:55:in `block in call_processors'
      sprockets (3.0.1) lib/sprockets/processor_utils.rb:54:in `call_processors'
      sprockets (3.0.1) lib/sprockets/loader.rb:103:in `load_asset_by_uri'
      sprockets (3.0.1) lib/sprockets/loader.rb:40:in `block in load'
      sprockets (3.0.1) lib/sprockets/loader.rb:170:in `fetch_asset_from_dependency_cache'
      sprockets (3.0.1) lib/sprockets/loader.rb:33:in `load'
      sprockets (3.0.1) lib/sprockets/cached_environment.rb:20:in `block in initialize'
      sprockets (3.0.1) lib/sprockets/cached_environment.rb:47:in `load'
      sprockets (3.0.1) lib/sprockets/base.rb:63:in `find_asset'
      sprockets (3.0.1) lib/sprockets/environment.rb:30:in `find_asset'
      sprockets (3.0.1) lib/sprockets/base.rb:89:in `[]'
      sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:230:in `lookup_asset_for_path'
      sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:190:in `check_errors_for'
      sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:159:in `block in stylesheet_link_tag'
      sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:158:in `stylesheet_link_tag'
      app/views/layouts/_header_scripts.html.erb:9:in `_f027cd8382f46d3cca51439219192f26'
      actionview (4.2.0) lib/action_view/template.rb:145:in `block in render'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
      activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
      actionview (4.2.0) lib/action_view/template.rb:333:in `instrument'
      actionview (4.2.0) lib/action_view/template.rb:143:in `render'
      deface (1.0.1) lib/deface/action_view_extensions.rb:41:in `render'
      actionview (4.2.0) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
      actionview (4.2.0) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
      actionview (4.2.0) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
      activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
      actionview (4.2.0) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
      actionview (4.2.0) lib/action_view/renderer/partial_renderer.rb:309:in `render'
      actionview (4.2.0) lib/action_view/renderer/renderer.rb:47:in `render_partial'
      actionview (4.2.0) lib/action_view/helpers/rendering_helper.rb:35:in `render'
      app/views/layouts/application.html.erb:17:in `_3d59895301982bbb0ac5730a2061c8fe'
      actionview (4.2.0) lib/action_view/template.rb:145:in `block in render'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
      activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
      actionview (4.2.0) lib/action_view/template.rb:333:in `instrument'
      actionview (4.2.0) lib/action_view/template.rb:143:in `render'
      deface (1.0.1) lib/deface/action_view_extensions.rb:41:in `render'
      actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
      actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
      actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:14:in `render'
      actionview (4.2.0) lib/action_view/renderer/renderer.rb:42:in `render_template'
      actionview (4.2.0) lib/action_view/renderer/renderer.rb:23:in `render'
      actionview (4.2.0) lib/action_view/rendering.rb:100:in `_render_template'
      actionpack (4.2.0) lib/action_controller/metal/streaming.rb:217:in `_render_template'
      actionview (4.2.0) lib/action_view/rendering.rb:83:in `render_to_body'
      actionpack (4.2.0) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
      actionpack (4.2.0) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
      actionpack (4.2.0) lib/abstract_controller/rendering.rb:25:in `render'
      actionpack (4.2.0) lib/action_controller/metal/rendering.rb:16:in `render'
      actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
      activesupport (4.2.0) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
      /Users/cj/.rbenv/versions/2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
      activesupport (4.2.0) lib/active_support/core_ext/benchmark.rb:12:in `ms'
      actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
      actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
      activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
      actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:40:in `render'
      actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
      actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
      actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
      actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
      actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
      activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
      activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
      activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
      activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
      activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
      activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
      activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
      activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
      activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
      activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
      actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
      actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
      actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
      activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
      actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
      actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
      activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
      actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
      actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
      actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
      actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
      actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
      actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
      actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
      actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
      actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
      actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/rack/developer_mode.rb:56:in `traced_call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
      warden (1.2.3) lib/warden/manager.rb:34:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/etag.rb:24:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/head.rb:13:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
      rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
      activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
      activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
      actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      airbrake (4.1.0) lib/airbrake/rails/middleware.rb:13:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
      better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
      better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:18:in `middleware_call'
      web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:13:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
      railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
      activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
      activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
      activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
      railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/runtime.rb:18:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/lock.rb:17:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
      airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      railties (4.2.0) lib/rails/engine.rb:518:in `call'
      railties (4.2.0) lib/rails/application.rb:164:in `call'
      newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.0) lib/rack/content_length.rb:15:in `call'
      thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
      thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
      thin (1.6.3) lib/thin/connection.rb:53:in `process'
      thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
      eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
      thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
      thin (1.6.3) lib/thin/server.rb:162:in `start'
      rack (1.6.0) lib/rack/handler/thin.rb:19:in `run'
      rack (1.6.0) lib/rack/server.rb:286:in `start'
      railties (4.2.0) lib/rails/commands/server.rb:80:in `start'
      railties (4.2.0) lib/rails/commands/commands_tasks.rb:80:in `block in server'
      railties (4.2.0) lib/rails/commands/commands_tasks.rb:75:in `server'
      railties (4.2.0) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
      railties (4.2.0) lib/rails/commands.rb:17:in `<top (required)>'
      bin/rails:4:in `<top (required)>'
      -e:1:in `<main>'

**Comment by cdesch** [comment]
issue unrelated to spree
