### ISSUE TITLE
TypeError: unknown filter type: #<Pathname:spree/backend/all.js>

### ISSUE THREAD

**Issue by sepastian** [spree/spree#6329]
When I do

    RAILS_ENV=production bin/rake assets:precompile --trace

I suddenly get

```
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
rake aborted!
TypeError: unknown filter type: #<Pathname:spree/backend/all.js>
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sprockets-3.0.2/lib/sprockets/legacy.rb:290:in `compile_match_filter'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sprockets-3.0.2/lib/sprockets/manifest.rb:125:in `block in find'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sprockets-3.0.2/lib/sprockets/manifest.rb:125:in `map'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sprockets-3.0.2/lib/sprockets/manifest.rb:125:in `find'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sprockets-3.0.2/lib/sprockets/manifest.rb:162:in `compile'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sprockets-3.0.2/lib/rake/sprocketstask.rb:147:in `with_logger'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/var/www/naturprodukte-kampl.at/bin/rake:8:in `<top (required)>'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
-e:1:in `<main>'
Tasks: TOP => assets:precompile
```

What is going on? I tried cloning my repository again, no success...

**Comment by sepastian** [comment]
Hello, the problem had nothing to do with spree.

If anyone runs into a similar issue, here's how I solved the problem. In my `config/initializer/assets.rb`, I added a list of `Pathmane` objects representing assets to be precompiled. At some point, I haven't checked where and when exactly, sprockets stopped accepting `Pathname` objects for precompilation and threw an error. The problem was solved by using `Pathname#to_s` instead, took me a while to figure that out...
