### ISSUE TITLE
NoMethodError on 2-4-stable (update: think this is not a bug but instead a misconfiguration in db)

### ISSUE THREAD

**Issue by Koldof** [spree/spree#6573]
So I've had tons of issues getting spree working. I ran into this [passenger (or maybe bundler) bug](http://stackoverflow.com/questions/5007773/installing-gems-with-bundler-big-problem). But while attempting to work around it I updated the bundles, that seems to have caused a new problem.

I'm not sure how to replicate it however. It happens on any call to /admin or and products. Has anybody else ran into this, or do they know how to fix it? I'm almost considering undergoing a full restart, but there's a ton of work I don't want to have to repeat.

Here's the production.log:

```
F, [2015-07-06T15:31:33.388612 #16733] FATAL -- : 
NoMethodError (undefined method "id" for nil:NilClass):
  vendor/bundle/ruby/2.0.0/bundler/gems/spree-d51a45c1c3ac/core/app/models/spree/zone.rb:109:in "collect"
  vendor/bundle/ruby/2.0.0/bundler/gems/spree-d51a45c1c3ac/core/app/models/spree/zone.rb:109:in "contains?"
  vendor/bundle/ruby/2.0.0/bundler/gems/spree-d51a45c1c3ac/core/app/models/spree/tax_rate.rb:187:in "default_zone_or_zone_match?"
  vendor/bundle/ruby/2.0.0/bundler/gems/spree-d51a45c1c3ac/core/app/models/spree/tax_rate.rb:174:in "compute_amount"
  vendor/bundle/ruby/2.0.0/bundler/gems/spree-d51a45c1c3ac/core/app/models/spree/tax_rate.rb:153:in "adjust"
  vendor/bundle/ruby/2.0.0/bundler/gems/spree-d51a45c1c3ac/core/app/models/spree/tax_rate.rb:91:in "block (2 levels) in adjust"
  vendor/bundle/ruby/2.0.0/bundler/gems/spree-d51a45c1c3ac/core/app/models/spree/tax_rate.rb:90:in "each"
  vendor/bundle/ruby/2.0.0/bundler/gems/spree-d51a45c1c3ac/core/app/models/spree/tax_rate.rb:90:in "block in adjust"
  vendor/bundle/ruby/2.0.0/bundler/gems/spree-d51a45c1c3ac/core/app/models/spree/tax_rate.rb:87:in "each"
  vendor/bundle/ruby/2.0.0/bundler/gems/spree-d51a45c1c3ac/core/app/models/spree/tax_rate.rb:87:in "adjust"
  vendor/bundle/ruby/2.0.0/bundler/gems/spree-d51a45c1c3ac/core/app/models/spree/line_item.rb:145:in "update_tax_charge"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:429:in "block in make_lambda"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:224:in "call"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:224:in "block in halting_and_conditional"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:503:in "call"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:503:in "block in call"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:503:in "each"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:503:in "call"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:86:in "run_callbacks"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/callbacks.rb:306:in "_create_record"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/timestamp.rb:57:in "_create_record"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/persistence.rb:484:in "create_or_update"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/callbacks.rb:302:in "block in create_or_update"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:113:in "call"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:113:in "call"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:552:in "block (2 levels) in compile"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:502:in "call"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:502:in "call"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:86:in "run_callbacks"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/callbacks.rb:302:in "create_or_update"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/persistence.rb:125:in "save!"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/validations.rb:57:in "save!"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/attribute_methods/dirty.rb:29:in "save!"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:273:in "block in save!"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:329:in "block in with_transaction_returning_status"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in "block in transaction"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in "within_new_transaction"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in "transaction"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:208:in "transaction"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:326:in "with_transaction_returning_status"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:273:in "save!"
  vendor/bundle/ruby/2.0.0/bundler/gems/spree-d51a45c1c3ac/core/app/models/spree/order_contents.rb:83:in "add_to_line_item"
  vendor/bundle/ruby/2.0.0/bundler/gems/spree-d51a45c1c3ac/core/app/models/spree/order_contents.rb:10:in "add"
  vendor/bundle/ruby/2.0.0/bundler/gems/spree-d51a45c1c3ac/core/app/models/spree/order_populator.rb:37:in "attempt_cart_add"
  vendor/bundle/ruby/2.0.0/bundler/gems/spree-d51a45c1c3ac/core/app/models/spree/order_populator.rb:16:in "populate"
  vendor/bundle/ruby/2.0.0/bundler/gems/spree-d51a45c1c3ac/frontend/app/controllers/spree/orders_controller.rb:45:in "populate"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_controller/metal/implicit_render.rb:4:in "send_action"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/abstract_controller/base.rb:189:in "process_action"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_controller/metal/rendering.rb:10:in "process_action"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/abstract_controller/callbacks.rb:20:in "block in process_action"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:113:in "call"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:113:in "call"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:552:in "block (2 levels) in compile"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:502:in "call"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:502:in "call"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:86:in "run_callbacks"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/abstract_controller/callbacks.rb:19:in "process_action"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_controller/metal/rescue.rb:29:in "process_action"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_controller/metal/instrumentation.rb:32:in "block in process_action"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/notifications.rb:159:in "block in instrument"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/notifications/instrumenter.rb:20:in "instrument"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/notifications.rb:159:in "instrument"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_controller/metal/instrumentation.rb:30:in "process_action"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_controller/metal/params_wrapper.rb:250:in "process_action"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/railties/controller_runtime.rb:18:in "process_action"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/abstract_controller/base.rb:136:in "process"
  vendor/bundle/ruby/2.0.0/gems/actionview-4.1.11/lib/action_view/rendering.rb:30:in "process"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_controller/metal.rb:196:in "dispatch"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_controller/metal/rack_delegation.rb:13:in "dispatch"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_controller/metal.rb:232:in "block in action"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:82:in "call"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:82:in "dispatch"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:50:in "call"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/journey/router.rb:73:in "block in call"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/journey/router.rb:59:in "each"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/journey/router.rb:59:in "call"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:692:in "call"
  vendor/bundle/ruby/2.0.0/gems/railties-4.1.11/lib/rails/engine.rb:514:in "call"
  vendor/bundle/ruby/2.0.0/gems/railties-4.1.11/lib/rails/railtie.rb:194:in "public_send"
  vendor/bundle/ruby/2.0.0/gems/railties-4.1.11/lib/rails/railtie.rb:194:in "method_missing"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/journey/router.rb:73:in "block in call"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/journey/router.rb:59:in "each"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/journey/router.rb:59:in "call"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:692:in "call"
  vendor/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in "block in call"
  vendor/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in "catch"
  vendor/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in "call"
  vendor/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/etag.rb:23:in "call"
  vendor/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/conditionalget.rb:35:in "call"
  vendor/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/head.rb:11:in "call"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/params_parser.rb:27:in "call"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/flash.rb:254:in "call"
  vendor/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in "context"
  vendor/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in "call"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/cookies.rb:562:in "call"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/query_cache.rb:36:in "call"
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in "call"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/callbacks.rb:29:in "block in call"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:82:in "run_callbacks"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/callbacks.rb:27:in "call"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/remote_ip.rb:76:in "call"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/debug_exceptions.rb:17:in "call"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/show_exceptions.rb:30:in "call"
  vendor/bundle/ruby/2.0.0/gems/railties-4.1.11/lib/rails/rack/logger.rb:38:in "call_app"
  vendor/bundle/ruby/2.0.0/gems/railties-4.1.11/lib/rails/rack/logger.rb:20:in "block in call"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/tagged_logging.rb:68:in "block in tagged"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/tagged_logging.rb:26:in "tagged"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/tagged_logging.rb:68:in "tagged"
  vendor/bundle/ruby/2.0.0/gems/railties-4.1.11/lib/rails/rack/logger.rb:20:in "call"
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/request_id.rb:21:in "call"
  vendor/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in "call"
  vendor/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/runtime.rb:17:in "call"
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.11/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in "call"
  vendor/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/sendfile.rb:112:in "call"
  vendor/bundle/ruby/2.0.0/gems/railties-4.1.11/lib/rails/engine.rb:514:in "call"
  vendor/bundle/ruby/2.0.0/gems/railties-4.1.11/lib/rails/application.rb:144:in "call"
  passenger (4.0.53) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in "process_request"
  passenger (4.0.53) lib/phusion_passenger/request_handler/thread_handler.rb:141:in "accept_and_process_next_request"
  passenger (4.0.53) lib/phusion_passenger/request_handler/thread_handler.rb:109:in "main_loop"
  passenger (4.0.53) lib/phusion_passenger/request_handler.rb:455:in "block (3 levels) in start_threads"
```

**Comment by Koldof** [comment]
I think this is actually due to a misconfiguration in the database, so I dropped all the tables and am starting the migrations and seeds again, hopefully no issue this time.

**Comment by Koldof** [comment]
Yep, misconfiguration,
