### ISSUE TITLE
Unable to run `rails console` in production env for default app

### ISSUE THREAD

**Issue by colinrymer** [spree/spree#6581]
When trying to run `RACK_ENV=production bundle exec rails console` on a freshly installed Spree application, the app exits with an `ActiveSupport::Concern::MultipleIncludedBlocks` error.

## Steps to reproduce:

1. Install Rails 4.2.2 - `gem install rails -v 4.2.2`
2. Install spree - `gem install spree`
3. Install spree_cmd - `gem install spree_cmd`
4. Create Rails app - `rails _4.2.2_ new testapp`
5. Install spree - `spree install testapp --branch "3-0-stable"`
6. Accept all default options for spree installation
7. Navigate to Rails app - `cd testapp`
8. Run `RACK_ENV=production bundle exec rails console`

## What I Expect vs What Happens
I expect to be put into the rails console; instead the application raises an error and exits.

## Gemfile & Gemfile.lock
https://gist.github.com/colinrymer/6390d32f7f850ae9433f

## Stacktrace
```
$ RACK_ENV=production bundle exec rails c
[WARNING] You are not setting Devise.secret_key within your application!
You must set this in config/initializers/devise.rb. Here's an example:

Devise.secret_key = "0b38e4151c0edb708403a6a6d0faa2cd232cc97f6336dc53796e64540650ce248481695bc6446a66a7fa90d275edcb758e20"
Instance method "open" is already defined in Object, use generic helper instead or set StateMachines::Machine.ignore_method_conflicts = true.
/Users/colin/.gem/ruby/2.2.2/gems/activesupport-4.2.2/lib/active_support/concern.rb:126:in `included': Cannot define multiple 'included' blocks for a Concern (ActiveSupport::Concern::MultipleIncludedBlocks)
	from /Users/colin/.gem/ruby/2.2.2/bundler/gems/spree-0285c1325a8d/core/app/models/spree/order/checkout.rb:6:in `<module:Checkout>'
	from /Users/colin/.gem/ruby/2.2.2/bundler/gems/spree-0285c1325a8d/core/app/models/spree/order/checkout.rb:3:in `<class:Order>'
	from /Users/colin/.gem/ruby/2.2.2/bundler/gems/spree-0285c1325a8d/core/app/models/spree/order/checkout.rb:2:in `<module:Spree>'
	from /Users/colin/.gem/ruby/2.2.2/bundler/gems/spree-0285c1325a8d/core/app/models/spree/order/checkout.rb:1:in `<top (required)>'
	from /Users/colin/.gem/ruby/2.2.2/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:457:in `load'
	from /Users/colin/.gem/ruby/2.2.2/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /Users/colin/.gem/ruby/2.2.2/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /Users/colin/.gem/ruby/2.2.2/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:456:in `load_file'
	from /Users/colin/.gem/ruby/2.2.2/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /Users/colin/.gem/ruby/2.2.2/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:317:in `depend_on'
	from /Users/colin/.gem/ruby/2.2.2/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:233:in `require_dependency'
	from /Users/colin/.gem/ruby/2.2.2/gems/railties-4.2.2/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
	from /Users/colin/.gem/ruby/2.2.2/gems/railties-4.2.2/lib/rails/engine.rb:471:in `each'
	from /Users/colin/.gem/ruby/2.2.2/gems/railties-4.2.2/lib/rails/engine.rb:471:in `block in eager_load!'
	from /Users/colin/.gem/ruby/2.2.2/gems/railties-4.2.2/lib/rails/engine.rb:469:in `each'
	from /Users/colin/.gem/ruby/2.2.2/gems/railties-4.2.2/lib/rails/engine.rb:469:in `eager_load!'
	from /Users/colin/.gem/ruby/2.2.2/gems/railties-4.2.2/lib/rails/engine.rb:346:in `eager_load!'
	from /Users/colin/.gem/ruby/2.2.2/gems/railties-4.2.2/lib/rails/application/finisher.rb:56:in `each'
	from /Users/colin/.gem/ruby/2.2.2/gems/railties-4.2.2/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
	from /Users/colin/.gem/ruby/2.2.2/gems/railties-4.2.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/colin/.gem/ruby/2.2.2/gems/railties-4.2.2/lib/rails/initializable.rb:30:in `run'
	from /Users/colin/.gem/ruby/2.2.2/gems/railties-4.2.2/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/colin/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/colin/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/colin/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/colin/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/colin/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/colin/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/colin/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/colin/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/colin/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/colin/.gem/ruby/2.2.2/gems/railties-4.2.2/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/colin/.gem/ruby/2.2.2/gems/railties-4.2.2/lib/rails/application.rb:352:in `initialize!'
	from /private/tmp/testapp/config/environment.rb:5:in `<top (required)>'
	from /Users/colin/.gem/ruby/2.2.2/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/colin/.gem/ruby/2.2.2/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/colin/.gem/ruby/2.2.2/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/colin/.gem/ruby/2.2.2/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/colin/.gem/ruby/2.2.2/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
	from /Users/colin/.gem/ruby/2.2.2/gems/spring-1.3.6/lib/spring/application.rb:92:in `preload'
	from /Users/colin/.gem/ruby/2.2.2/gems/spring-1.3.6/lib/spring/application.rb:143:in `serve'
	from /Users/colin/.gem/ruby/2.2.2/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
	from /Users/colin/.gem/ruby/2.2.2/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
	from /Users/colin/.gem/ruby/2.2.2/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
	from /Users/colin/.gem/ruby/2.2.2/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/colin/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/colin/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by alepore** [comment]
mhh i open production rails console all the times using `bundle exec rails console production`, also using `3-0-stable`

**Comment by colinrymer** [comment]
Substituting `bundle exec rails console production` for `RACK_ENV=production bundle exec rails console` in step 8 of my steps to reproduce causes the exact same `ActiveSupport::Concern::MultipleIncludedBlocks` error.

**Comment by cedarstarr** [comment]
This PR should fix this https://github.com/spree/spree/pull/6614

**Comment by colinrymer** [comment]
Thanks, @cedarstarr!

**Comment by JackWells** [comment]
I must be missing something.  I type "spree install --auto-accept" and it does.  Then I start rails, and get "Instance method "open" is already defined in Object, use generic helper instead or set StateMachines::Machine.ignore_method_conflicts = true."
Where do I set this and/or why is the installer broken?
