### ISSUE TITLE
Duplicates States and countries after a new rake db:seed

### ISSUE THREAD

**Issue by bricesanchez** [spree/spree#6672]
Hello all !

I'm on spree edge and i asking myself why there is no uniqueness check in :
https://github.com/spree/spree/blob/master/core/app/models/spree/country.rb#L13
https://github.com/spree/spree/blob/master/core/app/models/spree/state.rb#L13

When i run `rake db:seed` the first time :

```ruby
irb(main):001:0> Spree::Zone.count
   (0.7ms)  SELECT COUNT(*) FROM "spree_zones"
=> 2
irb(main):002:0> Spree::Country.count
   (0.6ms)  SELECT COUNT(*) FROM "spree_countries"
=> 248
irb(main):003:0> Spree::State.count
   (7.2ms)  SELECT COUNT(*) FROM "spree_states"
=> 3776
````
And when i run `rake db:seed` the second time without commenting this :
```ruby
Spree::Core::Engine.load_seed if defined?(Spree::Core)
Spree::Auth::Engine.load_seed if defined?(Spree::Auth)
```
```ruby
irb(main):001:0> Spree::Zone.count
   (0.7ms)  SELECT COUNT(*) FROM "spree_zones"
=> 2
irb(main):002:0> Spree::Country.count
   (1.3ms)  SELECT COUNT(*) FROM "spree_countries"
=> 496
irb(main):003:0> Spree::State.count
   (2.5ms)  SELECT COUNT(*) FROM "spree_states"
=> 11328
```
And i've an error who kills the `rake db:seed` :
```ruby
➜  equ-001-website-2015 git:(master) ✗ rake db:seed
/Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/refinerycms-settings-10c12da53e0c/app/models/refinery/setting.rb:14: warning: already initialized constant Refinery::Setting::FORM_VALUE_TYPES
/Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/refinerycms-settings-10c12da53e0c/app/models/refinery/setting.rb:14: warning: previous definition of FORM_VALUE_TYPES was here
/Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/refinerycms-settings-10c12da53e0c/app/models/refinery/setting.rb:122: warning: already initialized constant Refinery::Setting::REPLACEMENTS
/Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/refinerycms-settings-10c12da53e0c/app/models/refinery/setting.rb:122: warning: previous definition of REPLACEMENTS was here
loading ruby /Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/spree-40125195cf15/core/db/default/spree/countries.rb
loading ruby /Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/spree-40125195cf15/core/db/default/spree/default_reimbursement_type.rb
loading ruby /Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/spree-40125195cf15/core/db/default/spree/roles.rb
loading ruby /Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/spree-40125195cf15/core/db/default/spree/states.rb
loading ruby /Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/spree-40125195cf15/core/db/default/spree/stores.rb
loading ruby /Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/spree-40125195cf15/core/db/default/spree/zones.rb
rake aborted!
ActiveRecord::RecordInvalid: La validation a échoué : Nom n'est pas disponible
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.3/lib/active_record/validations.rb:79:in `raise_record_invalid'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.3/lib/active_record/validations.rb:43:in `save!'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.3/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.3/lib/active_record/transactions.rb:291:in `block in save!'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.3/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.3/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.3/lib/active_record/transactions.rb:291:in `save!'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.3/lib/active_record/persistence.rb:51:in `create!'
/Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/spree-40125195cf15/core/db/default/spree/zones.rb:1:in `<top (required)>'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/spree-40125195cf15/core/lib/tasks/core.rake:11:in `block (2 levels) in <top (required)>'
/Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/spree-40125195cf15/core/lib/tasks/core.rake:30:in `block (3 levels) in <top (required)>'
/Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/spree-40125195cf15/core/lib/tasks/core.rake:24:in `each'
/Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/spree-40125195cf15/core/lib/tasks/core.rake:24:in `block (2 levels) in <top (required)>'
/Users/bci20/Sites/equ-001-website-2015/.gems/bundler/gems/spree-40125195cf15/core/db/seeds.rb:5:in `<top (required)>'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/railties-4.2.3/lib/rails/engine.rb:547:in `load_seed'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `public_send'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `method_missing'
/Users/bci20/Sites/equ-001-website-2015/db/seeds.rb:27:in `<top (required)>'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/railties-4.2.3/lib/rails/engine.rb:547:in `load_seed'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.3/lib/active_record/tasks/database_tasks.rb:250:in `load_seed'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activerecord-4.2.3/lib/active_record/railties/databases.rake:180:in `block (2 levels) in <top (required)>'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/bci20/Sites/equ-001-website-2015/.gems/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
-e:1:in `<main>'
Tasks: TOP => db:load_dir
(See full trace by running task with --trace)
```

**Comment by jasonfb** [comment]
why would you run ```db:seed``` a second time? Your question is based on a false premise-- a premise that it is desirable to run db:seed more than once.

**Comment by JDutil** [comment]
I agree this is expected behavior as you should only be running the seeds once.  Feel free to submit a PR making them able to be run multiple times if you'd like though.

**Comment by bricesanchez** [comment]
I have a rails app with Refinery CMS and Spree. Each time, i've to install a new Refinery CMS engine, i've to run `rake db:seed` to update the Refinery CMS pages. 

Perhaps it's the wrong way on Refinery CMS. I thought we could run `rake db:seed` more than one time.

**Comment by jasonfb** [comment]
Seems odd to me, I really only ever year of people running ```rake db:seed``` the very first time you set up a new app (and then basically never again).

@bricesanchez The db:seed surely hooks into one of Refinery's own rake tasks, maybe you just want to run that task instead of ```db:seed``` ?

**Comment by JDutil** [comment]
When I need to re-seed I do a db:reset i.e. db:drop db:create db:seed

**Comment by bricesanchez** [comment]
@jasonfb and @JDutil Thanks for your explanations :)

**Comment by parndt** [comment]
Refinery considers seeds as idempotent.. so you should be able to run `rake db:seed` as many times as you like and achieve the same result.  This allows your main application to function without interference and also allows other gems/extensions to do the same.

**Comment by mvz** [comment]
If Spree were to add things to the seed I would want to just run `rake db:seed` and add those things to my database instead of doing this manually.

**Comment by mvz** [comment]
> When I need to re-seed I do a db:reset i.e. db:drop db:create db:seed

In a production database that is not really an option.

**Comment by jasonfb** [comment]
Additional data is generally added through a migration or rake task.

I don't know why this is confusing. Like a garden, you plan "seeds" once every spring, not multiple times per year. The Rails guide (http://edgeguides.rubyonrails.org/active_record_migrations.html#migrations-and-seed-data) clearly states about seeds: "This is generally a much cleaner way to set up the database of a blank application."

All Rails app work on a common standard -- seeds are run when you have a blank database. Every Rails dev I've ever worked with has accepted this as gospel. If Refinery wants to change that they should

1) Consider an orthogonal approach to the problem and implement what they need in a way that does not impact other code. (Like, for example, they could come to their senses and realize that the word "seed" is the improper word for this and rename the rake task).

2) Consider making a pull request against Rails to change the meaning of the behavior for "seed" for the entire community. 

I can't speak to Refinery or why it is so backwards in this way, but running db:seed is done once. That how Rails app works, any other expectation is wrong and should be corrected.

**Comment by JDutil** [comment]
I have absolutely no problem with people updating the seeds so that they can be run multiple times, but I personally have no desire to spend the time to change it myself. You guys are more than welcome to submit a PR if you'd like. Open source projects move forward by people scratching their own itch, and running seeds multiple times in production simply isn't one of mine.
