### ISSUE TITLE
undefined method `bill_address_firstname_start'

### ISSUE THREAD

**Issue by mmintel** [spree/spree#6749]
Hi there,

my spree app was working fine so far but I tried to move over to another server and there changed some gems and such.. I thought its working but now when I tried to login to the backend I am getting this error... but only for /admin/orders, everything else is still working.

Do you have any idea?

```
Showing /Users/mmintel/.rvm/gems/ruby-2.1.2@zeitschild/bundler/gems/spree-cc4aa202550e/backend/app/views/spree/admin/orders/index.html.erb where line #78 raised:

undefined method `bill_address_firstname_start' for #<Ransack::Search:0x007fd63c696210>
Extracted source (around line #101):
99
100
101
102
103
104
              
        end
      else
        super
      end
    end


Rails.root: /Users/mmintel/Projekte/heroku/test/zeitschild

Application Trace | Framework Trace | Full Trace
ransack (1.4.1) lib/ransack/search.rb:101:in `method_missing'
actionview (4.2.2) lib/action_view/helpers/tags/base.rb:28:in `public_send'
actionview (4.2.2) lib/action_view/helpers/tags/base.rb:28:in `value'
actionview (4.2.2) lib/action_view/helpers/tags/base.rb:38:in `value_before_type_cast'
actionview (4.2.2) lib/action_view/helpers/tags/text_field.rb:13:in `block in render'
actionview (4.2.2) lib/action_view/helpers/tags/text_field.rb:13:in `fetch'
actionview (4.2.2) lib/action_view/helpers/tags/text_field.rb:13:in `render'
actionview (4.2.2) lib/action_view/helpers/form_helper.rb:787:in `text_field'
actionview (4.2.2) lib/action_view/helpers/form_helper.rb:1322:in `text_field'
/Users/mmintel/.rvm/gems/ruby-2.1.2@zeitschild/bundler/gems/spree-cc4aa202550e/backend/app/views/spree/admin/orders/index.html.erb:78:in `block (2 levels) in _c6bf32c34b8f88475d8be37d6a319aab'
actionview (4.2.2) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
actionview (4.2.2) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
actionview (4.2.2) lib/action_view/helpers/capture_helper.rb:38:in `capture'
actionview (4.2.2) lib/action_view/helpers/form_helper.rb:444:in `form_for'
ransack (1.4.1) lib/ransack/helpers/form_helper.rb:55:in `search_form_for'
/Users/mmintel/.rvm/gems/ruby-2.1.2@zeitschild/bundler/gems/spree-cc4aa202550e/backend/app/views/spree/admin/orders/index.html.erb:12:in `block in _c6bf32c34b8f88475d8be37d6a319aab'
actionview (4.2.2) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
actionview (4.2.2) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
actionview (4.2.2) lib/action_view/helpers/capture_helper.rb:38:in `capture'
actionview (4.2.2) lib/action_view/helpers/capture_helper.rb:152:in `content_for'
/Users/mmintel/.rvm/gems/ruby-2.1.2@zeitschild/bundler/gems/spree-cc4aa202550e/backend/app/views/spree/admin/orders/index.html.erb:9:in `_c6bf32c34b8f88475d8be37d6a319aab'
actionview (4.2.2) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.2) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.2) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.2) lib/action_view/template.rb:143:in `render'
deface (1.0.1) lib/deface/action_view_extensions.rb:41:in `render'
actionview (4.2.2) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (4.2.2) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
activesupport (4.2.2) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.2) lib/active_support/notifications.rb:164:in `instrument'
actionview (4.2.2) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
actionview (4.2.2) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (4.2.2) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (4.2.2) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (4.2.2) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (4.2.2) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (4.2.2) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (4.2.2) lib/action_view/rendering.rb:100:in `_render_template'
actionpack (4.2.2) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (4.2.2) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (4.2.2) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
actionpack (4.2.2) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
actionpack (4.2.2) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.2.2) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (4.2.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/mmintel/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
activesupport (4.2.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (4.2.2) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (4.2.2) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (4.2.2) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
actionpack (4.2.2) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.2) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.2) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.2) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.2) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.2) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.2) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.2) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.2) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.2) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.2) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:74:in `call'
actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:819:in `call'
railties (4.2.2) lib/rails/engine.rb:518:in `call'
railties (4.2.2) lib/rails/railtie.rb:194:in `public_send'
railties (4.2.2) lib/rails/railtie.rb:194:in `method_missing'
actionpack (4.2.2) lib/action_dispatch/routing/mapper.rb:51:in `serve'
actionpack (4.2.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:819:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.2) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
activerecord (4.2.2) lib/active_record/migration.rb:378:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `call'
activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `_run_callbacks'
activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.2) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.2) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
rack-zippy (3.0.1) lib/rack-zippy.rb:55:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
railties (4.2.2) lib/rails/engine.rb:518:in `call'
railties (4.2.2) lib/rails/application.rb:164:in `call'
rack-zippy (3.0.1) lib/rack-zippy.rb:55:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
/Users/mmintel/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/Users/mmintel/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
/Users/mmintel/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

**Comment by mmintel** [comment]
when I comment out these lines here it is working

```RUBY
<div class="col-md-4">
          <div class="form-group">
            <%# label_tag :q_bill_address_firstname_start, Spree.t(:first_name_begins_with) %>
            <%# f.text_field :bill_address_firstname_start, class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%# label_tag :q_bill_address_lastname_start, Spree.t(:last_name_begins_with) %>
            <%# f.text_field :bill_address_lastname_start, class: 'form-control' %>
          </div>
        </div>

**Comment by mmintel** [comment]
same happens here... http://localhost:3000/admin/users

undefined method `bill_address_firstname_cont' for #<Ransack::Search:0x007fb6045b2090>

**Comment by fabiode** [comment]
Models are using whitelist_ransackable_attributes

you should take a look at this https://github.com/spree/spree/issues/6707

**Comment by nishant-cyro** [comment]
@priyank-gupta @damianlegawiec @Mafi88 - This is working fine now. Commit https://github.com/spree/spree/commit/f7e00dc9 fixes the issue.

**Comment by Mafi88** [comment]
@nishant-cyro :+1:
