### ISSUE TITLE
Cannot run install:migration while upgrading 2-4-stable to 3-0-stable

### ISSUE THREAD

**Issue by nxia416** [spree/spree#6904]
I am trying to upgrade my spree2.4 project to spree3. However, while trying to following the upgrade tips, I got the following error when I tried to run "rake railties:install:migrations":

```
/Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/override.rb:60:in `initialize': :action is invalid (ArgumentError)
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/dsl/context.rb:15:in `new'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/dsl/context.rb:15:in `create_override'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/dsl/loader.rb:56:in `build_context_and_extract_dsl_from'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/dsl/loader.rb:37:in `build_erb_context'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/dsl/loader.rb:27:in `build_context'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/dsl/loader.rb:22:in `block in load'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/dsl/loader.rb:17:in `open'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/dsl/loader.rb:17:in `load'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/environment.rb:102:in `block (2 levels) in enumerate_and_load'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/environment.rb:101:in `glob'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/environment.rb:101:in `block in enumerate_and_load'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/environment.rb:91:in `each'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/environment.rb:91:in `enumerate_and_load'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/environment.rb:85:in `load_overrides'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/environment.rb:68:in `block in load_all'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/environment.rb:66:in `each'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/environment.rb:66:in `load_all'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/deface-1.0.2/lib/deface/railtie.rb:12:in `activate'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:446:in `instance_exec'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:446:in `block in make_lambda'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:192:in `call'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:192:in `block in simple'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `call'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `block in call'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `each'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `call'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/nxia/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/nxia/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/nxia/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/nxia/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/nxia/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/nxia/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/nxia/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/nxia/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/nxia/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
	from /Users/nxia/Projects/rails_projects/project_beat_shop_spree3/config/environment.rb:5:in `<top (required)>'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/spring-1.6.1/lib/spring/application.rb:92:in `preload'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/spring-1.6.1/lib/spring/application.rb:143:in `serve'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/spring-1.6.1/lib/spring/application.rb:131:in `block in run'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/spring-1.6.1/lib/spring/application.rb:125:in `loop'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/spring-1.6.1/lib/spring/application.rb:125:in `run'
	from /Users/nxia/.rvm/gems/ruby-2.2.3/gems/spring-1.6.1/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/nxia/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/nxia/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

I tried ruby 2.1 and 2.2.3, but still got the same problem.

Here is my Gem file:
```
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
# gem 'rails', '4.1.11'
gem 'rails', '~> 4.2.0'

# Use sqlite3 as the database for Active Record
# gem 'sqlite3'
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails' #, '~> 4.0.3'
gem 'sass', '~> 3.4.20'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier'#, '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'#, '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc'#, '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring', '~> 1.6.1' #,        group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]


# gem 'spree', github: 'spree/spree', branch: '2-4-stable'
gem 'spree', github: 'spree/spree', branch: '3-0-stable'


# gem 'spree_gateway', github: 'spree/spree_gateway', branch: '2-4-stable'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'

# gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '2-4-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'

# gem 'spree_fancy', :github => 'spree/spree_fancy', :branch => '2-4-stable'

# gem 'spree_variant_options', :git => 'git://github.com/nxia416/spree_variant_options.git', :branch => "2-4-stable"
# https://github.com/redglory/spree_variant_options.git
gem 'spree_variant_options', :git => 'git://github.com/redglory/spree_variant_options.git', :branch => "3-0-stable"


## 
# gem 'spree_social_products', github: 'spree-contrib/spree_social_products', branch: '2-4-stable'
gem 'spree_social_products', github: 'spree-contrib/spree_social_products', branch: '3-0-stable'
# gem 'spree_reviews', github: 'spree-contrib/spree_reviews', branch: '2-4-stable'
gem 'spree_reviews', github: 'spree-contrib/spree_reviews', branch: '3-0-stable'
# gem 'spree_paypal_express', github: 'spree-contrib/better_spree_paypal_express', branch: '2-4-stable'
gem 'spree_paypal_express', github: 'spree-contrib/better_spree_paypal_express', branch: '3-0-stable'
# gem 'spree_social', github: 'spree-contrib/spree_social', branch: '2-4-stable'
gem 'spree_social', github: 'spree-contrib/spree_social', branch: '3-0-stable'
# gem 'spree_contact_us', github: 'spree-contrib/spree_contact_us', branch: '2-4-stable'
gem 'spree_contact_us', github: 'spree-contrib/spree_contact_us', branch: '3-0-stable'

# gem 'spree_mail_settings', github: 'spree-contrib/spree_mail_settings', branch: '2-4-stable'
gem 'spree_mail_settings', github: 'spree-contrib/spree_mail_settings', branch: '3-0-stable'
gem "omniauth-paypal", '~> 1.3.0'

## Deployment

group :production do
  gem 'unicorn'
  gem 'unicorn-rails'
  gem 'capistrano3-unicorn'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
end


gem "font-awesome-rails"

gem 'web-console', '~> 2.0'
gem 'responders', '~> 2.0' 
```

**Comment by nxia416** [comment]
Fixed. Turned out the problem was caused by gem 'spring'.

**Comment by siddharth28** [comment]
@nxia416 not able to replicate this issue.
Can you please share some more details.

Just tried upgrade from
`gem 'spree', github: 'spree/spree', tag: 'v2.4.9'
gem 'spree_mail_settings', github: 'spree-contrib/spree_mail_settings', branch: '2-4-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '2-4-stable'
gem 'spree_social', github: 'spree-contrib/spree_social', branch: '2-4-stable'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '2-4-stable'`
to 
`gem 'spree', github: 'spree/spree', tag: 'v3.0.5'
gem 'spree_mail_settings', github: 'spree-contrib/spree_mail_settings', branch: '3-0-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'
gem 'spree_social', github: 'spree-contrib/spree_social', branch: '3-0-stable'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'`

**Comment by Mafi88** [comment]
I also can't replicate this problem. I used your Gemfile:
-  uncommented rails 4.1.11, spree 2-4 versions and commented responders
- chagned rails to 4.2.0, spree to 3-0 and uncommented responders
- ran ```bundle update spree```
- ran ```rake railties:install:migrations```

and it worked correctly. From the error message you provided, it seems there is a problem with deface version

Could you please check your deface version in (Gemfile lock), and update it to ```deface (1.0.2)``` if it's in different version?

Please let me know if it helped.
