### ISSUE TITLE
spree install --auto-accept gives an error  undefined method `this' for #<Gem::Specification:0x4218fd2 activesupport-4.2.5.1

### ISSUE THREAD

**Issue by linklee** [spree/spree#7104]
followed instructions here https://guides.spreecommerce.com/developer/getting_started_tutorial.html 
And get this error

```
jonstark@jonstark-pc:~/rails_projects$ spree install --auto-accept
/home/jonstark/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x4218fd2 activesupport-4.2.5.1> (NoMethodError)
	from /home/jonstark/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /home/jonstark/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /home/jonstark/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/string.rb:1:in `<top (required)>'
	from /home/jonstark/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /home/jonstark/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /home/jonstark/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/jonstark/.rvm/gems/ruby-2.3.0/gems/spree_cmd-3.0.6.1/lib/spree_cmd/installer.rb:2:in `<top (required)>'
	from /home/jonstark/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/jonstark/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/jonstark/.rvm/gems/ruby-2.3.0/gems/spree_cmd-3.0.6.1/lib/spree_cmd.rb:13:in `<top (required)>'
	from /home/jonstark/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/jonstark/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/jonstark/.rvm/gems/ruby-2.3.0/gems/spree_cmd-3.0.6.1/bin/spree:2:in `<top (required)>'
	from /hme/jonstark/.rvm/gems/ruby-2.3.0/bin/spree:23:in `load'
	from /home/jonstark/.rvm/gems/ruby-2.3.0/bin/spree:23:in `<main>'
	from /home/jonstark/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/jonstark/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

```
My gemfile

```
#Gemfile
source 'https://rubygems.org'
ruby '2.3.0'
gem 'rails', '4.2.5' #-> Bumped the version
gem 'sprockets-rails' #-> this will add the latest version

gem 'bcrypt-ruby', '~> 3.1.2'
gem 'sqlite3'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :development, :test do
  gem 'rspec-rails', '~> 2.0'
  gem "factory_girl_rails", "~> 4.0"
end

group :test do
  gem 'capybara', '~> 2.1.0'
  gem "capybara-email", "~> 2.2.0"
  gem 'shoulda-matchers', '~> 2.4.0'
end

```
Please help!

**Comment by aishmita-aggarwal** [comment]
I can replicate this on master.

**Comment by aishmita-aggarwal** [comment]
@linklee This is a rubygems issue(https://github.com/rubygems/rubygems/issues/1420).

**Comment by orenf** [comment]
@tenderlove's patch should fix this.

**Comment by parhs** [comment]
heroku fixed this. Propably a sree specific fix would be better.

**Comment by orenf** [comment]
Looks like the fix for this in RubyGems has been merged.

https://github.com/rubygems/rubygems/commit/708d9d83f6894b3ac30a02b4c976c6c7899d97ce

**Comment by parhs** [comment]
So we should wait for 2.6.3 ...
