### ISSUE TITLE
Mysql2 Error when migrating

### ISSUE THREAD

**Issue by thiagotonon** [spree/spree#7179]
This error is occurring every time that i try to run spree migrations from scratch

```
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INDEX `index_spree_products_on_permalink` TO `index_spree_products_on_slug`' at line 1: ALTER TABLE `spree_products` RENAME INDEX `index_spree_products_on_permalink` TO `index_spree_products_on_slug`/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `block in execute'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `execute'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:497:in `rename_index'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:994:in `block in rename_column_indexes'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:988:in `each'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:988:in `rename_column_indexes'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:524:in `rename_column'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:662:in `block in method_missing'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in `block in say_with_time'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in `say_with_time'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:652:in `method_missing'
/Users/rdscodes_a1/Documents/!development/web/nosvd/db/migrate/20160201190362_rename_permalink_to_slug_for_products.spree.rb:5:in `change'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:606:in `exec_migration'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:589:in `block in migrate'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:588:in `migrate'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:765:in `migrate'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:1043:in `ddl_transaction'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:956:in `block in migrate'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:952:in `each'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:952:in `migrate'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:820:in `up'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:798:in `migrate'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.2/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/rdscodes_a1/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

what i trying to run is

`rake db:drop db:create db:migrate`

Here is my Gemfile:
```

source 'https://rubygems.org'

gem 'rails', '4.2.2'
gem 'mysql2', '0.3.18'
gem 'sass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'compass-rails'

gem 'mail_form'
gem 'formtastic'
gem 'carrierwave'

gem 'mechanize'

gem 'unicorn'
gem 'unicorn-worker-killer'

gem 'non-stupid-digest-assets'
gem 'paper_trail'
gem 'enumerize'

gem 'acts_as_tenant', github: 'henriquenm/acts_as_tenant'

gem 'spree', branch: '3-0-stable'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
gem 'spree_i18n', github: 'thiagotonon/spree_i18n', branch: '3-0-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'
gem 'spree_autosuggest', github: 'evrone/spree_autosuggest'

gem 'omniauth-facebook'
gem 'redactor-rails'

group :development do
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'capistrano-bundler'
  gem 'capistrano-unicorn-nginx'
  gem 'capistrano-db-tasks', require: false
end

group :development, :test do
  gem 'annotate'
  gem 'awesome_print'
  gem 'byebug'
  gem 'hirb-unicode'
  gem 'letter_opener'
  gem 'magic_encoding'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'spring'
  gem 'web-console', '~> 2.0'
end
```

Thanks for help

**Comment by priyank-gupta** [comment]
@thiagotonon What's your MySQL version ?

**Comment by thiagotonon** [comment]
@priyank-gupta my MySQL version is stable 5.7.11 which was installed using brew

I'm using the gem mysql2 on 0.3.18

**Comment by thiagotonon** [comment]
Apparently my problem was solved by upgrading mysql version

For those who are facing this problem, [this might help](http://stackoverflow.com/a/33262719/5024577)

Closing the issue, thanks.
