### ISSUE TITLE
Spree Install Fatal Error.

### ISSUE THREAD

**Issue by BraydonG** [spree/spree#7380]
I'm having a problem

My current problem is running `$ spree install`
This issue is related to:

  - [X] Other

Here are my current details:

```
$ spree install
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x117c608 activesupport-4.2.5> (NoMethodError)
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/core_ext/string.rb:1:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/spree_cmd-3.0.9/lib/spree_cmd/installer.rb:2:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/spree_cmd-3.0.9/lib/spree_cmd.rb:13:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/spree_cmd-3.0.9/bin/spree:2:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/spree:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/spree:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by BraydonG** [comment]
I'm running an ubuntu/UNIX VM.

**Comment by damianlegawiec** [comment]
@BraydonG this is a RubyGems issue https://github.com/rubygems/rubygems/issues/1420 - please update it to at least `2.6.3`
