### ISSUE TITLE
uninitialized constant CreateDataMigrations::SeedMigration - migration canceled 

### ISSUE THREAD

**Issue by joshRpowell** [spree/spree#7465]
We get the following when migrating on a production environment on an existing rails app:
```
StandardError: An error has occurred, this and all later migrations canceled:

uninitialized constant CreateDataMigrations::SeedMigration

/app/db/migrate/20160502153354_create_data_migrations.seed_migration.rb:4:in 'up'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:611:in 'exec_migration'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:592:in 'block (2 levels) in migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:591:in 'block in migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in 'with_connection'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:590:in 'migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:768:in 'migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:998:in 'block in execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:1044:in 'block in ddl_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in 'block in transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:184:in 'within_new_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in 'transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in 'transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:1044:in 'ddl_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:997:in 'execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:959:in 'block in migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:955:in 'each'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:955:in 'migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:823:in 'up'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:801:in 'migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/tasks/database_tasks.rb:137:in 'migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/railties/databases.rake:44:in 'block (2 levels) in <top (required)>'
NameError: uninitialized constant CreateDataMigrations::SeedMigration
/app/db/migrate/20160502153354_create_data_migrations.seed_migration.rb:4:in 'up'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:611:in 'exec_migration'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:592:in 'block (2 levels) in migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:591:in 'block in migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in 'with_connection'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:590:in 'migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:768:in 'migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:998:in 'block in execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:1044:in 'block in ddl_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in 'block in transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:184:in 'within_new_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in 'transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in 'transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:1044:in 'ddl_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:997:in 'execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:959:in 'block in migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:955:in 'each'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:955:in 'migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:823:in 'up'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:801:in 'migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/tasks/database_tasks.rb:137:in 'migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/railties/databases.rake:44:in 'block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
```

This is the referenced migration file: 
```ruby
# This migration comes from seed_migration (originally 20140310150145)
class CreateDataMigrations < ActiveRecord::Migration
  def up
    create_table SeedMigration.migration_table_name do |t|
      t.string :version
      t.integer :runtime
      t.datetime :migrated_on
    end
  end

  def down
    drop_table SeedMigration.migration_table_name
  end
end
```

We got around the error locally by dropping and rebuilding the DB. 

We couldn't find any reference in the repo.  

Any suggestion on how to troubleshoot / solve this issue?

**Comment by joshRpowell** [comment]
unrelated to spree
