### ISSUE TITLE
Rails 5 w/ Edge: cannot load such file -- coffee_script

### ISSUE THREAD

**Issue by hhff** [spree/spree#7578]
Steps to reproduce:

1. `rails new my_app -d postgresql`

2. Add to Gemfile:

```
gem 'spree', github: 'spree/spree'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise'
gem 'spree_gateway', github: 'spree/spree_gateway'
```

3. `rails g spree:install --user_class=Spree::User --sample=false --seed=false`

Error:

```
/Users/hhff/.rvm/gems/ruby-2.3.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': cannot load such file -- coffee_script (LoadError)
	from /Users/hhff/.rvm/gems/ruby-2.3.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/hhff/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/hhff/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/hhff/.rvm/gems/ruby-2.3.1@global/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/hhff/.rvm/gems/ruby-2.3.1/bundler/gems/spree_auth_devise-56f3fe203c14/lib/spree_auth_devise.rb:4:in `<top (required)>'
	from /Users/hhff/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.1/lib/bundler/runtime.rb:91:in `require'
	from /Users/hhff/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.1/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
	from /Users/hhff/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.1/lib/bundler/runtime.rb:86:in `each'
	from /Users/hhff/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.1/lib/bundler/runtime.rb:86:in `block in require'
	from /Users/hhff/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.1/lib/bundler/runtime.rb:75:in `each'
	from /Users/hhff/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.1/lib/bundler/runtime.rb:75:in `require'
	from /Users/hhff/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.1/lib/bundler.rb:106:in `require'
	from /Users/hhff/dev/SC/pipe/RailsCode/pipe_mv/config/application.rb:17:in `<top (required)>'
	from /Users/hhff/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:82:in `require'
	from /Users/hhff/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:82:in `preload'
	from /Users/hhff/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:143:in `serve'
	from /Users/hhff/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
	from /Users/hhff/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
	from /Users/hhff/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
	from /Users/hhff/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/hhff/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/hhff/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

Any thoughts?  Thanks all!

**Comment by hhff** [comment]
Ah, this was a weird thing due to me moving some files around.  Everything's fine here!

**Comment by jnorkus** [comment]
Hey I know this was a while ago but I'm having exactly the same problem and spent last night fighting this. Any chance you remember what the reason or the fix was?

**Comment by jeromedalbert** [comment]
Had the same issue and found this issue on Google. It is because there is a coffee file somewhere in the project. I couldn't find any when using my editor global search, but when using `find . -name "*.coffee"`, it found some coffee files (for me it was in the node_modules folder, and this folder was in `Rails.application.config.assets.paths` as a configuration of `assets.rb`, so I just removed that line).

**Comment by swillits** [comment]
For Google search posterity, I had this issue, removed the coffee files and it was still a problem. I needed to kill the cache with: `rake tmp:cache:clear`

**Comment by Blake-LeBlanc** [comment]
> For Google search posterity, I had this issue, removed the coffee files and it was still a problem. I needed to kill the cache with: `rake tmp:cache:clear`

Thank you for the posterity tip @swillits , that did the trick on my end too!
