### ISSUE TITLE
Errors when Creating Extension

### ISSUE THREAD

**Issue by ignaciosm** [spree/spree#7633]
Hi,
I'm new to rails ....I am getting an error everytime I try to follow the tutorial on creating a new extension (sorry if this is a stupid question):

After creating successfully a fresh copy of Spree from the tutotial using RVM I get this:

```
ism:cuy ignacio$ cd ..
ism:cuyspree ignacio$ spree extension simple_sales
      create  spree_simple_sales
      create  spree_simple_sales/app
      create  spree_simple_sales/app/assets/javascripts/spree/backend/spree_simple_sales.js
      create  spree_simple_sales/app/assets/javascripts/spree/frontend/spree_simple_sales.js
      create  spree_simple_sales/app/assets/stylesheets/spree/backend/spree_simple_sales.css
      create  spree_simple_sales/app/assets/stylesheets/spree/frontend/spree_simple_sales.css
      create  spree_simple_sales/lib
      create  spree_simple_sales/lib/spree_simple_sales.rb
      create  spree_simple_sales/lib/spree_simple_sales/engine.rb
      create  spree_simple_sales/lib/spree_simple_sales/factories.rb
      create  spree_simple_sales/lib/generators/spree_simple_sales/install/install_generator.rb
      create  spree_simple_sales/bin
      create  spree_simple_sales/bin/rails
      create  spree_simple_sales/spree_simple_sales.gemspec
      create  spree_simple_sales/Gemfile
      create  spree_simple_sales/.gitignore
      create  spree_simple_sales/LICENSE
      create  spree_simple_sales/Rakefile
      create  spree_simple_sales/README.md
      create  spree_simple_sales/config/routes.rb
      create  spree_simple_sales/config/locales/en.yml
      create  spree_simple_sales/.rspec
      create  spree_simple_sales/spec/spec_helper.rb

        ********************************************************************************

        Your extension has been generated with a gemspec dependency on Spree 3.1.0.

        For more information on the versioning of Spree.
        See https://guides.spreecommerce.com/developer/extensions_tutorial.html#versioning-your-extension

        ********************************************************************************
```

```
ism:cuyspree ignacio$ cd spree_simple_sales
ism:spree_simple_sales ignacio$ bundle exec rails g migration add_sale_price_to_spree_variants sale_price:decimal
The git source git://github.com/spree/spree.git is not yet checked out. Please run `bundle install` before trying to start your application
ism:spree_simple_sales ignacio$ bundle install
The git source `git://github.com/spree/spree.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/spree/spree_auth_devise.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/spree/spree.git
Fetching git://github.com/spree/spree_auth_devise.git
You have one or more invalid gemspecs that need to be fixed.
The gemspec at
/Users/ignacio/Coding/cuyspree/spree_simple_sales/spree_simple_sales.gemspec is
not valid. Please fix this gemspec.
The validation error was 'authors may not be empty'
ism:spree_simple_sales ignacio$ subl .
ism:spree_simple_sales ignacio$ bundle install
The git source `git://github.com/spree/spree.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/spree/spree_auth_devise.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/spree/spree.git
Fetching git://github.com/spree/spree_auth_devise.git
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies......................................
```

```
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    rspec-rails (~> 3.4) was resolved to 3.4.0, which depends on
      railties (< 4.3, >= 3.0) was resolved to 4.0.0, which depends on
        actionpack (= 3.0.0)

    sass-rails (~> 5.0.0) was resolved to 5.0.0, which depends on
      railties (< 5.0, >= 4.0.0) was resolved to 4.0.0, which depends on
        actionpack (= 4.0.0)

    rspec-rails (~> 3.4) was resolved to 3.4.0, which depends on
      actionpack (< 4.3, >= 3.0)
Bundler could not find compatible versions for gem "activemodel":
  In Gemfile:
    rspec-rails (~> 3.4) was resolved to 3.4.0, which depends on
      railties (< 4.3, >= 3.0) was resolved to 3.0.1, which depends on
        actionpack (= 3.0.1) was resolved to 3.0.1, which depends on
          activemodel (= 3.0.1)

    rspec-rails (~> 3.4) was resolved to 3.4.0, which depends on
      actionpack (< 4.3, >= 3.0) was resolved to 3.0.1, which depends on
        activemodel (= 3.0.0)
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    spree was resolved to 3.2.0.beta1, which depends on
spree_frontend (= 3.2.0.beta1) was resolved to 3.2.0.beta1, which depends
on
        canonical-rails (~> 0.1.0) was resolved to 0.1.0, which depends on
          rails (< 5.1, >= 3.1) was resolved to 5.0.0, which depends on
            activerecord (= 4.2.6)

    spree was resolved to 3.2.0.beta1, which depends on
      spree_core (= 3.2.0.beta1) was resolved to 3.2.0.beta1, which depends on
        rails (~> 5.0.0) was resolved to 5.0.0, which depends on
          activerecord (= 5.0.0)
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    rspec-rails (~> 3.4) was resolved to 3.4.0, which depends on
      actionpack (< 4.3, >= 3.0) was resolved to 4.0.0, which depends on
        activesupport (= 3.0.0)

    rspec-rails (~> 3.4) was resolved to 3.4.0, which depends on
      railties (< 4.3, >= 3.0) was resolved to 4.0.0, which depends on
        activesupport (= 4.0.0)

    rspec-rails (~> 3.4) was resolved to 3.4.0, which depends on
      railties (< 4.3, >= 3.0) was resolved to 4.0.0, which depends on
        activesupport (= 4.0.0)

    rspec-rails (~> 3.4) was resolved to 3.4.0, which depends on
      activesupport (< 4.3, >= 3.0)
```

```
ism:spree_simple_sales ignacio$ gem list

*** LOCAL GEMS ***

actionmailer (4.2.6)
actionpack (4.2.6)
actionview (4.2.6)
activejob (4.2.6)
activemerchant (1.49.0)
activemodel (4.2.6)
activerecord (4.2.6)
activesupport (4.2.6)
acts_as_list (0.7.2)
addressable (2.4.0)
arel (6.0.3)
autoprefixer-rails (6.5.1)
awesome_nested_set (3.0.3)
bcrypt (3.1.11)
bigdecimal (default: 1.2.8)
binding_of_caller (0.7.2)
bootstrap-sass (3.3.7)
builder (3.2.2)
bundler (1.13.5)
bundler-unload (1.0.2)
byebug (9.0.6)
camertron-eprun (1.1.1)
cancancan (1.10.1)
canonical-rails (0.0.11)
carmen (1.0.2)
cldr-plurals-runtime-rb (1.0.1)
climate_control (0.0.3)
cocaine (0.5.8)
coffee-rails (4.1.1)
coffee-script (2.4.1)
coffee-script-source (1.10.0)
colorize (0.8.1)
concurrent-ruby (1.0.2)
css_parser (1.4.5)
debug_inspector (0.0.2)
deface (1.0.2)
devise (3.5.10)
devise-encryptable (0.1.2)
did_you_mean (1.0.0)
erubis (2.7.0)
execjs (2.7.0)
executable-hooks (1.3.2)
ffaker (2.2.0)
font-awesome-rails (4.6.3.1)
friendly_id (5.1.0)
gem-wrappers (1.2.7)
globalid (0.3.7)
highline (1.6.21)
htmlentities (4.3.4)
i18n (0.7.0)
io-console (default: 0.4.5)
jbuilder (2.6.0)
jquery-rails (4.2.1)
jquery-ui-rails (5.0.5)
json (default: 1.8.3)
kaminari (0.17.0)
loofah (2.0.3)
mail (2.6.4)
mime-types (3.1)
mime-types-data (3.2016.0521)
mimemagic (0.3.0)
mini_portile2 (2.1.0)
minitest (5.9.1, 5.8.3)
monetize (1.4.0)
money (6.7.1)
multi_json (1.12.1)
net-telnet (0.1.1)
nokogiri (1.6.8.1)
orm_adapter (0.5.0)
paperclip (4.3.7)
paranoia (2.1.5)
polyamorous (1.3.1)
polyglot (0.3.5)
power_assert (0.2.6)
premailer (1.8.7)
premailer-rails (1.9.4)
psych (default: 2.0.17)
rabl (0.12.0)
rack (1.6.4)
rack-test (0.6.3)
rails (4.2.6)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.3)
railties (4.2.6)
rake (11.3.0, 10.4.2)
ransack (1.4.1)
rdoc (4.2.2, default: 4.2.1)
responders (2.3.0)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
sass (3.4.22)
sass-rails (5.0.6)
sdoc (0.4.2)
select2-rails (3.5.9.1)
sixarm_ruby_unaccent (1.1.1)
spree (3.1.0)
spree_api (3.1.0)
spree_auth_devise (3.1.0)
spree_backend (3.1.0)
spree_cmd (3.1.0)
spree_core (3.1.0)
spree_frontend (3.1.0)
spree_gateway (3.1.0)
spree_sample (3.1.0)
spring (2.0.0)
sprockets (3.7.0)
sprockets-rails (3.2.0)
sqlite3 (1.3.12)
state_machines (0.4.0)
state_machines-activemodel (0.4.0)
state_machines-activerecord (0.4.0)
stringex (2.6.1)
test-unit (3.1.5)
thor (0.19.1)
thread_safe (0.3.5)
tilt (2.0.5)
truncate_html (0.9.3)
turbolinks (5.0.1)
turbolinks-source (5.0.0)
twitter_cldr (3.5.0)
tzinfo (1.2.2)
uglifier (3.0.2)
versioncake (2.3.1)
warden (1.2.6)
web-console (2.3.0)
ism:spree_simple_sales ignacio$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

My Gemfile:

```
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

gem 'spree', '~> 3.1.0.rc1'
gem 'spree_auth_devise', '~> 3.1.0.rc1'
gem 'spree_gateway', '~> 3.1.0.rc1'
```

Please help! Thanks

**Comment by tanmay3011** [comment]
@ignaciosm Working on a fix for this issue. Will raise a PR soon

**Comment by ignaciosm** [comment]
Great, thanks!

**Comment by ignaciosm** [comment]
@tanmay3011 still get this:
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (= 4.2.6)

    spree was resolved to 3.1.1, which depends on
      spree_frontend (= 3.1.1) was resolved to 3.1.1, which depends on
        canonical-rails (~> 0.0.4) was resolved to 0.0.11, which depends on
          rails (< 5.0, >= 3.1)

    spree was resolved to 3.1.1, which depends on
      spree_core (= 3.1.1) was resolved to 3.1.1, which depends on
        rails (~> 4.2.7.1)

My Gemfile:
gem 'spree', github: 'spree/spree', branch: '3-1-stable'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-1-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-1-stable'

Any ideas?

**Comment by tanmay3011** [comment]
@ignaciosm `s.add_dependency 'rails', '~> 4.2.7.1'`, In spree_core rails has been locked down to 4.2.7.1
Please update your rails version to 4.2.7.1 that might resolve this issue.

**Comment by ignaciosm** [comment]
Now I can't create the "spree_simple_sales" extension
```
ism:spree1 ignacio$ spree extension simple_sales
/Users/ignacio/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'spree_cmd' (>= 0.a) among 120 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/ignacio/.rvm/gems/ruby-2.3.1@spree1:/Users/ignacio/.rvm/gems/ruby-2.3.1@global', execute `gem env` for more information
	from /Users/ignacio/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /Users/ignacio/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /Users/ignacio/.rvm/gems/ruby-2.3.1@spree1/bin/spree:22:in `<main>'
	from /Users/ignacio/.rvm/gems/ruby-2.3.1@spree1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ignacio/.rvm/gems/ruby-2.3.1@spree1/bin/ruby_executable_hooks:15:in `<main>'
```
`ism:spree1 ignacio$ rails -v
Rails 4.2.7.1`
`ism:spree1 ignacio$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
ism:spree1 ignacio$ `

My gem list:
```
ism:spree1 ignacio$ gem list

*** LOCAL GEMS ***

actionmailer (4.2.7.1)
actionpack (4.2.7.1)
actionview (4.2.7.1)
activejob (4.2.7.1)
activemerchant (1.49.0)
activemodel (4.2.7.1)
activerecord (4.2.7.1)
activesupport (4.2.7.1)
acts_as_list (0.7.2)
addressable (2.4.0)
arel (6.0.3)
autoprefixer-rails (6.5.1)
awesome_nested_set (3.0.3)
bcrypt (3.1.11)
bigdecimal (1.2.8)
binding_of_caller (0.7.2)
bootstrap-sass (3.3.7)
builder (3.2.2)
bundler (1.13.5)
bundler-unload (1.0.2)
byebug (9.0.6)
camertron-eprun (1.1.1)
cancancan (1.10.1)
canonical-rails (0.0.11)
carmen (1.0.2)
cldr-plurals-runtime-rb (1.0.1)
climate_control (0.0.3)
cocaine (0.5.8)
coffee-rails (4.1.1)
coffee-script (2.4.1)
coffee-script-source (1.10.0)
colorize (0.8.1)
concurrent-ruby (1.0.2)
css_parser (1.4.6)
debug_inspector (0.0.2)
deface (1.0.2)
devise (3.5.10)
devise-encryptable (0.1.2)
did_you_mean (1.0.0)
erubis (2.7.0)
execjs (2.7.0)
executable-hooks (1.3.2)
ffaker (2.2.0)
font-awesome-rails (4.6.3.1)
friendly_id (5.1.0)
gem-wrappers (1.2.7)
globalid (0.3.7)
highline (1.6.21)
htmlentities (4.3.4)
i18n (0.7.0)
io-console (0.4.5)
jbuilder (2.6.0)
jquery-rails (4.2.1)
jquery-ui-rails (5.0.5)
json (1.8.3)
kaminari (0.17.0)
loofah (2.0.3)
mail (2.6.4)
mime-types (3.1)
mime-types-data (3.2016.0521)
mimemagic (0.3.0)
mini_portile2 (2.1.0)
minitest (5.9.1, 5.8.3)
monetize (1.4.0)
money (6.7.1)
multi_json (1.12.1)
net-telnet (0.1.1)
nokogiri (1.6.8.1)
orm_adapter (0.5.0)
paperclip (4.3.7)
paranoia (2.1.5)
polyamorous (1.3.1)
polyglot (0.3.5)
power_assert (0.2.6)
premailer (1.8.7)
premailer-rails (1.9.4)
psych (2.0.17)
rabl (0.12.0)
rack (1.6.4)
rack-test (0.6.3)
rails (4.2.7.1)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.3)
railties (4.2.7.1)
rake (11.3.0, 10.4.2)
ransack (1.4.1)
rdoc (4.2.2, 4.2.1)
responders (2.3.0)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
sass (3.4.22)
sass-rails (5.0.6)
sdoc (0.4.2)
select2-rails (3.5.9.1)
sixarm_ruby_unaccent (1.1.1)
spring (2.0.0)
sprockets (3.7.0)
sprockets-rails (3.2.0)
sqlite3 (1.3.12)
state_machines (0.4.0)
state_machines-activemodel (0.4.0)
state_machines-activerecord (0.4.0)
stringex (2.6.1)
test-unit (3.1.5)
thor (0.19.1)
thread_safe (0.3.5)
tilt (2.0.5)
truncate_html (0.9.3)
turbolinks (5.0.1)
turbolinks-source (5.0.0)
twitter_cldr (3.6.0)
tzinfo (1.2.2)
uglifier (3.0.2)
versioncake (2.3.1)
warden (1.2.6)
web-console (2.3.0)
```

My Gemfile:
```
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.7.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

gem 'spree', github: 'spree/spree', branch: '3-1-stable'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-1-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-1-stable'
```
My gem env
```
ism:spree1 ignacio$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/ignacio/.rvm/gems/ruby-2.3.1@spree1
  - USER INSTALLATION DIRECTORY: /Users/ignacio/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /Users/ignacio/.rvm/rubies/ruby-2.3.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/ignacio/.rvm/gems/ruby-2.3.1@spree1/bin
  - SPEC CACHE DIRECTORY: /Users/ignacio/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/ignacio/.rvm/rubies/ruby-2.3.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /Users/ignacio/.rvm/gems/ruby-2.3.1@spree1
     - /Users/ignacio/.rvm/gems/ruby-2.3.1@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/ignacio/.rvm/gems/ruby-2.3.1@spree1/bin
     - /Users/ignacio/.rvm/gems/ruby-2.3.1@global/bin
     - /Users/ignacio/.rvm/rubies/ruby-2.3.1/bin
     - /Users/ignacio/.rvm/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Users/ignacio/.rvm/bin
```
