### ISSUE TITLE
Error while reverting migration AddDiscontinuedToProductsAndVariants

### ISSUE THREAD

**Issue by deepakm-webonise** [spree/spree#7679]
I am getting error while reverting this migration 

rake db:migrate:down VERSION=20161109154178
        
    == 20161109154178 AddDiscontinuedToProductsAndVariants: reverting =============
    -- execute("UPDATE `spree_products` SET `deleted_at` = `discontinue_on` WHERE `deleted_at` IS NULL")
    rake aborted!
    StandardError: An error has occurred, this migration was canceled:

    PG::SyntaxError: ERROR:  syntax error at or near "`"
    LINE 1: UPDATE `spree_products` SET `deleted_at` = `discontinue_on` ...
                   ^
    : UPDATE `spree_products` SET `deleted_at` = `discontinue_on` WHERE `deleted_at` IS NULL
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:665:in `block in method_missing'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `block in say_with_time'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `say_with_time'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:654:in `method_missing'
    /home/deepak/workspace/Project/db/migrate/20161109154178_add_discontinued_to_products_and_variants.spree.rb:63:in `down'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:611:in `exec_migration'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:591:in `block in migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:590:in `migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:768:in `migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1044:in `ddl_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:942:in `run'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:834:in `run'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:90:in `block (3 levels) in <top (required)>'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
    /home/deepak/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
    /home/deepak/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
    ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "`"
    LINE 1: UPDATE `spree_products` SET `deleted_at` = `discontinue_on` ...
                   ^
    : UPDATE `spree_products` SET `deleted_at` = `discontinue_on` WHERE `deleted_at` IS NULL
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:665:in `block in method_missing'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `block in say_with_time'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `say_with_time'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:654:in `method_missing'
    /home/deepak/workspace/Project/db/migrate/20161109154178_add_discontinued_to_products_and_variants.spree.rb:63:in `down'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:611:in `exec_migration'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:591:in `block in migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:590:in `migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:768:in `migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1044:in `ddl_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:942:in `run'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:834:in `run'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:90:in `block (3 levels) in <top (required)>'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
    /home/deepak/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
    /home/deepak/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
    PG::SyntaxError: ERROR:  syntax error at or near "`"
    LINE 1: UPDATE `spree_products` SET `deleted_at` = `discontinue_on` ...
                   ^
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:665:in `block in method_missing'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `block in say_with_time'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `say_with_time'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:654:in `method_missing'
    /home/deepak/workspace/Project/db/migrate/20161109154178_add_discontinued_to_products_and_variants.spree.rb:63:in `down'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:611:in `exec_migration'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:591:in `block in migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:590:in `migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:768:in `migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1044:in `ddl_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:942:in `run'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:834:in `run'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:90:in `block (3 levels) in <top (required)>'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
    /home/deepak/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
    /home/deepak/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
    Tasks: TOP => db:migrate:down
    (See full trace by running task with --trace)

I think it has something to do with the backticks `` ` `` 

I have raised a pull request to fix it https://github.com/spree/spree/pull/7680

**Comment by deepakm-webonise** [comment]
:+1:
