### ISSUE TITLE
ArgumentError in Spree::OrdersController#update

### ISSUE THREAD

**Issue by 99cm** [spree/spree#7748]
comparison of NilClass with BigDecimal failed

Extracted source (around line #16):
14
15
16
17
18
19
              

        def compute_amount(order)
          [(order.item_total + order.ship_total), compute(order)].min * -1
        end
      end
    end

## Context

spree_core (3.1.3) app/models/spree/promotion/actions/create_adjustment.rb:16:in `each'
spree_core (3.1.3) app/models/spree/promotion/actions/create_adjustment.rb:16:in `min'
spree_core (3.1.3) app/models/spree/promotion/actions/create_adjustment.rb:16:in `compute_amount'
spree_core (3.1.3) app/models/concerns/spree/adjustment_source.rb:13:in `create_adjustment'
spree_core (3.1.3) app/models/concerns/spree/adjustment_source.rb:24:in `create_unique_adjustment'
spree_core (3.1.3) app/models/spree/promotion/actions/create_adjustment.rb:12:in `perform'
spree_core (3.1.3) app/models/spree/promotion.rb:70:in `block in activate'

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by 99cm** [comment]
The same error appeared when remove 1 item from cart. Full trace as follows:
Extracted source (around line #16):

        def compute_amount(order)
          [(order.item_total + order.ship_total), compute(order)].min * -1
        end
      end
    end`
**Application Trace | Framework Trace | Full **Trace**
spree_core (3.1.3) app/models/spree/promotion/actions/create_adjustment.rb:16:in `each'
spree_core (3.1.3) app/models/spree/promotion/actions/create_adjustment.rb:16:in `min'
spree_core (3.1.3) app/models/spree/promotion/actions/create_adjustment.rb:16:in `compute_amount'
spree_core (3.1.3) app/models/concerns/spree/adjustment_source.rb:13:in `create_adjustment'
spree_core (3.1.3) app/models/concerns/spree/adjustment_source.rb:24:in `create_unique_adjustment'
spree_core (3.1.3) app/models/spree/promotion/actions/create_adjustment.rb:12:in `perform'
spree_core (3.1.3) app/models/spree/promotion.rb:70:in `block in activate'
activerecord (4.2.6) lib/active_record/relation/delegation.rb:46:in `map'
activerecord (4.2.6) lib/active_record/relation/delegation.rb:46:in `map'
spree_core (3.1.3) app/models/spree/promotion.rb:69:in `activate'
spree_core (3.1.3) app/models/spree/promotion_handler/cart.rb:26:in `block in activate'
spree_core (3.1.3) app/models/spree/promotion_handler/cart.rb:24:in `each'
spree_core (3.1.3) app/models/spree/promotion_handler/cart.rb:24:in `activate'
spree_core (3.1.3) app/models/spree/order_contents.rb:33:in `update_cart'
spree_frontend (3.1.3) app/controllers/spree/orders_controller.rb:17:in `update'
actionpack (4.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.6) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.6) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.6) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.6) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.6) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.6) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.6) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.6) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:817:in `call'
railties (4.2.6) lib/rails/engine.rb:518:in `call'
railties (4.2.6) lib/rails/railtie.rb:194:in `public_send'
railties (4.2.6) lib/rails/railtie.rb:194:in `method_missing'
actionpack (4.2.6) lib/action_dispatch/routing/mapper.rb:51:in `serve'
actionpack (4.2.6) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:817:in `call'
warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
warden (1.2.6) lib/warden/manager.rb:34:in `catch'
warden (1.2.6) lib/warden/manager.rb:34:in `call'
rack (1.6.5) lib/rack/etag.rb:24:in `call'
rack (1.6.5) lib/rack/conditionalget.rb:38:in `call'
rack (1.6.5) lib/rack/head.rb:13:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.5) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.5) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.6) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
activerecord (4.2.6) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.6) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.3.0) lib/web_console/middleware.rb:20:in `block in call'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.5) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.5) lib/rack/lock.rb:17:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
railties (4.2.6) lib/rails/engine.rb:518:in `call'
railties (4.2.6) lib/rails/application.rb:165:in `call'
passenger (5.0.30) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
passenger (5.0.30) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
passenger (5.0.30) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
passenger (5.0.30) src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
passenger (5.0.30) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
Request

Parameters:

{"utf8"=>"✓",
 "_method"=>"patch",
 "authenticity_token"=>"/98BGenPfdTviIdGFMP+5sA+xPyQt9vq+OooruZXujfbPu0caUEMQWr1ea/bPKHtKjwloEf98pyd1EmWhflatg==",
 "order"=>{"line_items_attributes"=>{"0"=>{"quantity"=>"0",
 "id"=>"86"}},
 "coupon_code"=>""}}
