### ISSUE TITLE
Cannot run bundle exec test_app

### ISSUE THREAD

**Issue by delphaber** [spree/spree#8189]
I want to run `spree_core` tests on my machine but I got an error during `bundle exec test_app`

I cloned the `spree` repo (HEAD at `7420c13c1`)
I went inside the `spree` folder and I run `bundle`
Then I went inside the `core` folder and I run `bundle`
Then I run `bundle exec test_app --trace` and this is the output

```
** Invoke test_app (first_time)
** Execute test_app
** Invoke common:test_app (first_time)
** Execute common:test_app
Generating dummy Rails application...
Initialized empty Git repository in /Users/faber/Unicorns/spree/core/spec/dummy/.git/
Setting up dummy database...
rake aborted!
Bundler::VersionConflict: Bundler could not find compatible versions for gem "rabl":
  In Gemfile:
    spree was resolved to 3.3.0.rc2, which depends on
      spree_api (= 3.3.0.rc2) was resolved to 3.3.0.rc2, which depends on
        rabl (~> 0.13.1)

Could not find gem 'rabl (~> 0.13.1)', which is required by gem 'spree_api (= 3.3.0.rc2)', in any of the sources.
/Users/faber/Unicorns/spree/core/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/faber/Unicorns/spree/core/spec/dummy/config/application.rb:1:in `require'
/Users/faber/Unicorns/spree/core/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/faber/Unicorns/spree/core/spec/dummy/Rakefile:4:in `require_relative'
/Users/faber/Unicorns/spree/core/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/faber/.rbenv/versions/2.4.1/bin/bundle:23:in `load'
/Users/faber/.rbenv/versions/2.4.1/bin/bundle:23:in `<main>'
Bundler::Molinillo::VersionConflict: Bundler could not find compatible versions for gem "rabl":
  In Gemfile:
    spree was resolved to 3.3.0.rc2, which depends on
      spree_api (= 3.3.0.rc2) was resolved to 3.3.0.rc2, which depends on
        rabl (~> 0.13.1)

Could not find gem 'rabl (~> 0.13.1)', which is required by gem 'spree_api (= 3.3.0.rc2)', in any of the sources.
/Users/faber/Unicorns/spree/core/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/faber/Unicorns/spree/core/spec/dummy/config/application.rb:1:in `require'
/Users/faber/Unicorns/spree/core/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/faber/Unicorns/spree/core/spec/dummy/Rakefile:4:in `require_relative'
/Users/faber/Unicorns/spree/core/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/faber/.rbenv/versions/2.4.1/bin/bundle:23:in `load'
/Users/faber/.rbenv/versions/2.4.1/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
Skipping installation no generator to run...
Precompiling assets...
rake aborted!
Bundler::VersionConflict: Bundler could not find compatible versions for gem "rabl":
  In Gemfile:
    spree was resolved to 3.3.0.rc2, which depends on
      spree_api (= 3.3.0.rc2) was resolved to 3.3.0.rc2, which depends on
        rabl (~> 0.13.1)

Could not find gem 'rabl (~> 0.13.1)', which is required by gem 'spree_api (= 3.3.0.rc2)', in any of the sources.
/Users/faber/Unicorns/spree/core/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/faber/Unicorns/spree/core/spec/dummy/config/application.rb:1:in `require'
/Users/faber/Unicorns/spree/core/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/faber/Unicorns/spree/core/spec/dummy/Rakefile:4:in `require_relative'
/Users/faber/Unicorns/spree/core/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/faber/.rbenv/versions/2.4.1/bin/bundle:23:in `load'
/Users/faber/.rbenv/versions/2.4.1/bin/bundle:23:in `<main>'
Bundler::Molinillo::VersionConflict: Bundler could not find compatible versions for gem "rabl":
  In Gemfile:
    spree was resolved to 3.3.0.rc2, which depends on
      spree_api (= 3.3.0.rc2) was resolved to 3.3.0.rc2, which depends on
        rabl (~> 0.13.1)

Could not find gem 'rabl (~> 0.13.1)', which is required by gem 'spree_api (= 3.3.0.rc2)', in any of the sources.
/Users/faber/Unicorns/spree/core/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/faber/Unicorns/spree/core/spec/dummy/config/application.rb:1:in `require'
/Users/faber/Unicorns/spree/core/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/faber/Unicorns/spree/core/spec/dummy/Rakefile:4:in `require_relative'
/Users/faber/Unicorns/spree/core/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/faber/.rbenv/versions/2.4.1/bin/bundle:23:in `load'
/Users/faber/.rbenv/versions/2.4.1/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

I'm using rbenv 1.1.1 and bundler 1.15.3 on bash 4.4 on mac os sierra

What I'm doing wrong?

**Comment by damianlegawiec** [comment]
@delphaber it should be fixed now:

```
cd spree
git pull
cd api
bundle update
cd ../core
bundle update
bundle exec rake test_app
```

**Comment by delphaber** [comment]
Hi! Thanks for the fast reply!

I've got the same error :(

```
↳ $ bundle exec rake test_app --trace
** Invoke test_app (first_time)
** Execute test_app
** Invoke common:test_app (first_time)
** Execute common:test_app
Generating dummy Rails application...
Initialized empty Git repository in /Users/faber/Unicorns/spree/core/spec/dummy/.git/
Setting up dummy database...
rake aborted!
Bundler::VersionConflict: Bundler could not find compatible versions for gem "rabl":
  In Gemfile:
    spree was resolved to 3.3.0.rc2, which depends on
      spree_api (= 3.3.0.rc2) was resolved to 3.3.0.rc2, which depends on
        rabl (~> 0.13.1)

Could not find gem 'rabl (~> 0.13.1)', which is required by gem 'spree_api (= 3.3.0.rc2)', in any of the sources.
/Users/faber/Unicorns/spree/core/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/faber/Unicorns/spree/core/spec/dummy/config/application.rb:1:in `require'
/Users/faber/Unicorns/spree/core/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/faber/Unicorns/spree/core/spec/dummy/Rakefile:4:in `require_relative'
/Users/faber/Unicorns/spree/core/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/faber/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/Users/faber/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
Bundler::Molinillo::VersionConflict: Bundler could not find compatible versions for gem "rabl":
  In Gemfile:
    spree was resolved to 3.3.0.rc2, which depends on
      spree_api (= 3.3.0.rc2) was resolved to 3.3.0.rc2, which depends on
        rabl (~> 0.13.1)

Could not find gem 'rabl (~> 0.13.1)', which is required by gem 'spree_api (= 3.3.0.rc2)', in any of the sources.
/Users/faber/Unicorns/spree/core/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/faber/Unicorns/spree/core/spec/dummy/config/application.rb:1:in `require'
/Users/faber/Unicorns/spree/core/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/faber/Unicorns/spree/core/spec/dummy/Rakefile:4:in `require_relative'
/Users/faber/Unicorns/spree/core/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/faber/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/Users/faber/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)
Skipping installation no generator to run...
Precompiling assets...
rake aborted!
Bundler::VersionConflict: Bundler could not find compatible versions for gem "rabl":
  In Gemfile:
    spree was resolved to 3.3.0.rc2, which depends on
      spree_api (= 3.3.0.rc2) was resolved to 3.3.0.rc2, which depends on
        rabl (~> 0.13.1)

Could not find gem 'rabl (~> 0.13.1)', which is required by gem 'spree_api (= 3.3.0.rc2)', in any of the sources.
/Users/faber/Unicorns/spree/core/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/faber/Unicorns/spree/core/spec/dummy/config/application.rb:1:in `require'
/Users/faber/Unicorns/spree/core/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/faber/Unicorns/spree/core/spec/dummy/Rakefile:4:in `require_relative'
/Users/faber/Unicorns/spree/core/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/faber/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/Users/faber/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
Bundler::Molinillo::VersionConflict: Bundler could not find compatible versions for gem "rabl":
  In Gemfile:
    spree was resolved to 3.3.0.rc2, which depends on
      spree_api (= 3.3.0.rc2) was resolved to 3.3.0.rc2, which depends on
        rabl (~> 0.13.1)

Could not find gem 'rabl (~> 0.13.1)', which is required by gem 'spree_api (= 3.3.0.rc2)', in any of the sources.
/Users/faber/Unicorns/spree/core/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/faber/Unicorns/spree/core/spec/dummy/config/application.rb:1:in `require'
/Users/faber/Unicorns/spree/core/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/faber/Unicorns/spree/core/spec/dummy/Rakefile:4:in `require_relative'
/Users/faber/Unicorns/spree/core/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/faber/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/Users/faber/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)
```

**Comment by damianlegawiec** [comment]
@delphaber can you try to install rabl manually?

```
gem install -v 0.13.1 rabl
```

**Comment by delphaber** [comment]
Same error :(

**Comment by delphaber** [comment]
Found the problem! There's a problem with bundler 1.15. I installed bundler 1.13 and everything worked!

Solidus guys wrote it in the readme: 'Having bundler problems? Try downgrading to bundler 1.13.7 or earlier. Gem resolution is seriously broken in bundler versions since 1.14.'

**Comment by damianlegawiec** [comment]
@delphaber can you also add a similar note to ours README file? :)

**Comment by delphaber** [comment]
@damianlegawiec sure!

**Comment by delphaber** [comment]
Done! https://github.com/spree/spree/pull/8221

**Comment by adrian2monk** [comment]
Hi, guys, I have an issue with the same statement but the problem is different right now, the task is not available anymore. Ans, I could find at the docs any clue about the subject. Can you help me with any advice or orientation about where to look at?

Here let you the **trace** `bundle exec rake test_app --trace `
```
rake aborted!
Don't know how to build task 'test_app' (see --tasks)
/Library/Ruby/Gems/2.3.0/gems/rake-12.3.0/lib/rake/task_manager.rb:59:in `[]'
/Library/Ruby/Gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:159:in `invoke_task'
/Library/Ruby/Gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Library/Ruby/Gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/Library/Ruby/Gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/Library/Ruby/Gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/Library/Ruby/Gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/Library/Ruby/Gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/Library/Ruby/Gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/Library/Ruby/Gems/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:22:in `load'
/usr/local/bin/rake:22:in `<top (required)>'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
```
