### ISSUE TITLE
Extensions Tutorial: `require': cannot load such file -- factory_bot (LoadError)

### ISSUE THREAD

**Issue by jericdeleon** [spree/spree#8450]
## Context
I am new to Spree (and Rails in general). I tried following the Spree Developer Guides [here](https://guides.spreecommerce.org/developer/extensions_tutorial.html), but got stuck in the part: *Generating the Test App*.

When the instruction to run `bundle exec rake test_app` in the extension was advised, I tried running it but `rake` complained that `sqlite3` was missing. So I added it in the extension's Gemfile, then `bundle install`'ed. After that `rake test_app` ran fine, but once I ran rspec, I was greeted by the error below.

The extension functionality is still working fine, though.
It's just `rspec`'s setup in the extension that fails.

## Expected Behavior
As advised in the guide, `rspec` should run without issues:

```
No examples found.

Finished in 0.00005 seconds
0 examples, 0 failures
```

## Actual Behavior
Running `rspec` in the extension results in these error logs:
```
Downloads/dm/spree_simple_sales via 💎 v2.4.2                   
➜ rspec                         
Coverage report generated for RSpec to /home/jericdeleon/Downloads/dm/spree_simple_sales/coverage. 31 / 34 LOC (91.18%) covered.
/home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': cannot load such file -- factory_bot (LoadError)
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'    
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bundler/gems/spree-a99042ae849a/core/lib/spree/testing_support/factories.rb:1:in `<top (required)>'
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'    
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'    
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
        from /home/jericdeleon/Downloads/dm/spree_simple_sales/spec/spec_helper.rb:30:in `<top (required)>'                     
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'         
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'         
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `block in requires='
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `each'
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `requires='
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:111:in `each'
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:21:in `configure'
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:99:in `setup'
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:86:in `run'
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:71:in `run'
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:45:in `invoke'
        from /home/jericdeleon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/exe/rspec:4:in `<top (required)>'
        from /home/jericdeleon/.rbenv/versions/2.4.2/bin/rspec:23:in `load'                                                     
        from /home/jericdeleon/.rbenv/versions/2.4.2/bin/rspec:23:in `<main>'                                                   
```

## Steps to Reproduce
1. Follow the [Spree Extensions Tutorial](https://guides.spreecommerce.org/developer/extensions_tutorial.html)

## Your Environment
* Version used: 2.4.2 and 2.3.5 (issue encountered on both)
* generated `spec-helper.rb`:
```
# Run Coverage report
require 'simplecov'
SimpleCov.start do
  add_filter 'spec/dummy'
  add_group 'Controllers', 'app/controllers'
  add_group 'Helpers', 'app/helpers'
  add_group 'Mailers', 'app/mailers'
  add_group 'Models', 'app/models'
  add_group 'Views', 'app/views'
  add_group 'Libraries', 'lib'
end

# Configure Rails Environment
ENV['RAILS_ENV'] = 'test'

require File.expand_path('../dummy/config/environment.rb',  __FILE__)

require 'rspec/rails'
require 'database_cleaner'
require 'ffaker'

# Requires supporting ruby files with custom matchers and macros, etc,
# in spec/support/ and its subdirectories.
Dir[File.join(File.dirname(__FILE__), 'support/**/*.rb')].each { |f| require f }

# Requires factories and other useful helpers defined in spree_core.
require 'spree/testing_support/authorization_helpers'
require 'spree/testing_support/capybara_ext'
require 'spree/testing_support/controller_requests'
require 'spree/testing_support/factories'
require 'spree/testing_support/url_helpers'

# Requires factories defined in lib/spree_simple_sales/factories.rb
require 'spree_simple_sales/factories'

RSpec.configure do |config|
  config.include FactoryGirl::Syntax::Methods

  # Infer an example group's spec type from the file location.
  config.infer_spec_type_from_file_location!

  # == URL Helpers
  #
  # Allows access to Spree's routes in specs:
  #
  # visit spree.admin_path
  # current_path.should eql(spree.products_path)
  config.include Spree::TestingSupport::UrlHelpers

  # == Requests support
  #
  # Adds convenient methods to request Spree's controllers
  # spree_get :index
  config.include Spree::TestingSupport::ControllerRequests, type: :controller

  # == Mock Framework
  #
  # If you prefer to use mocha, flexmock or RR, uncomment the appropriate line:
  #
  # config.mock_with :mocha
  # config.mock_with :flexmock
  # config.mock_with :rr
  config.mock_with :rspec
  config.color = true

  # Remove this line if you're not using ActiveRecord or ActiveRecord fixtures
  config.fixture_path = "#{::Rails.root}/spec/fixtures"

  # Capybara javascript drivers require transactional fixtures set to false, and we use DatabaseCleaner
  # to cleanup after each test instead.  Without transactional fixtures set to false the records created
  # to setup a test will be unavailable to the browser, which runs under a separate server instance.
  config.use_transactional_fixtures = false

  # Ensure Suite is set to use transactions for speed.
  config.before :suite do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with :truncation
  end

  # Before each spec check if it is a Javascript test and switch between using database transactions or not where necessary.
  config.before :each do
    DatabaseCleaner.strategy = RSpec.current_example.metadata[:js] ? :truncation : :transaction
    DatabaseCleaner.start
  end

  # After each spec clean the database.
  config.after :each do
    DatabaseCleaner.clean
  end

  config.fail_fast = ENV['FAIL_FAST'] || false
  config.order = "random"
end

```

**Comment by bbonislawski** [comment]
Hello @jericdeleon , I'll try to reproduce your problem and fix it as soon as possible. Thanks for reporting your issue, I really appreciate your help!

**Comment by bbonislawski** [comment]
Ok, I investigated this case. It's already fixed on master and we'll soon be releasing patch versions and everything will be ok. 
For temporary fix, can you add `factory_bot` gem to your Gemfile?

**Comment by tanmay3011** [comment]
@bbonislawski v3.4.1 still has factory_girl. I guess with the new version release and backporting the factory_bot to previous versions this will get fixed.

**Comment by bbonislawski** [comment]
That's the plan too ;) I'm going to take care of it now.

**Comment by jericdeleon** [comment]
Ah, just got updated with news of `factory_girl` -> `factory_bot` rename

Anyway, including `factory_bot` gem and doing a global string replace of `FactoryGirl` -> FactoryBot within the extension folder worked

Thanks @bbonislawski !

**Comment by damianlegawiec** [comment]
`Spree 3.4.4` fixes this issue
