### ISSUE TITLE
Dummy app generation fails in core gems

### ISSUE THREAD

**Issue by artplan1** [spree/spree#8575]
I tried to run `DB=postgres bundle exec rake test_app` in core gem folders to run tests.
I received problems with dependencies

## Context

These are logs from different gems:

### Api

<details>
<summary>Log</summary>

```
~/projects/abc/spree/api
DB=postgres bundle exec rake test_app
Generating dummy Rails application...
Setting up dummy database...
rake aborted!
Bundler::VersionConflict: Bundler could not find compatible versions for gem "bootstrap-sass":
  In Gemfile:
    spree was resolved to 3.5.0.alpha, which depends on
      spree_backend (= 3.5.0.alpha) was resolved to 3.5.0.alpha, which depends on
        bootstrap-sass (~> 3.3)

Could not find gem 'bootstrap-sass (~> 3.3)', which is required by gem 'spree_backend (= 3.5.0.alpha)', in any of the sources.
/Users/artem/projects/abc/spree/api/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/api/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/api/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/api/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/api/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'

Caused by:
Bundler::Molinillo::VersionConflict: Unable to satisfy the following requirements:

- `bootstrap-sass (~> 3.3)` required by `spree_backend (3.5.0.alpha)`
/Users/artem/projects/abc/spree/api/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/api/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/api/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/api/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/api/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
      create  db/migrate/20180131162709_create_spree_dummy_models.rb
      create  app/models/spree/dummy_model.rb
rake aborted!
Bundler::VersionConflict: Bundler could not find compatible versions for gem "bootstrap-sass":
  In Gemfile:
    spree was resolved to 3.5.0.alpha, which depends on
      spree_backend (= 3.5.0.alpha) was resolved to 3.5.0.alpha, which depends on
        bootstrap-sass (~> 3.3)

Could not find gem 'bootstrap-sass (~> 3.3)', which is required by gem 'spree_backend (= 3.5.0.alpha)', in any of the sources.
/Users/artem/projects/abc/spree/api/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/api/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/api/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/api/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/api/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'

Caused by:
Bundler::Molinillo::VersionConflict: Unable to satisfy the following requirements:

- `bootstrap-sass (~> 3.3)` required by `spree_backend (3.5.0.alpha)`
/Users/artem/projects/abc/spree/api/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/api/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/api/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/api/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/api/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
Skipping installation no generator to run...
Precompiling assets...
rake aborted!
Bundler::VersionConflict: Bundler could not find compatible versions for gem "bootstrap-sass":
  In Gemfile:
    spree was resolved to 3.5.0.alpha, which depends on
      spree_backend (= 3.5.0.alpha) was resolved to 3.5.0.alpha, which depends on
        bootstrap-sass (~> 3.3)

Could not find gem 'bootstrap-sass (~> 3.3)', which is required by gem 'spree_backend (= 3.5.0.alpha)', in any of the sources.
/Users/artem/projects/abc/spree/api/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/api/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/api/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/api/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/api/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'

Caused by:
Bundler::Molinillo::VersionConflict: Unable to satisfy the following requirements:

- `bootstrap-sass (~> 3.3)` required by `spree_backend (3.5.0.alpha)`
/Users/artem/projects/abc/spree/api/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/api/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/api/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/api/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/api/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```
</details>

### Backend

<details>
<summary>Log</summary>

```
~/projects/abc/spree/backend
DB=postgres bundle exec rake test_app
Generating dummy Rails application...
Setting up dummy database...
rake aborted!
Bundler::VersionConflict: Bundler could not find compatible versions for gem "canonical-rails":
  In Gemfile:
    spree was resolved to 3.5.0.alpha, which depends on
      spree_frontend (= 3.5.0.alpha) was resolved to 3.5.0.alpha, which depends on
        canonical-rails (~> 0.2.0)

Could not find gem 'canonical-rails (~> 0.2.0)', which is required by gem 'spree_frontend (= 3.5.0.alpha)', in any of the sources.
/Users/artem/projects/abc/spree/backend/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/backend/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/backend/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/backend/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/backend/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'

Caused by:
Bundler::Molinillo::VersionConflict: Unable to satisfy the following requirements:

- `canonical-rails (~> 0.2.0)` required by `spree_frontend (3.5.0.alpha)`
/Users/artem/projects/abc/spree/backend/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/backend/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/backend/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/backend/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/backend/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
      create  db/migrate/20180131163195_create_spree_dummy_models.rb
      create  app/models/spree/dummy_model.rb
rake aborted!
Bundler::VersionConflict: Bundler could not find compatible versions for gem "canonical-rails":
  In Gemfile:
    spree was resolved to 3.5.0.alpha, which depends on
      spree_frontend (= 3.5.0.alpha) was resolved to 3.5.0.alpha, which depends on
        canonical-rails (~> 0.2.0)

Could not find gem 'canonical-rails (~> 0.2.0)', which is required by gem 'spree_frontend (= 3.5.0.alpha)', in any of the sources.
/Users/artem/projects/abc/spree/backend/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/backend/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/backend/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/backend/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/backend/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'

Caused by:
Bundler::Molinillo::VersionConflict: Unable to satisfy the following requirements:

- `canonical-rails (~> 0.2.0)` required by `spree_frontend (3.5.0.alpha)`
/Users/artem/projects/abc/spree/backend/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/backend/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/backend/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/backend/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/backend/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
Skipping installation no generator to run...
Precompiling assets...
rake aborted!
Bundler::VersionConflict: Bundler could not find compatible versions for gem "canonical-rails":
  In Gemfile:
    spree was resolved to 3.5.0.alpha, which depends on
      spree_frontend (= 3.5.0.alpha) was resolved to 3.5.0.alpha, which depends on
        canonical-rails (~> 0.2.0)

Could not find gem 'canonical-rails (~> 0.2.0)', which is required by gem 'spree_frontend (= 3.5.0.alpha)', in any of the sources.
/Users/artem/projects/abc/spree/backend/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/backend/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/backend/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/backend/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/backend/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'

Caused by:
Bundler::Molinillo::VersionConflict: Unable to satisfy the following requirements:

- `canonical-rails (~> 0.2.0)` required by `spree_frontend (3.5.0.alpha)`
/Users/artem/projects/abc/spree/backend/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/backend/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/backend/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/backend/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/backend/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```
</details>

### Core

<details>
<summary>Log</summary>

```
~/projects/abc/spree/core                                                                                                                                            DB=postgres bundle exec rake test_app
Generating dummy Rails application...
Setting up dummy database...
rake aborted!
Bundler::VersionConflict: Bundler could not find compatible versions for gem "bootstrap-sass":
  In Gemfile:
    spree was resolved to 3.5.0.alpha, which depends on
      spree_backend (= 3.5.0.alpha) was resolved to 3.5.0.alpha, which depends on
        bootstrap-sass (~> 3.3)

Could not find gem 'bootstrap-sass (~> 3.3)', which is required by gem 'spree_backend (= 3.5.0.alpha)', in any of the sources.
/Users/artem/projects/abc/spree/core/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/core/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/core/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/core/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/core/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'

Caused by:
Bundler::Molinillo::VersionConflict: Unable to satisfy the following requirements:

- `bootstrap-sass (~> 3.3)` required by `spree_backend (3.5.0.alpha)`
/Users/artem/projects/abc/spree/core/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/core/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/core/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/core/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/core/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
      create  db/migrate/20180131163466_create_spree_dummy_models.rb
      create  app/models/spree/dummy_model.rb
rake aborted!
Bundler::VersionConflict: Bundler could not find compatible versions for gem "bootstrap-sass":
  In Gemfile:
    spree was resolved to 3.5.0.alpha, which depends on
      spree_backend (= 3.5.0.alpha) was resolved to 3.5.0.alpha, which depends on
        bootstrap-sass (~> 3.3)

Could not find gem 'bootstrap-sass (~> 3.3)', which is required by gem 'spree_backend (= 3.5.0.alpha)', in any of the sources.
/Users/artem/projects/abc/spree/core/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/core/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/core/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/core/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/core/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'

Caused by:
Bundler::Molinillo::VersionConflict: Unable to satisfy the following requirements:

- `bootstrap-sass (~> 3.3)` required by `spree_backend (3.5.0.alpha)`
/Users/artem/projects/abc/spree/core/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/core/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/core/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/core/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/core/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
Skipping installation no generator to run...
Precompiling assets...
rake aborted!
Bundler::VersionConflict: Bundler could not find compatible versions for gem "bootstrap-sass":
  In Gemfile:
    spree was resolved to 3.5.0.alpha, which depends on
      spree_backend (= 3.5.0.alpha) was resolved to 3.5.0.alpha, which depends on
        bootstrap-sass (~> 3.3)

Could not find gem 'bootstrap-sass (~> 3.3)', which is required by gem 'spree_backend (= 3.5.0.alpha)', in any of the sources.
/Users/artem/projects/abc/spree/core/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/core/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/core/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/core/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/core/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'

Caused by:
Bundler::Molinillo::VersionConflict: Unable to satisfy the following requirements:

- `bootstrap-sass (~> 3.3)` required by `spree_backend (3.5.0.alpha)`
/Users/artem/projects/abc/spree/core/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/core/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/core/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/core/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/core/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```
</details>

### Frontend

<details>
<summary>Log</summary>

```
~/projects/abc/spree/frontend                                                                                                                                        DB=postgres bundle exec rake test_app
Generating dummy Rails application...
Setting up dummy database...
rake aborted!
Bundler::VersionConflict: Bundler could not find compatible versions for gem "jquery-ui-rails":
  In Gemfile:
    spree was resolved to 3.5.0.alpha, which depends on
      spree_backend (= 3.5.0.alpha) was resolved to 3.5.0.alpha, which depends on
        jquery-ui-rails (~> 6.0.1)

Could not find gem 'jquery-ui-rails (~> 6.0.1)', which is required by gem 'spree_backend (= 3.5.0.alpha)', in any of the sources.
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/frontend/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/frontend/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'

Caused by:
Bundler::Molinillo::VersionConflict: Unable to satisfy the following requirements:

- `jquery-ui-rails (~> 6.0.1)` required by `spree_backend (3.5.0.alpha)`
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/frontend/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/frontend/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
      create  db/migrate/20180131163274_create_spree_dummy_models.rb
      create  app/models/spree/dummy_model.rb
rake aborted!
Bundler::VersionConflict: Bundler could not find compatible versions for gem "jquery-ui-rails":
  In Gemfile:
    spree was resolved to 3.5.0.alpha, which depends on
      spree_backend (= 3.5.0.alpha) was resolved to 3.5.0.alpha, which depends on
        jquery-ui-rails (~> 6.0.1)

Could not find gem 'jquery-ui-rails (~> 6.0.1)', which is required by gem 'spree_backend (= 3.5.0.alpha)', in any of the sources.
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/frontend/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/frontend/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'

Caused by:
Bundler::Molinillo::VersionConflict: Unable to satisfy the following requirements:

- `jquery-ui-rails (~> 6.0.1)` required by `spree_backend (3.5.0.alpha)`
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/frontend/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/frontend/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
Skipping installation no generator to run...
Precompiling assets...
rake aborted!
Bundler::VersionConflict: Bundler could not find compatible versions for gem "jquery-ui-rails":
  In Gemfile:
    spree was resolved to 3.5.0.alpha, which depends on
      spree_backend (= 3.5.0.alpha) was resolved to 3.5.0.alpha, which depends on
        jquery-ui-rails (~> 6.0.1)

Could not find gem 'jquery-ui-rails (~> 6.0.1)', which is required by gem 'spree_backend (= 3.5.0.alpha)', in any of the sources.
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/frontend/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/frontend/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'

Caused by:
Bundler::Molinillo::VersionConflict: Unable to satisfy the following requirements:

- `jquery-ui-rails (~> 6.0.1)` required by `spree_backend (3.5.0.alpha)`
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/boot.rb:6:in `<top (required)>'
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/frontend/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/frontend/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```
</details>

## Expected Behavior

App should be generated, tests should pass

## Actual Behavior

All in logs

## Possible Fix

Issue is similar to https://github.com/spree/spree/issues/8189

But downgrading bundler is not the way

And more, bundler guys wrote that they fixed it: https://github.com/bundler/bundler/issues/5633

I see one problem in `dummy generator's` gemfile_path

```ruby
def gemfile_path
    core_gems = ["spree/core", "spree/api", "spree/backend", "spree/frontend"]

    if core_gems.include?(lib_name)
        '../../../../../Gemfile'
    else
        '../../../../Gemfile'
    end
end
```

It sets gemfile path of dummy app to root of main spree gem which add all core gems dependencies to currently tested gem

That Gemfile contains all deps which is good, but is it necessary?

I don't think `spree_backend` gem should have `spree_frontend` as dependency

When I'm fixing generator to set path to gem folder (`../../../../Gemfile`):
- everything is good in all gems when running in that folder
- but it only fails when I'm running `rake` from `main spree` root when it set up `frontend gem` test app

<details>
<summary>Log</summary>

```
rake test_app
Generating dummy Rails application...
Setting up dummy database...
rake aborted!
Bundler::GemNotFound: Could not find gem 'capybara-accessible' in any of the gem sources listed in your Gemfile.
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/boot.rb:14:in `<top (required)>'
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/application.rb:1:in `require'
/Users/artem/projects/abc/spree/frontend/spec/dummy/config/application.rb:1:in `<top (required)>'
/Users/artem/projects/abc/spree/frontend/spec/dummy/Rakefile:4:in `require_relative'
/Users/artem/projects/abc/spree/frontend/spec/dummy/Rakefile:4:in `<top (required)>'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/artem/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
```
</details>

## Steps to Reproduce

1. cd to gem folder
2. run `bundle exec rake test_app`

## Your Environment

Mac OS 10.13.2
Ruby 2.4.2
Bundler 1.61.1

**Comment by mvz** [comment]
What works for me is:

```
bundle install
cd core
BUNDLE_GEMFILE=../Gemfile bundle exec rake test_app
```

The simpler solution is probably to only have a `Gemfile` in the top level directory, since I don't see any use case where you want to use the per-gem version.

**Comment by artplan1** [comment]
@mvz that works for me, thank you 👍
