### ISSUE TITLE
No route matches {:action=>"show", :controller=>"spree/taxons", :id=>nil}, possible unmatched constraints: [:id]

### ISSUE THREAD

**Issue by 99cm** [spree/spree#8675]
spree/core/app/helpers/spree/base_helper.rb need to be fixed!
`seo_url(taxon)` does not work any more for spree 3.4.4 and up if #2759 comment ever fixed before.

puma logged errors:

> Error during failsafe response: No route matches {:action=>"show", :controller=>"spree/taxons", :id=>nil}, possible unmatched constraints: [:id]
>   /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/journey/formatter.rb:55:in `generate'
>   /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/routing/route_set.rb:748:in `generate'
>   /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/routing/route_set.rb:779:in `generate'
>   /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/routing-filter-0.6.1/lib/routing_filter/adapters/rails.rb:30:in `block in generate'
>   /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/routing-filter-0.6.1/lib/routing_filter/filters/locale.rb:70:in `around_generate'
>   /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/routing-filter-0.6.1/lib/routing_filter/filter.rb:11:in `run'
>   /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/routing-filter-0.6.1/lib/routing_filter/chain.rb:15:in `run'
>   /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/routing-filter-0.6.1/lib/routing_filter/adapters/rails.rb:29:in `generate'
>   /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/routing/route_set.rb:826:in `url_for'
>   /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/routing/route_set.rb:277:in `call'
>   /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/routing/route_set.rb:335:in `block (2 levels) in define_url_helper'
>   /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/routing/routes_proxy.rb:42:in `nested_taxons_path'
>   /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/routing/routes_proxy.rb:45:in `method_missing'
>   /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spree_core-3.4.4/app/helpers/spree/base_helper.rb:79:in `seo_url'
>   /home/ypill/wuxu18/app/views/spree/frontend/ypill/_main_nav_bar.html.erb:16:in `block (3 levels) in _d16a1d9612a1846710427ba2d762257f'

In _main_nav_html.erb code:

```
            <% @taxonomies.each do |taxonomy| %>
              <% cache [I18n.locale, taxonomy, max_level] do %>
                    <% taxonomy.root.children.each do |taxon| %>
                      <li class="<%= (taxon.id == @taxon.id ? 'active' : '') unless @taxon.nil? %>">
                        <%= link to taxon.name, seo_url(taxon) %>">
                        </a>
                      </li>
                    <% end %>
                <% end %>
            <% end %>
```
Line 16: seo_url(taxon)
`<%= link to taxon.name, seo_url(taxon) %>">`
In  spree/core/app/helpers/spree/base_helper.rb:
```
    def seo_url(taxon)
      spree.nested_taxons_path(taxon.permalink)
    end
```
Line 79:
` spree.nested_taxons_path(taxon.permalink)`
Method missing?
or undefined method `permalink`?

**Comment by bbonislawski** [comment]
Can you provide more details? Did you use `seo_url` in your code?
 It happens when you pass `nil` to helper and it's expected result.

**Comment by 99cm** [comment]
yes, code inserted in the post above, `_main_nav_html.erb`.
Line 16: <%= link to taxon.name, seo_url(taxon) %>

In spree/core/app/helpers/spree/base_helper.rb, line 79: `spree.nested_taxons_path(taxon.permalink)`
undefined method 'permalink' for nil:Nil.Class?

**Comment by 99cm** [comment]
your conclusion is rough. I am going to comment base_helper_decorator.rb, in reference to solidus/base_helper.rb
spree has  spree/frontend/app/helpers/spree/frontend_helper.rb. How does it work together with base_helper.rb?
