### ISSUE TITLE
Tests failing with attachments

### ISSUE THREAD

**Issue by ianzitow** [spree/spree#8905]
## Context

I just cloned the repository, tried master and 3-6-stable branches and followed steps of [Developing Spree](https://github.com/spree/spree#developing-spree) section. 

## Expected Behavior

It should successfully run all tests.

## Actual Behavior

Tests failing when validating presence of attachments.

## Possible Fix

Maybe we need to update README.

## Steps to Reproduce

When running the following commands:
```
cd core
BUNDLE_GEMFILE=../Gemfile bundle exec rake test_app
bundle exec rspec spec
```
It returns with just 6 examples tested:
```
Run options: include {:active_storage=>true}

Randomized with seed 32091
......

Finished in 0.81428 seconds (files took 6.58 seconds to load)
6 examples, 0 failures
```
When I run `bash build.sh`, it just runs tests for the core part (skipping next) and returns 11 failed tests, all that might be related to ActiveStorage:
```
Failure/Error: let!(:product_image) { product.master.images.create!(attachment: image('thinking-cat.jpg')) }
      
      ActiveRecord::RecordInvalid:
        Validation failed: Attachment must be present
```
Am I missing any configuration?

## Your Environment

* Version used: Tested branch and 3-6-stable branches.
* Gemfile and Gemfile.lock as text in a Gist: https://gist.github.com/ianzitow/7734bdda5cc2fa96de99bbc0579d5dc4
* Any relevant stack traces ("Full trace" preferred): 
```
      Failure/Error: let!(:product_image) { product.master.images.create!(attachment: image('thinking-cat.jpg')) }
      
      ActiveRecord::RecordInvalid:
        Validation failed: Attachment must be present
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/validations.rb:80:in `raise_validation_error'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/validations.rb:52:in `save!'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/transactions.rb:315:in `block in save!'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/transactions.rb:386:in `block in with_transaction_returning_status'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:252:in `transaction'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/transactions.rb:212:in `transaction'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/transactions.rb:383:in `with_transaction_returning_status'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/transactions.rb:315:in `save!'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/suppressor.rb:48:in `save!'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:374:in `insert_record'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/associations/has_many_association.rb:36:in `insert_record'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:362:in `block (2 levels) in _create_record'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:455:in `replace_on_target'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:284:in `add_to_target'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:360:in `block in _create_record'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:136:in `block in transaction'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:230:in `block in within_new_transaction'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:227:in `within_new_transaction'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/transactions.rb:212:in `transaction'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:135:in `transaction'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:359:in `_create_record'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/associations/has_many_association.rb:123:in `_create_record'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/associations/association.rb:186:in `create!'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/associations/collection_proxy.rb:366:in `create!'
      # ./spec/controllers/spree/api/v1/images_controller_spec.rb:48:in `block (4 levels) in <module:Spree>'
      # /Users/ianzitow/.rbenv/versions/2.5.1/bin/rspec:23:in `load'
      # /Users/ianzitow/.rbenv/versions/2.5.1/bin/rspec:23:in `<top (required)>'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `load'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:28:in `run'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/cli.rb:424:in `exec'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/cli.rb:27:in `dispatch'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/cli.rb:18:in `start'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/exe/bundle:30:in `block in <top (required)>'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
      # /Users/ianzitow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/exe/bundle:22:in `<top (required)>'
      # /Users/ianzitow/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
      # /Users/ianzitow/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
```

**Comment by VygovskySergey** [comment]
@ianzitow Hello, yeah, we know about it, these tests are supposed to work with `Paperclip`, and right now for transition period we left them as they are. After we complete move to `ActiveStorage`, we rewrite them due to `ActiveStorage` syntax, you can add env variable `SPREE_USE_PAPERCLIP=true`, for passing tests in your dev environment
