### ISSUE TITLE
bundle exec rake spree_sample:load

### ISSUE THREAD

**Issue by laoyouzi** [spree/spree#8924]
When I executed bundle exec rake spree_saple:load, I got the following error：
ActiveRecord::StatementInvalid: Mysql2::Error: Column 'updated_at' in field list is ambiguous: UPDATE `spree_option_values` INNER JOIN `spree_option_value_translations` ON `spree_option_value_translations`.`spree_option_value_id` = `spree_option_values`.`id` SET `position` = (`spree_option_values`.`position` + 1), `updated_at` = '2018-08-06 08:17:48.490969' WHERE `spree_option_values`.`option_type_id` = 1 AND (`spree_option_values`.`position` >= 1)

![image](https://user-images.githubusercontent.com/20438144/43705712-ec782ab6-9995-11e8-9a5c-28b8c1c69837.png)

**Comment by VygovskySergey** [comment]
@laoyouzi Could you send extended stack trace? I need to know which file cause this error.

**Comment by laoyouzi** [comment]
The correct way should be added 'spree_products'.name, as follws:
SELECT  DISTINCT **_spree_products`.`name_**, `spree_products`.`id`, `spree_products`.`available_on`, `spree_products`.`discontinue_on`, `spree_products`.`deleted_at`, 
`spree_products`.`tax_category_id`, `spree_products`.`shipping_category_id`, `spree_products`.`created_at`, `spree_products`.`updated_at`, `spree_products`.`promotionable` FROM `spree_products` WHERE `spree_products`.`deleted_at` IS NULL AND (`spree_products`.discontinue_on IS NULL or `spree_products`.discontinue_on >= '2018-08-07 00:33:50.703598') ORDER BY `spree_products`.`name` ASC LIMIT 25 OFFSET 0

![image](https://user-images.githubusercontent.com/20438144/43747684-0b9dff82-9a1e-11e8-933b-e191c36b6032.png)

**Comment by VygovskySergey** [comment]
@laoyouzi So you have another error? Could you provide more explicit info about errors that you have?

**Comment by exocode** [comment]
Here is my stacktrace:

```
rails spree_sample:load
Loaded Payment Methods samples
Loaded Shipping Categories samples
Loaded Shipping Methods samples
Loaded Tax Categories samples
Loaded Tax Rates samples
Loaded Products samples
Loaded Taxonomies samples
Loaded Taxons samples
Loaded Option Types samples
rails aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Column 'updated_at' in field list is ambiguous: UPDATE `spree_option_values` INNER JOIN `spree_option_value_translations` ON `spree_option_value_translations`.`spree_option_value_id` = `spree_option_values`.`id` SET `position` = (`spree_option_values`.`position` + 1), `updated_at` = '2018-10-14 13:14:04.199431' WHERE `spree_option_values`.`option_type_id` = 1 AND (`spree_option_values`.`position` >= 1)
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:214:in `block (2 levels) in execute'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:213:in `block in execute'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:613:in `block (2 levels) in log'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block in log'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `log'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:212:in `execute'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/mysql/database_statements.rb:26:in `execute'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:223:in `execute_and_free'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/mysql/database_statements.rb:43:in `exec_delete'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:140:in `update'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `update'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation.rb:380:in `update_all'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/querying.rb:8:in `update_all'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:90:in `public_send'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:90:in `block in method_missing'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation.rb:336:in `scoping'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:90:in `method_missing'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:413:in `block in make_lambda'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:178:in `block (2 levels) in halting_and_conditional'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:600:in `catch'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:600:in `block in default_terminator'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:179:in `block in halting_and_conditional'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:507:in `block in invoke_before'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:507:in `each'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:507:in `invoke_before'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:130:in `run_callbacks'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:827:in `_run_create_callbacks'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/callbacks.rb:340:in `_create_record'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/timestamp.rb:95:in `_create_record'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/persistence.rb:553:in `create_or_update'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/callbacks.rb:336:in `block in create_or_update'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:131:in `run_callbacks'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/callbacks.rb:336:in `create_or_update'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/persistence.rb:162:in `save!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/validations.rb:50:in `save!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/attribute_methods/dirty.rb:43:in `save!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:313:in `block in save!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:210:in `transaction'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:313:in `save!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/suppressor.rb:46:in `save!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/persistence.rb:51:in `create!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation.rb:156:in `block in create!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation.rb:336:in `scoping'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation.rb:156:in `create!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation.rb:164:in `first_or_create!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/Users/janjezek/.gem/ruby/2.5.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/janjezek/.gem/ruby/2.5.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/janjezek/.gem/ruby/2.5.0/gems/railties-5.1.6/lib/rails/command.rb:46:in `invoke'
/Users/janjezek/.gem/ruby/2.5.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
/Users/janjezek/Coding/RubymineProjects/demo51-spree/bin/rails:9:in `require'
/Users/janjezek/Coding/RubymineProjects/demo51-spree/bin/rails:9:in `<top (required)>'
/Users/janjezek/Coding/RubymineProjects/demo51-spree/bin/spring:15:in `<main>'

Caused by:
Mysql2::Error: Column 'updated_at' in field list is ambiguous
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:214:in `block (2 levels) in execute'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:213:in `block in execute'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:613:in `block (2 levels) in log'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block in log'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `log'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:212:in `execute'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/mysql/database_statements.rb:26:in `execute'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:223:in `execute_and_free'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/mysql/database_statements.rb:43:in `exec_delete'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:140:in `update'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `update'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation.rb:380:in `update_all'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/querying.rb:8:in `update_all'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:90:in `public_send'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:90:in `block in method_missing'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation.rb:336:in `scoping'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:90:in `method_missing'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:413:in `block in make_lambda'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:178:in `block (2 levels) in halting_and_conditional'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:600:in `catch'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:600:in `block in default_terminator'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:179:in `block in halting_and_conditional'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:507:in `block in invoke_before'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:507:in `each'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:507:in `invoke_before'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:130:in `run_callbacks'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:827:in `_run_create_callbacks'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/callbacks.rb:340:in `_create_record'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/timestamp.rb:95:in `_create_record'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/persistence.rb:553:in `create_or_update'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/callbacks.rb:336:in `block in create_or_update'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:131:in `run_callbacks'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/callbacks.rb:336:in `create_or_update'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/persistence.rb:162:in `save!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/validations.rb:50:in `save!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/attribute_methods/dirty.rb:43:in `save!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:313:in `block in save!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:210:in `transaction'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:313:in `save!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/suppressor.rb:46:in `save!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/persistence.rb:51:in `create!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation.rb:156:in `block in create!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation.rb:336:in `scoping'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation.rb:156:in `create!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation.rb:164:in `first_or_create!'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/janjezek/.gem/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/Users/janjezek/.gem/ruby/2.5.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/janjezek/.gem/ruby/2.5.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/janjezek/.gem/ruby/2.5.0/gems/railties-5.1.6/lib/rails/command.rb:46:in `invoke'
/Users/janjezek/.gem/ruby/2.5.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
/Users/janjezek/Coding/RubymineProjects/demo51-spree/bin/rails:9:in `require'
/Users/janjezek/Coding/RubymineProjects/demo51-spree/bin/rails:9:in `<top (required)>'
/Users/janjezek/Coding/RubymineProjects/demo51-spree/bin/spring:15:in `<main>'
Tasks: TOP => spree_sample:load
(See full trace by running task with --trace)

Process finished with exit code 1


```
