### ISSUE TITLE
Rails 5.2.1 breaks Spree

### ISSUE THREAD

**Issue by sofianegargouri** [spree/spree#8929]
Spree isn't working since Rails 5.2.1

## Context
I upgraded my Rails app to 5.2.1 this morning, and it isn't working since then. Downgrading to 5.2.0 fixed it.

## Expected Behavior
Run migrations and work well

## Actual Behavior
When running migrations:

```
== 20180806143829 MakeExistingCreditCardsDefault: migrating ===================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

wrong number of arguments (given 3, expected 2)
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/polyamorous-1.3.3/lib/polyamorous/activerecord_5.2_ruby_2/join_dependency.rb:58:in `join_constraints'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/relation/query_methods.rb:1027:in `build_join_query'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/relation/query_methods.rb:1009:in `build_joins'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/relation/query_methods.rb:929:in `build_arel'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/relation/query_methods.rb:903:in `arel'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/relation.rb:329:in `update_all'
/Users/sofianegargouri/Development/project/db/migrate/20180806143829_make_existing_credit_cards_default.spree.rb:8:in `up'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/migration.rb:817:in `exec_migration'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/migration.rb:797:in `block in migrate'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:414:in `with_connection'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/migration.rb:796:in `migrate'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/migration.rb:977:in `migrate'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/transactions.rb:212:in `transaction'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/migration.rb:1343:in `ddl_transaction'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/migration.rb:1262:in `each'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/migration.rb:1210:in `block in migrate'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/migration.rb:1210:in `migrate'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/migration.rb:1036:in `up'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/migration.rb:1011:in `migrate'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
/Users/sofianegargouri/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
```

When trying to access the app:

```
ArgumentError in Spree::Home#index
Showing /Users/sofianegargouri/Development/Project/app/views/spree/home/index.html.erb where line #9 raised:

wrong number of arguments (given 3, expected 2)


7 8 9 10 11 12 | <div data-hook="homepage_products">   <% cache(cache_key_for_products) do %>     <%= render partial: 'spree/shared/products', locals: { products: @products } %>   <% end %> </div>
-- | --


Rails.root: /Users/sofianegargouri/Development/Project

Application Trace | Framework Trace | Full Trace
activerecord (5.2.1) lib/active_record/associations/join_dependency/join_association.rb:12:in `initialize'
polyamorous (1.3.3) lib/polyamorous/activerecord_5.2_ruby_2/join_association.rb:19:in `initialize'
polyamorous (1.3.3) lib/polyamorous/activerecord_5.2_ruby_2/join_dependency.rb:28:in `new'
polyamorous (1.3.3) lib/polyamorous/activerecord_5.2_ruby_2/join_dependency.rb:28:in `block in build'
polyamorous (1.3.3) lib/polyamorous/activerecord_5.2_ruby_2/join_dependency.rb:8:in `each'
polyamorous (1.3.3) lib/polyamorous/activerecord_5.2_ruby_2/join_dependency.rb:8:in `map'
polyamorous (1.3.3) lib/polyamorous/activerecord_5.2_ruby_2/join_dependency.rb:8:in `build'
polyamorous (1.3.3) lib/polyamorous/activerecord_5.2_ruby_2/join_dependency.rb:28:in `block in build'
polyamorous (1.3.3) lib/polyamorous/activerecord_5.2_ruby_2/join_dependency.rb:8:in `each'
polyamorous (1.3.3) lib/polyamorous/activerecord_5.2_ruby_2/join_dependency.rb:8:in `map'
polyamorous (1.3.3) lib/polyamorous/activerecord_5.2_ruby_2/join_dependency.rb:8:in `build'
activerecord (5.2.1) lib/active_record/associations/join_dependency.rb:72:in `initialize'
activerecord (5.2.1) lib/active_record/relation/query_methods.rb:1023:in `new'
activerecord (5.2.1) lib/active_record/relation/query_methods.rb:1023:in `build_join_query'
activerecord (5.2.1) lib/active_record/relation/query_methods.rb:1009:in `build_joins'
activerecord (5.2.1) lib/active_record/relation/query_methods.rb:929:in `build_arel'
activerecord (5.2.1) lib/active_record/relation/query_methods.rb:903:in `arel'
activerecord (5.2.1) lib/active_record/relation.rb:587:in `references_eager_loaded_tables?'
activerecord (5.2.1) lib/active_record/relation.rb:469:in `eager_loading?'
activerecord (5.2.1) lib/active_record/relation/calculations.rb:214:in `has_include?'
activerecord (5.2.1) lib/active_record/relation/calculations.rb:132:in `calculate'
activerecord (5.2.1) lib/active_record/relation/calculations.rb:52:in `count'
spree_core (3.6.2) app/helpers/spree/products_helper.rb:50:in `cache_key_for_products'
app/views/spree/home/index.html.erb:9:in `_6f1171295a7198085d55d1d92ef99f74'
actionview (5.2.1) lib/action_view/template.rb:159:in `block in render'
activesupport (5.2.1) lib/active_support/notifications.rb:170:in `instrument'
actionview (5.2.1) lib/action_view/template.rb:354:in `instrument_render_template'
actionview (5.2.1) lib/action_view/template.rb:157:in `render'
deface (1.3.0) lib/deface/action_view_extensions.rb:41:in `render'
actionview (5.2.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (5.2.1) lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
activesupport (5.2.1) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.1) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.2.1) lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
actionview (5.2.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (5.2.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (5.2.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (5.2.1) lib/action_view/renderer/template_renderer.rb:16:in `render'
actionview (5.2.1) lib/action_view/renderer/renderer.rb:44:in `render_template'
actionview (5.2.1) lib/action_view/renderer/renderer.rb:25:in `render'
actionview (5.2.1) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.2.1) lib/action_controller/metal/streaming.rb:219:in `_render_template'
actionview (5.2.1) lib/action_view/rendering.rb:84:in `render_to_body'
actionpack (5.2.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.2.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (5.2.1) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (5.2.1) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
activesupport (5.2.1) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/Users/sofianegargouri/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
activesupport (5.2.1) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.2.1) lib/active_record/railties/controller_runtime.rb:31:in `cleanup_view_runtime'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:45:in `render'
actionpack (5.2.1) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
actionpack (5.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
actionpack (5.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
actionpack (5.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.1) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.1) lib/active_support/callbacks.rb:132:in `run_callbacks'
actionpack (5.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.1) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.1) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.1) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.1) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
railties (5.2.1) lib/rails/engine.rb:524:in `call'
railties (5.2.1) lib/rails/railtie.rb:190:in `public_send'
railties (5.2.1) lib/rails/railtie.rb:190:in `method_missing'
actionpack (5.2.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (5.2.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
versioncake (3.4.0) lib/versioncake/rack/middleware.rb:17:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.5) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.5) lib/rack/etag.rb:25:in `call'
rack (2.0.5) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.5) lib/rack/head.rb:12:in `call'
actionpack (5.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.1) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.6.2) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.6.2) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `catch'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.2.1) lib/rails/engine.rb:524:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

## Temporary Fix
Downgrade to Rails 5.2.0

## Steps to Reproduce

1. Install Spree with Rails 5.2.1

## Your Environment
* Version used: 3.6.2

**Comment by bbonislawski** [comment]
Unfortunately, you're right. Rails team changed associations internals in activerecord again, so https://github.com/activerecord-hackery/polyamorous (which is dependency of ransack) stopped working. I'm trying to fix it and provide PR for polyamorous as soon as possible. For now we have to lock version of rails on 5.2.0
