### ISSUE TITLE
 cannot load such file -- polyamorous/activerecord_5.2.2_ruby_2/join_association (LoadError)

### ISSUE THREAD

**Issue by sureshchipurupalli** [spree/spree#9107]
I'm trying to setup spree in ubuntu 16.04.I'm following this [https://guides.spreecommerce.org/developer/getting_started_tutorial.html](url)

```
ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]

rails -v
Rails 5.2.2
```

Added Spree gems to my Gemfile:
```
gem 'spree', '~> 3.6.4'
gem 'spree_auth_devise', '~> 3.3'
gem 'spree_gateway', '~> 3.3'
```

`bundle install`

I tried to use the install generators to set up Spree:

`rails g spree:install --user_class=Spree::User`

```
root@vmi11:/var/www/mystore# rails g spree:install --user_class=Spree::User
/usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': cannot load such file -- polyamorous/activerecord_5.2.2_ruby_2/join_association (LoadError)
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/ransack-2.0.1/lib/polyamorous.rb:30:in `block in <main>'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/ransack-2.0.1/lib/polyamorous.rb:29:in `each'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/ransack-2.0.1/lib/polyamorous.rb:29:in `<main>'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/ransack-2.0.1/lib/ransack/adapters/active_record/context.rb:3:in `<main>'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/ransack-2.0.1/lib/ransack/adapters/active_record.rb:14:in `<main>'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/ransack-2.0.1/lib/ransack/adapters.rb:25:in `require_adapter'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/ransack-2.0.1/lib/ransack.rb:27:in `<main>'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/spree_core-3.6.5/lib/spree/core.rb:14:in `<main>'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/spree_core-3.6.5/lib/spree_core.rb:2:in `<main>'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/spree-3.6.5/lib/spree.rb:1:in `<main>'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `each'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `block in require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `each'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler.rb:114:in `require'
        from /var/www/mystore/config/application.rb:7:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:92:in `require'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:92:in `preload'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
        from /usr/local/rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from -e:1:in `<main>'


```

``
I'm getting the  same error for :
```
rails g spree:auth:install
rails g spree_gateway:install
```

**Comment by damianlegawiec** [comment]
@sureshchipurupalli this is caused by ransack dependency

https://github.com/activerecord-hackery/ransack/issues/987

For now, you can simply lock rails in your `Gemfile`

```gem 'rails', '~> 5.2.1.1'```
