### ISSUE TITLE
MiniMagick::Error when creating a product url with an inexistent style

### ISSUE THREAD

**Issue by r-sierra** [spree/spree#9130]
## Context
When trying to create an image url with 

    main_app.url_for(@product.images.first.url(some_style))

if the value of `some_style` is not defined in [Image::Configuration::ActiveStorage](https://github.com/spree/spree/blob/69ec26e448bd9b9223c0c59d68db96d76246f9b5/core/app/models/spree/image/configuration/active_storage.rb#L13-L20), the url is generated with an invalid *resize* attribute, so when clicked an exception arises from MiniMagick.

The method responsible for creating the url is defined here:

https://github.com/spree/spree/blob/69ec26e448bd9b9223c0c59d68db96d76246f9b5/core/app/models/spree/asset/support/active_storage.rb#L8-L12

And `dimensions_for_style` is defined here:

https://github.com/spree/spree/blob/69ec26e448bd9b9223c0c59d68db96d76246f9b5/core/app/models/spree/asset/support/active_storage.rb#L18-L20

So when computing `dimensions_for_style` for a non existent `style` the `default_style` is returned, which is a symbol not a dimension.

https://github.com/spree/spree/blob/69ec26e448bd9b9223c0c59d68db96d76246f9b5/core/app/models/spree/image/configuration/active_storage.rb#L22-L24
## Expected Behavior
The url generated for the image should contain a valid resize attribute, even when the style is invalid

## Actual Behavior
The url generated for the image contains an invalid resize attribute. Instead of
having dimensions(ex: 250x250) it has the string "product" which is the default style for ActiveStorage

## Possible Fix
Change `dimesions_for_style` method in [app/models/spree/support/active_storage.rb](https://github.com/spree/spree/blob/69ec26e448bd9b9223c0c59d68db96d76246f9b5/core/app/models/spree/asset/support/active_storage.rb#L18-L20)

          def dimensions_for_style(style)
            # self.class.styles.with_indifferent_access[style] || default_style
            self.class.styles.with_indifferent_access[style] || self.class.styles.with_indifferent_access[default_style]
          end

## Sample App
Just ask for one if needed

## Your Environment
* Ruby 2.5.1
* Spree 3.6.6
* Rails 5.2.0

## Stack Trace
```
MiniMagick::Error (`mogrify -resize product /tmp/mini_magick20181219-10826-1wpb74.jpeg` failed with error:
mogrify: invalid argument for option `product': -resize @ error/mogrify.c/MogrifyImageCommand/5862.
):

mini_magick (4.8.0) lib/mini_magick/shell.rb:17:in `run'
mini_magick (4.8.0) lib/mini_magick/tool.rb:92:in `call'
mini_magick (4.8.0) lib/mini_magick/tool.rb:40:in `new'
mini_magick (4.8.0) lib/mini_magick/image.rb:564:in `mogrify'
activestorage (5.2.2) app/models/active_storage/variation.rb:59:in `block (2 levels) in transform'
activestorage (5.2.2) app/models/active_storage/variation.rb:58:in `each'
activestorage (5.2.2) app/models/active_storage/variation.rb:58:in `block in transform'
activesupport (5.2.2) lib/active_support/notifications.rb:170:in `instrument'
activestorage (5.2.2) app/models/active_storage/variation.rb:57:in `transform'
activestorage (5.2.2) app/models/active_storage/variant.rb:122:in `transform'
activestorage (5.2.2) app/models/active_storage/variant.rb:86:in `block in process'
activestorage (5.2.2) app/models/active_storage/variant.rb:110:in `open_image'
activestorage (5.2.2) app/models/active_storage/variant.rb:85:in `process'
activestorage (5.2.2) app/models/active_storage/variant.rb:53:in `processed'
activestorage (5.2.2) app/controllers/active_storage/representations_controller.rb:12:in `show'
actionpack (5.2.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.2) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.2) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.2) lib/active_support/callbacks.rb:132:in `run_callbacks'
actionpack (5.2.2) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.2) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.2) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.2) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.2) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.2) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.2) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.2) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.2) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.2) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.2) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.2) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.2) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.2) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.2) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.2) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.2) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.2) lib/action_dispatch/routing/route_set.rb:840:in `call'
versioncake (3.4.0) lib/versioncake/rack/middleware.rb:17:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.6) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.6) lib/rack/etag.rb:25:in `call'
rack (2.0.6) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.6) lib/rack/head.rb:12:in `call'
actionpack (5.2.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.2) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.2) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.2.2) lib/rails/engine.rb:524:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

If there's anything else you need just let me know. 
Thanks for this awesome product!

**Comment by damianlegawiec** [comment]
Thanks @r-sierra for reporting this - fixed in master, we will also backport this to 3.6
