### ISSUE TITLE
Cannot search for a product/variant by SKU

### ISSUE THREAD

**Issue by mvanio** [spree/spree#9216]
Adding a product to an existing order fails with 'Loading failed' when using the 'Choose a variant' search bar in the admin/orders section. 

## Context
Spree 3.6.4, Rails 5.2.1

## Expected Behavior
The search should locate matching SKU/product names

## Actual Behavior
For some reason, the search works with part of the SKU, but not another part. E.g for SKU 'ROR-00012', the search 'ROR' fails, but the search '00012' works. Is this a known issue?

## Steps to Reproduce
Using the 3.6.5 sample store in /admin
1. click orders > new order
2. in the product search bar type 'ROR' -> 'Loading failed'
3. clear the product search and type '00012' -> SKU 'ROR-00012' is shown

## Your Environment
Log hints at product 'ROR-00011', but the search is for 'ROR-00012'...

```
ActionView::Template::Error (Spree::Variant#name delegated to product.name, but product is nil: 
#<Spree::Variant id: 1, sku: "ROR-00011", weight: 0.0, height: nil, width: nil, depth: nil, deleted_at: nil,
 discontinue_on: nil, is_master: true, product_id: 1, cost_price: 0.17e2, cost_currency: "USD", 
position: 1, track_inventory: true, tax_category_id: nil, updated_at: "2018-11-19 13:51:05", 
created_at: "2018-11-19 13:50:57">):
    1: object false
    2: node(:count) { @variants.count }
    3: node(:total_count) { @variants.total_count }
    4: node(:current_page) { params[:page] ? params[:page].to_i : 1 }
    5: node(:pages) { @variants.total_pages }
    6: 
  
spree_core (3.6.5) app/models/spree/variant.rb:9:in `rescue in name'
spree_core (3.6.5) app/models/spree/variant.rb:9:in `name'
```

-- EDITED to correct Rails version.

**Comment by PSzyszkaSpark** [comment]
Can't replicate this issue. Tested on spree 3.6.4. 
When I tape 'ROR' into the search bar it finds multiple products (20 elements).

**Comment by amalrik** [comment]
I created a repo that reproduces the issue.
[repo](https://github.com/amalrik/spree_issue_9216)

log trace is here: [logs](https://gist.github.com/amalrik/c99e88d2e1a5b3ca8eff877c16757e40)
I need to investigate further but it seems some issue between activestorage and spree 3.6
@mvanio How did you install rails 5.1 along with spree 3.6?
I've tried to install that versions but bundler complains that spree 3.6 depends on rails 5.2

**Comment by mvanio** [comment]
That's a typo - the Rails version I have here is 5.2.1.

**Comment by amalrik** [comment]
forget about what I said, after install active storage, it works:
`rails active_storage:install`
In my case the problem was I upgraded rails on the Gemfile but didn't  installed active storage.

**Comment by mvanio** [comment]
For me the issue was related to this: https://github.com/spree-contrib/spree_related_products/issues/169

Since using the workaround it is possible to search for products to add to an order. However, the products returned do not seem to have anything in common with the search term. 

Spree calls `/api/v1/products?q%5Bproduct_name_or_sku_cont%5D=hurr` and returns master products that do not have 'hurr' in either the name or sku. And it does not return all of the products. 
Instead, when searching for a variant I have found the search term `/api/v1/products?q%5Bsku_cont%5D=hurr` to work better and give me the products I need. 

I have activestorage installed but I'm not using it, the `SPREE_USE_PAPERCLIP` env var is set to `true`. Is there a way of uninstalling activestorage so I can test?

**Comment by barhum** [comment]
I was getting an error on the chrome console when posting to the api/v1/variants_controller while searching. I saw a post online that by changing this line on the model/variant.rb. I tried in production and it seems to be working now.

from: 
`self.whitelisted_ransackable_associations = %w[option_values product prices default_price]` 

to: 
`self.whitelisted_ransackable_associations = %w[option_values product_name prices default_price]`

**Comment by mma7** [comment]
i had the same issue using spree 4.1 stable, i had to modify variant.rb like this for it to work:
Using spree with locale: fr

```
def self.product_name_or_sku_cont(query)
        joins(:product, product: :translations).where("spree_product_translations.name LIKE :query OR sku LIKE :query", query: "%#{query}%")
end
```
elf.whitelisted_ransackable_associations = %w[option_values product_name prices default_price]

**Comment by damianlegawiec** [comment]
Fixed in v5
