### ISSUE TITLE
After upgrading to spree4.0.0.beta, executing `rails db:migrate:reset` will result in `uninitialized constant ChangeCollationForSpreeTagNames::ActsAsTaggableOn`

### ISSUE THREAD

**Issue by hoshinotsuyoshi** [spree/spree#9527]
After upgrading to spree4.0.0.beta from spree3.6,   executing `rails db:migrate:reset` will result in `uninitialized constant ChangeCollationForSpreeTagNames::ActsAsTaggableOn`

This behavior may not be a bug because it only runs in the development|test environment.

However, some developers may see it, so I report this issue.

Maybe  https://github.com/spree/spree/pull/9491 related.

## Context

I often execute ` RAILS_ENV=test rails db:environment:set db:migrate:reset`,  to reset test DB.

## Expected Behavior

Migration is completed with no errors.

## Actual Behavior

Migration is failed.

```
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

uninitialized constant ChangeCollationForSpreeTagNames::ActsAsTaggableOn
```

## Possible Fix

If you have a migration file like below:

```ruby
# This migration comes from spree (originally 20160511072249)
# This migration is added to circumvent issue #623 and have special characters
# work properly
class ChangeCollationForSpreeTagNames < ActiveRecord::Migration[4.2]
  def up
    if ActsAsTaggableOn::Utils.using_mysql?
      execute("ALTER TABLE spree_tags MODIFY name varchar(255) CHARACTER SET utf8 COLLATE utf8_bin;")
    end
  end
end
```

Because acts_as_taggable_on gem is no longer installed, you might update the migration file.

for example;

```diff
-   if ActsAsTaggableOn::Utils.using_mysql?
+   if defined?(ActsAsTaggableOn) && ActsAsTaggableOn::Utils.using_mysql?
```

## Steps to Reproduce

How to reproduce:

1. (I have spree3.6 app)
2. Upgrade to spree4.0.0beta
    * update `Gemfile`
3. `$ bundle update` (with some args)
4. `$ bin/rails railties:install:migrations RAILS_ENV=test`
5. `$ bin/rails db:environment:set db:migrate:reset RAILS_ENV=test`
    * error occured

<details><summary>here is backtrace:</summary>

```
(...snip...)
== 20190214113549 ActsAsTaggableOnSpreeMigration: migrating ===================
-- create_table(:spree_tags, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.0081s
-- create_table(:spree_taggings, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.0083s
-- add_index(:spree_tags, :name, {:unique=>true})
   -> 0.0090s
-- add_index(:spree_taggings, [:tag_id, :taggable_id, :taggable_type, :context, :tagger_id, :tagger_type], {:unique=>true, :name=>"spree_taggings_idx"})
   -> 0.0118s
== 20190214113549 ActsAsTaggableOnSpreeMigration: migrated (0.0374s) ==========

== 20190214113550 ChangeCollationForSpreeTagNames: migrating ==================
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

uninitialized constant ChangeCollationForSpreeTagNames::ActsAsTaggableOn
Did you mean?  ActsAsTaggableOnSpreeMigration
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/db/migrate/20190214113550_change_collation_for_spree_tag_names.spree.rb:6:in `up'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:831:in `exec_migration'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:812:in `block (2 levels) in migrate'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:811:in `block in migrate'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:465:in `with_connection'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:810:in `migrate'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:1001:in `migrate'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:1311:in `block in execute_migration_in_transaction'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:1364:in `ddl_transaction'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:1310:in `execute_migration_in_transaction'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:1282:in `block in migrate_without_lock'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:1281:in `each'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:1281:in `migrate_without_lock'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:1229:in `block in migrate'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:1382:in `with_advisory_lock'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:1229:in `migrate'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:1061:in `up'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:1036:in `migrate'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/railties/databases.rake:85:in `block (3 levels) in <top (required)>'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/railties/databases.rake:83:in `each'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/railties/databases.rake:83:in `block (2 levels) in <top (required)>'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/railties-6.0.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/railties-6.0.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/railties-6.0.0/lib/rails/command.rb:48:in `invoke'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/railties-6.0.0/lib/rails/commands.rb:18:in `<top (required)>'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/hoshino/go/src/github.com/hoshinotsuyoshi/shop/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
bin/rails:4:in `<main>'

Caused by:
NameError: uninitialized constant ChangeCollationForSpreeTagNames::ActsAsTaggableOn
Did you mean?  ActsAsTaggableOnSpreeMigration
(...snip...)

```

</details>

## Your Environment

* Version used: `4.0.0.beta`
* Gemfile and Gemfile.lock as text in a Gist: https://gist.github.com/hoshinotsuyoshi/660d0313dc4c1cc9fc3f37aec3f0a7a1

-----

Thank you !

**Comment by damianlegawiec** [comment]
You're right @hoshinotsuyoshi , we need to add this note to the upgrade guide
