### ISSUE TITLE
Running bundle exec rails c in spree extension gives console_command.rb:28:in `initialize': undefined method `sandbox=' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by githubble01** [spree/spree#9618]
New to Spree and relatively new to Rails.
I followed the getting [started guide](https://guides.spreecommerce.org/developer/tutorials/getting_started_tutorial.html) without a hitch. 

## Context
When I proceeded with the [extension tutorial](https://guides.spreecommerce.org/developer/tutorials/extensions_tutorial.html) I got stuck.

When `running bundle exec rails c` I expect the rails console to get started. I can successfully start the rails console in other projects, such as my newly created main spree project.

## Expected Behavior
Rails console starts up.

## Actual Behavior
```

Traceback (most recent call last):
	21: from bin/rails:8:in `<main>'
	20: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
	19: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
	18: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
	17: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	16: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	15: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/engine/commands.rb:9:in `<top (required)>'
	14: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
	13: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
	12: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
	11: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	10: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 9: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/commands.rb:18:in `<top (required)>'
	 8: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/command.rb:46:in `invoke'
	 7: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/command/base.rb:65:in `perform'
	 6: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 5: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 4: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 3: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/commands/console/console_command.rb:102:in `perform'
	 2: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/commands/console/console_command.rb:19:in `start'
	 1: from /Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/commands/console/console_command.rb:19:in `new'
/Users/uglyduckling/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/commands/console/console_command.rb:28:in `initialize': undefined method `sandbox=' for nil:NilClass (NoMethodError)
```

## Environment
`rails -v Rails 6.0.0`
`ruby -v ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]`
`gem` file etc.. as per tutorial.
OS: MacOs Mojave
 
Any help appreciated!

## EDIT 1
According to (my interpretation of) the instructions the rails console should be started from the extension base directory. Perhaps this is just a documentation issue...

**Comment by CharlyJazz** [comment]
i think that is a outdate tutorial

**Comment by githubble01** [comment]
Ok, so when you read up on the inner workings of rails extensions, it becomes clear that the rails console should be started in the spree project, not in the extension as the tutorial suggests.

**Comment by ToTenMilan** [comment]
You can access the extension code in rails console via application's `rails console`

Assume that I am in application root directory, and I have my extension in application's Gemfile, so I can do:
```
$ rails c
2.6.5 :001 > SomePaymentAPI
2.6.5 :002 > require 'some_payment_api'
 => true 
2.6.5 :003 > SomePaymentAPI
 => SomePaymentAPI 
2.6.5 :004 > 
```
